### ISSUE TITLE
Allow contributors to write/improve docs with Netlify CMS

### ISSUE THREAD

**Issue by erquhart** [gohugoio/hugoDocs#1006]
Netlify CMS now has [Open Authoring](https://www.netlifycms.org/docs/open-authoring/), meaning it can use forks for contributors without write access. This feature was meant to make contributing to open source docs easier, allowing writers to make edits in a CMS environment rather than editing raw frontmatter/markdown in the GitHub UI. Behind the scenes, the changes would be submitted as a PR from a fork on the user's GitHub account.

Primary benefits:
- Ensure valid changes to frontmatter
- WYSIWYG editing for writers (no raw yaml/markdown)
- automate image uploads to the right subdirectories
- Codemirror for editing code blocks

The CMS would exist entirely in the static directory - it's a 100% open source single page app, not a service. There's also no lock-in - we could remove it a month later and you'd never know it was there.

Curious if you're open to a PR to implement? I'd also handle any bugs that might surface moving forward.

**Comment by bep** [comment]
Sure, I'm curious to see how this would work.

I would suggest, if possible, that you try to add this as a Hugo Module:

https://github.com/gohugoio/hugoDocs/blob/master/config.toml#L21

Note that the mounting of folders/files is pretty flexible, so it does not matter too much how the source repo looks like as long as you mount it to somewhere below `static`, see:

https://gohugo.io/hugo-modules/configuration/#module-config-mounts

**Comment by erquhart** [comment]
That makes a lot of sense, looking into it 👍

**Comment by bep** [comment]
@erquhart note that I don't know much about the CMS setup. If you need some build-specific settings etc., that should be possible, of course. Let me know if you need my help.

**Comment by erquhart** [comment]
Thanks @bep. The customization stuff is pretty site specific so a lot of it will end up in the repo, although I’m using the module approach during development to see how much can be split off. I’ll comment with any questions 👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
