### ISSUE TITLE
Document safe.SafeJSStr template func

### ISSUE THREAD

**Issue by digitalcraftsman** [gohugoio/hugoDocs#101]

**Comment by rdwatters** [comment]
I didn't realize this existed. This is different from https://gohugo.io/functions/safejs/?

**Comment by moorereason** [comment]
Yes, it's different.  See https://golang.org/pkg/html/template/.

I believe I added it while building the namespaces so that we covered everything in `html/template`.

**Comment by digitalcraftsman** [comment]
It was registered in the funcMap but to be honest I wasn't aware of it's existence either.

**Comment by moorereason** [comment]
Yeah, that's my fault.  The migration to namespaces was monotonous and time-consuming.  I forgot to document SafeJSStr along the way and then forgot about it in the end.
