### ISSUE TITLE
content-management/organization/index.md has unreadable (broken?) figures  

### ISSUE THREAD

**Issue by saper** [gohugoio/hugoDocs#1010]
Reading [content organization page](https://github.com/gohugoio/hugoDocs/blob/bd0e15bb6063f7ad4f0c47eb33c8c0c23c962d13/content/en/content-management/organization/index.md) is difficult because the figures seem to be unreadable or broken. Also the ASCII art graphics does not display well (I like ASCII art but that does not match the way the page is written).

Example:
![page-bundles-shot](https://user-images.githubusercontent.com/248374/72253988-1f878b80-3603-11ea-90df-dc0281387db2.png)

**Comment by ndalliard** [comment]
I've build it locally and get `<!--raw HTML omitted-->`, that has something to do with Goldmark, the new default Markdown library. The `improc` shortcode is used to embed the image: https://github.com/gohugoio/hugoDocs/blob/master/layouts/shortcodes/imgproc.html
