### ISSUE TITLE
"Step 4: Add Some Content" gives no guidance for adding content

### ISSUE THREAD

**Issue by dvergin** [gohugoio/hugoDocs#1011]
This is the sort of thing that is obvious to people familiar with the software in question. But...

...the Quick Start gives no indication about how a first-time user would "add some content" Does the new content go below what is there? Before the second "---"? After that "---" line? Does it need some particular format or keywords? Use MarkDown? Or HTML? Just a couple of quick hints would allow the user to try a few things, see what happens, and go from there.

**Comment by rafalkrupinski** [comment]
Same problem

I've tried adding some content and I'm getting an empty page in the browser, and a warning from hugo server
