### ISSUE TITLE
Typo? :REND on .RenderString samples

### ISSUE THREAD

**Issue by davidsneighbour** [gohugoio/hugoDocs#1019]
The samples on https://gohugo.io/functions/renderstring/ show the following:

```
{{ $optBlock := dict "display" "block" }}
{{ $optOrg := dict "markup" "org" }}
{{ "**Bold Markdown**" | $p.RenderString }}
{{  "**Bold Block Markdown**" | $p.RenderString  $optBlock }}
{{  "/italic org mode/" | $p.RenderString  $optOrg }}:REND
```

The `:REND` in the last line is nowhere explained. I feel like this might be a typo? If not, we should add some notes about this.

**Comment by bep** [comment]
It should be removed. I guess I copy-pasted it from some test where I often mark start/end by some construct to check for any whitespace issues.
