### ISSUE TITLE
Can't start hugo to serve docs information

### ISSUE THREAD

**Issue by sgharms** [gohugoio/hugoDocs#1025]
1. Clone `https://github.com/gohugoio/hugoDocs.git`
2. `cd hugoDocs`
3. `hugo server`

Error:
<pre>
Building sites … WARN 2020/01/27 23:27:44 found no layout file for "HTML" for "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/01/27 23:27:44 found no layout file for "HTML" for "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/01/27 23:27:44 found no layout file for "HTML" for "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/01/27 23:27:44 found no layout file for "HTML" for "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/01/27 23:27:44 found no layout file for "HTML" for "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
(.... much repetition .... )
WARN 2020/01/27 23:27:29 make non-relative ref/relref page reference(s) in page "functions/merge.md" absolute, e.g. {{< ref "/blog/my-post.md" >}}
Total in 380 ms
Error: Error building site: "/tmp/hugoDocs/content/en/functions/truncate.md:27:1": failed to render shortcode "note": failed to process shortcode: "/tmp/hugoDocs/layouts/shortcodes/note.html:4:4": execute of template failed: template: shortcodes/note.html:4:4: executing "shortcodes/note.html" at <partial "svg/exclamation.svg" (dict "size" "20px")>: error calling partial: partial "svg/exclamation.svg" not found
</pre>

I don't think the load of WARN's is great, but I think the Error is distinctly the problem here. The shortcode definition looks decent, but it's referring to an svg file. That file is not in `layouts/partials/exclamation.svg`, but it is in `./_vendor/github.com/gohugoio/gohugoioTheme/layouts/partials/svg/exclamation.svg`.

Moving `svg/exclamation.svg` into the `partials` directory makes this error go away, but then I run into another one about `code-toggle`. Based on the README, I don't _think_ I'm doing this wrong.

I tried running a bisect to try to find out what changed, but I didnt have much luck finding a SHA that built (for the record, v0.9 did not start `hugo server` cleanly).

Am I missing something here, perhaps a version incompatibility?

**Comment by bep** [comment]
>Am I missing something here, perhaps a version incompatibility?

The Hugo Docs needs a fairly new Hugo version.

**Comment by sgharms** [comment]
Confirmed. At 0.63 things worked as expected.
