### ISSUE TITLE
Notable for Showcase

### ISSUE THREAD

**Issue by stephenkeep** [gohugoio/hugoDocs#1028]
Hi Hugo Team!

My site is built using Hugo and the site is dedicated to teaching people about the web. Throughout my articles, I talk about Hugo and static site generators. 

I want to teach people that there is life beyond WordPress.

Before submitting the PR to be included in the showcase, could I get a thumbs up on whether my page is Notable enough?

[https://pagedart.com](https://pagedart.com)

Thanks

**Comment by Resonanz** [comment]
Your website looks nice and clean interns of the design! Have you released the code for it on github and added it to the Hugo themes page?

**Comment by bep** [comment]
@stephenkeep I will think about it a little. Please ping this issue if I forget ... My GitHub notifications is a little bit overloaded these days. It's a very useful site for many, I'm sure, but I'm not sure if it's "notable enough" as a showcase.

**Comment by stephenkeep** [comment]
Thanks @bep No problem at all just wanted to spread the Hugo love!

@Resonanz that is a great idea I will look into that!

**Comment by celtic-coder** [comment]
Hi @stephenkeep,

I checked the source for the home page but it doesn't mention Hugo as being the site generator? 

Is there a link to Hugo elsewhere on the site, perhaps? 

Kind Regards, 
Liam
