### ISSUE TITLE
Some template functions aren't part of a namespace

### ISSUE THREAD

**Issue by digitalcraftsman** [gohugoio/hugoDocs#103]
This issue also proposes where these functions shall belong to. I took the freedom to propose an entirely new namespace for some functions.

Feel free to comment.

### `time` namespace

- time
- unix
- adddate

### `collections` namespace

- range

### `fmt` namespace

- format

### New `menus` namespace 

- haschildren
- hasmenucurrent
- ismenucurrent

### `partial` namespace

- render

---

### remaining functions

- get
- getpage
- len
- param
- scratch
- with

**Comment by bep** [comment]
It would be better if you could move this issue to the /hugo repo -- where we have to apply the fixes.

**Comment by digitalcraftsman** [comment]
Makes sense.
