### ISSUE TITLE
TOCSS: failed to transform "scss/main.scss" (text/x-scss): SCSS processing failed

### ISSUE THREAD

**Issue by meichangliang** [gohugoio/hugoDocs#1051]
It has been used according to the instructions, hugo-extended , but still not successful

![图片](https://user-images.githubusercontent.com/24769632/76169446-2b32a100-61b3-11ea-8678-ef8ca1d8f287.png)

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
