### ISSUE TITLE
Document what version a feature was added

### ISSUE THREAD

**Issue by jtooker** [gohugoio/hugoDocs#1070]
When a documented feature does not work, it is unclear if it is user error, a bug in the code or the version of hugo predates the feature.  

For example, I wanted to use the `Summary` front matter variable [as documented](https://gohugo.io/content-management/summaries/#summary-splitting-options).  I tried it and it did not seem to work.  I found this [stackoverflow post](https://stackoverflow.com/questions/59014231/); the person with the original problem said upgrading fixed it, but that was not terribly helpful.  I had to search through release notes to find that [the feature was added in v0.55.0](https://github.com/gohugoio/hugo/releases/tag/v0.55.0).

It would have been nicer if the [documentation](https://gohugo.io/content-management/summaries/#summary-splitting-options) had flagged the version that feature was added so that I could know it was unavailable to me or that I would need to upgrade.  For example, [Qt documentation](https://doc.qt.io/qt-5/qremoteobjectnode.html#addClientSideConnection) marks when each function (or feature, or class) was added.

**Comment by coliff** [comment]
Good feedback @jtooker  👍  - we've started documenting which version a feature was added in the docs much more now.
