### ISSUE TITLE
Quick start guide does not work 

### ISSUE THREAD

**Issue by mattiashem** [gohugoio/hugoDocs#1071]
What version of Hugo are you using (hugo version)?
FROM golang

RUN mkdir /root/src
WORKDIR /root/src
RUN git clone https://github.com/gohugoio/hugo.git
WORKDIR /root/src/hugo
RUN go install --tags extended
WORKDIR /src/

Does this issue reproduce with the latest release?
Yess cloned the latest git

root@2b21e24c1a12:/src# hugo new site quickstart
Congratulations! Your new Hugo site is created in /src/quickstart.

Just a few more steps and you're ready to go:

1. Download a theme into the same-named folder.
   Choose a theme from https://themes.gohugo.io/ or
   create your own with the "hugo new theme " command.
2. Perhaps you want to add some content. You can add single files
   with "hugo new /.".
3. Start the built-in live server via "hugo server".

Visit https://gohugo.io/ for quickstart guide and full documentation.
root@2b21e24c1a12:/src# cd quickstart/
root@2b21e24c1a12:/src/quickstart# git init
Initialized empty Git repository in /src/quickstart/.git/
root@2b21e24c1a12:/src/quickstart# git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke
Cloning into '/src/quickstart/themes/ananke'...
remote: Enumerating objects: 1613, done.
remote: Total 1613 (delta 0), reused 0 (delta 0), pack-reused 1613
Receiving objects: 100% (1613/1613), 4.22 MiB | 6.83 MiB/s, done.
Resolving deltas: 100% (892/892), done.
root@2b21e24c1a12:/src/quickstart# echo 'theme = "ananke"' >> config.toml
root@2b21e24c1a12:/src/quickstart# hugo new posts/my-first-post.md
Error: module "mytheme" not found; either add it as a Hugo Module or store it in "/src/quickstart/themes".: module does not exist
Tested it 2 weeks ago and then today again. Build the docker image to get the latest Hugo, Then run the commands from the quickstart.

**Comment by arcooke** [comment]
Same issue here, on Solus

```
$ hugo version
Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: 2020-03-25T19:59:31Z
```

```
me@ac-desktop ~/Source/ramblings $ git init
Initialized empty Git repository in /home/me/Source/ramblings/.git/
me@ac-desktop ~/Source/ramblings $ git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke
Cloning into '/home/me/Source/ramblings/themes/ananke'...
remote: Enumerating objects: 1613, done.
remote: Total 1613 (delta 0), reused 0 (delta 0), pack-reused 1613
Receiving objects: 100% (1613/1613), 4.22 MiB | 12.75 MiB/s, done.
Resolving deltas: 100% (892/892), done.
me@ac-desktop ~/Source/ramblings $ hugo new posts/first.md
Error: module "gohugo-theme-ananke" not found; either add it as a Hugo Module or store it in "/home/me".: module does not exist
me@ac-desktop ~/Source/ramblings $ hugo new posts/first.md
Error: module "gohugo-theme-ananke" not found; either add it as a Hugo Module or store it in "/home/me/Source/ramblings/themes".: module does not exist
me@ac-desktop ~/Source/ramblings $ 
```

**Comment by arcooke** [comment]
Fixed.  In the copied `config.toml`, replace:
`theme = "gohugo-theme-ananke"`
with
`theme = "ananke"`

**Comment by mattiashem** [comment]
`root@8ce5674c51b9:/src/quickstart# cat config.toml 
baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"
root@8ce5674c51b9:/src/quickstart# hugo new posts/first.md
Error: module "mytheme" not found; either add it as a Hugo Module or store it in "/src/quickstart/themes".: module does not exist
root@8ce5674c51b9:/src/quickstart#`


Nope same problem for me

**Comment by ret394** [comment]
I would stick with the quickstart guide if you want to get stuff done.

>Download a theme into the same-named folder.

or get really familiar with the hugo docs and codebase. and go.

In any case, I can fix it(issue and frameworks in general) easily. Or guide you how to fix similar issues. If paid to do so. So let me know, ping me @ret394.

thanks. have a nice day. keep up the great work. 👏

[ret394](https://github.com/ret394)

**Comment by songproducer** [comment]
I resolved by running this:
git submodule update --init --recursive

**Comment by OTLabs** [comment]
Running this sequence today on Windows10 machine poduced following error message:

```
Building sites … Built in 25 ms
Error: Error building site: TOCSS: failed to transform "ananke/css/main.css" (text/css): resource "css/ananke/css/main.css_bb5467e0521bbea6b1e66429f6ec028e" not found in file cache
```

```
hugo.exe version
Hugo Static Site Generator v0.69.0-4205844B windows/amd64 BuildDate: 2020-04-10T09:11:37Z
```

**Comment by jmooring** [comment]
@OTLabs This issue is closed. 

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
