### ISSUE TITLE
resources.PostProcess Docs

### ISSUE THREAD

**Issue by acahir** [gohugoio/hugoDocs#1080]
The [docs](https://gohugo.io/hugo-pipes/postprocess/) for the new PostProcess are slightly confusing:

Limitation 1 states that this only works for *.html files, but the example uses a CSS file. Seems like a contradiction to me.

I'm not sure I'm clear enough on the new feature to know the right way to correct this myself, sorry.

**Comment by bep** [comment]
Yes, I see how that is confusing.

I meant that it only works for templates that produces HTML files -- in Hugo you can also do JSON and anything else. So, if you try do use PostProcess in a JSON template it would not work.
