### ISSUE TITLE
Please document the Extended version

### ISSUE THREAD

**Issue by rgov** [gohugoio/hugoDocs#1106]
I've been using Hugo for a while but just learned about the existence of "Hugo Extended" that seems to have SCSS support. However the differences between the versions are not really highlighted explicitly in the documentation so it's not really clear.

1. Why would I ever _not_ want to use the extended version?

2. The Install page explains how to get it in certain circumstances. But it is not mentioned for macOS, even though in the Releases page there's both a regular and extended version. It turns out that `brew` installs the extended version by default.

3. The only real documentation seems to be a minor "note" in the [0.43 release notes](https://gohugo.io/news/0.43-relnotes/).

My true preference though would be to eliminate this distinction.

**Comment by rgov** [comment]
Thanks for moving it.

I don't presume to know all use cases of Hugo out there, but I am struggling to picture a need to build a static site in an environment that must be so minimal it cannot even include libc. Is this really a constraint? Well anyway, that can be another discussion beyond just documenting the differences.

**Comment by bep** [comment]
>, but I am struggling to picture a need to build a static site in an environment that must be so minimal it cannot even include libc. 

You asked for some arguments. The main argument is the build chain. I spent 2 long days filled with gray hairs to get the extended build up and running on Circle Ci for Linux, MacOs and Windows. Extending that to the other platforms was not in my time budget ...

**Comment by davidsneighbour** [comment]
See #1152 where we will continue and finish the discussion.
