### ISSUE TITLE
Update Github Pages Deployment to Include GitHub Actions

### ISSUE THREAD

**Issue by faraixyz** [gohugoio/hugoDocs#1120]
I was looming one the page for [how to host Github pages for organization/user sites](https://gohugo.io/hosting-and-deployment/hosting-on-github/#github-user-or-organization-pages) and I’m thinking of updating the docs to include GitHub actions. That way you can do everything on one repo, with one branch having the source files and the master branch only used for publishing.

**Comment by coliff** [comment]
hey @faraixyz - that would be great!

PR would be very welcome - I think a lot of folks would find that helpful.

**Comment by davidsneighbour** [comment]
I did some work recently to test my PHP application with Github Actions and it's basically a docker container that runs an operating system and you define some steps that are taken. Maybe existing docker solutions can be adapted for that. Put the deploy script into the repository and execute from within the container... great idea.

BUT: careful with the run duration. Free accounts have only (?) 3000 minutes available before they bill you. I used up 500 minutes in short time by testing around ;)

**Comment by UtkarshVerma** [comment]
I use GitHub Actions for building my website. I was planning to write up a blog post for it, but I can also add it to the docs instead. What's the maintainer's take on this?

**Comment by gagarine** [comment]
Sorry I made a duplicate the wrong repository https://github.com/gohugoio/hugo/issues/8204 .

One simple way was featured on the GitHub blog: https://github.blog/2020-03-22-github-action-hero-shohei-ueda/ . The actions: https://github.com/marketplace/actions/github-pages-action

That would be a great addition to the documentation. Eventually Hugo could provide an "official" action too.

**Comment by yangliuly1** [comment]
Hi, me too. Such as my blog is 'https://xxx.github.io/blog/', but my post is `https://xxx.github.io/blog/blog/posts/`, 
so how to solve it.
Thank you for your reply!
