### ISSUE TITLE
Capital characters or not capital character, that is the question

### ISSUE THREAD

**Issue by juh2** [gohugoio/hugoDocs#114]
In 
https://gohugo.io/templates/output-formats/#output-formats
we have an example like this:

```
[outputFormats.MyEnrichedFormat]
mediaType = "text/enriched"
baseName = "myindex"
isPlainText = true
protocol = "bep://"
```

But in the list of parameters all parameters are written with a capital first letter.

This is kind of confusing.

**Comment by digitalcraftsman** [comment]
Hello @juh2,

at the first time this can be confusing. [This forum thread](https://discourse.gohugo.io/t/config-params-should-be-all-lowercase-or-not/5051) should clarify some things.

**Comment by bep** [comment]
The forum thread may clarify, but I agree with @juh2 -- there should be a symmetry there.

**Comment by digitalcraftsman** [comment]
> there should be a symmetry there.

In other words: turn camelCase- and PascalCase-formatted text into lowercase in the examples, right?

**Comment by bep** [comment]
>In other words: turn camelCase- and PascalCase-formatted text into lowercase in the examples, right?

No, **this issue** is about PascalCase that should be camel.
