### ISSUE TITLE
Typo on Docker section of installation page

### ISSUE THREAD

**Issue by jenewland1999** [gohugoio/hugoDocs#1147]
Hi there,

I was reading through the installation documentation and I happened to notice that the section on Docker appears to have a typo. 

## Description

The section currently reads as:

> We currently do not official Hugo images for Docker, but we do recommend these up to date distributions:

I believe it's supposed to say:

We currently do not **offer** official Hugo images for Docker, but we do recommend these up to date distributions:

## Relevant Link(s)

https://gohugo.io/getting-started/installing#docker

## Relevant Screenshot(s)

![Screenshot of the typo on Hugo docs website](https://user-images.githubusercontent.com/34895363/84893362-03e34e00-b097-11ea-8ea5-27ac5fde03a9.png)

**Comment by coliff** [comment]
Thanks for reporting. I opened a PR for it.

**Comment by jenewland1999** [comment]
No problem! ☺️
