### ISSUE TITLE
Please document the difference between the "extended" and non-"extended" versions

### ISSUE THREAD

**Issue by nelhage** [gohugoio/hugoDocs#1152]
I'm setting up a new site with Hugo for the first time, after happily using hugo for years. I'm exploring themes, and many of them now cite that they need the "extended" version. I've now spent half an hour trying to figure out the difference between the "extended" and non-"extended" versions and why I should care, and I'm still pretty baffled. The "extended" version seems to support SASS/SCSS, but I can't figure if there's a reason I might not want it. Is it slower? Less reliable or portable somehow?

I've extensively searched the documentation and the forum, and I can't find an explanation. Please consider writing a page somewhere in the documentation explaining why there is this confusing bifurcation of hugo into two incompatible projects, and helping users make decisions about which one to use.

**Comment by bep** [comment]
I agree.

* The only functional difference is SASS/SCSS
* The technical build time difference is that it requires a C++ build chain for the target platform to build, the reason why we currently only build the extended for 3 platforms (Windows, Linux, MacOS)
* Binaries are slightly less portable as you need a compatible Libc version on your computer (for Windows we build a fully static version as Libc is rather uncommon unless you have Visual Studio or something installed).

**Comment by kenmorse** [comment]
Maybe a note in the "Install Hugo" page?

**Comment by davidsneighbour** [comment]
But @kenmorse not only that. Let's introduce some kind of marker (label in bootstrap lingo?) that shows people on subsequent pages of the documentation that the extended version is required for this to work.

**Comment by faraixyz** [comment]
I put in a pull request a few weeks ago addressing this. https://github.com/gohugoio/hugoDocs/pull/1124

**Comment by tronorama** [comment]
> I agree.
> 
>     * The only functional difference is SASS/SCSS

I'm confused and I still don't understand what I can do with the mythical extended version that I cannot do with the normal version (?).

I seem to already be making use of SASS/SCSS with the regular binary on Manjaro (via the regular repository), as well as themes that depend on SASS/SCSS. Is there still some actual difference in the "extended" version (which seems to be available via the AUR)?

I know it's been a year since this issue was created, have the two projects been merged? Will they be in the future?

**Comment by faraixyz** [comment]
Assuming the package is this one (https://archlinux.org/packages/community/x86_64/hugo/) it uses the extended one by default (https://github.com/archlinux/svntogit-community/blob/08a9d645782d2d8fefd108c9836247cae3772e41/trunk/PKGBUILD#L27).

As of writing this, the differences are that the extended version has libsass for Sass/SCSS (although the normal binary does this uses dartsass) and supports webp image processing.

**Comment by bep** [comment]
>As of writing this, the differences are that the extended version has libsass for Sass/SCSS (although the normal binary does this uses dartsass) and supports webp image processing.

The above is correct.

**Comment by breyed** [comment]
The lack of a definition of "extended" makes the quick start not so quick for Windows users. A windows user going through the [Quick Start](https://gohugo.io/getting-started/quick-start/) page gets sent over to [Installing Hugo](https://gohugo.io/getting-started/installing). On that page, in the Windows section, he's presented with the choice of installing hugo or hugo-extended. The only guidance provided is:

> Or if you need the “extended” Sass/SCSS version

It's not clear what this means. Is Sass/SCSS the only extension or just a primary one? The user now needs to go on a hunt.
