### ISSUE TITLE
Accessibility / Seo ranks less than 80 on some pages

### ISSUE THREAD

**Issue by nel417** [gohugoio/hugoDocs#1160]
Hello everyone, I was looking into a few pages on the site (https://gohugo.io/) and the accessibility and SEO are dangerously low. Tested with lighthouse and axe

**Home page / Themes page / Docs page:**

Accessibility 79: 
[role]s are not contained by their required parent element
Background and foreground colors do not have a sufficient contrast ratio.
Image elements do not have [alt] attributes
Lists do not contain only `<li>` elements and script supporting elements (`<script>` and `<template>`).

SEO 78:
needs a meta description and images need alt tags

Just thought I would throw this into an issue.

Thanks everyone!

**Comment by coliff** [comment]
thanks for reporting this. A few of these have been fixed and I'm about to open a PR for the meta description. These issues are related to the theme so I'll see about moving this issue to that projects repo.

**Comment by genetikdisoda** [comment]
Few edits remaining https://pagespeed.web.dev/report?url=https%3A%2F%2Fgohugo.io%2F

**Comment by coliff** [comment]
We're doing much better than before (not less than 80 on some pages)... so I'll close this issue now.

![image](https://user-images.githubusercontent.com/1212885/202937431-4e2b7fc7-2539-412d-887e-7a7248f86b5b.png)
