### ISSUE TITLE
Branch bundles with "index.md" pages don't render child leaf bundles

### ISSUE THREAD

**Issue by CraigHawker** [gohugoio/hugoDocs#1164]
I have been looking at whether migrating to Hugo could solve some performance issues we have on a fairly large (and growing) Jekyll-based site.  As part of my testing I simply copied across about 1000 pages from the existing Jekyll site and placed them inside the Hugo site.

Basically: all folders (regardless of depth) contained "index.md" files, which is perfectly valid in Jekyll and other systems, but these stopped the child leaf bundles from being rendered.  I documented the exact problem here: https://discourse.gohugo.io/t/content-depth-migrating-from-jekyll/26635/6

The current documentation (https://gohugo.io/content-management/organization) does show site samples with this naming convention, but the impact of an incorrectly-named file is not called out.

As a newbie I found the content provided by Joe Mooring (see the "explanation" section) very useful.  I feel that incorporating it - or something similar - would help a lot of people who are testing out Hugo.

Apologies if I've misused some terminology above.

**Comment by gunteet** [comment]
Is this a documentation or Hugo feature request? Seems the latter.

**Comment by jmooring** [comment]
This will be addressed in https://github.com/gohugoio/hugoDocs/issues/2307
