### ISSUE TITLE
Sponsor links don't respect default browser behaviour

### ISSUE THREAD

**Issue by nmokkenstorm** [gohugoio/hugoDocs#1169]
While browsing the [homepage](https://gohugo.io) for the first time I was curious about the sponsors, but clicking on the links while holding shift or cmd does not respect the browser default behaviour, this feels like an accessibility issue. I'm willing to look into a fix, but I'm a web developer with 0 knowledge of Golang, so I figured I'd raise an issue first.

For what it's worth, I'm running Chrome 83.0.4103.116 on macOS Catalina 10.15.5

**Comment by davidsneighbour** [comment]
Running on Ubuntu 20.04 it works as expected. With a SHIFT it opens a new window in the foreground, with CTRL it opens a new window with a foreground. Please open a thread at discourse.gohugo.io but I think this is not a bug. To check for accessibility issues use a service like listed on https://www.w3.org/WAI/ER/tools/

**Comment by nmokkenstorm** [comment]
As mentioned, I'm running OSX, so it might be a Mac specific issue. I'll spin up an Ubuntu and Windows machine to check, and have a look at the discourse page, thanks.

**Comment by bep** [comment]
I have seen some issues myself, and we should fix it. The sponsor links has som JS tracking code (for GA stats) -- maybe that is it. A fix would be appreciated. Don't need to know Go to fix it, the Go templates we use should be fairly simple to understand -- as long as you have Hugo installed.

**Comment by nmokkenstorm** [comment]
Yeah, I've looked into it and I think I have a fix available, still cleaning it up a bit. The offending code is [here](https://github.com/gohugoio/gohugoioTheme/blob/master/layouts/partials/home-page-sections/sponsors.html#L16) and [here](https://github.com/gohugoio/gohugoioTheme/blob/master/layouts/partials/gtag.html#L21). Basically `return false` disables handling of the event, and the callback in the gtag handler doesn't respect default browser behaviour.

My experimentation got me two possible solutions: don't `return false` and rely on the async function to do its thing, or manually track which keys are down and assign behaviour to that. In my opinion the latter doesn't scale, and still won't respect any custom settings a user might have.
