### ISSUE TITLE
Document js.Build

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#1171]
For the options, see:

https://godoc.org/github.com/gohugoio/hugo/resources/resource_transformers/js#Options

```html
{{ $js := resources.Get "js/main.ts" | js.Build }}
```

=> "js/main.js"

```html
{{ $js := resources.Get "js/main.ts" | js.Build "mypath.js" }}
```

```html
{{ $js := resources.Get "js/main.ts" | js.Build (dict "targetPath" "mypath.js" "externals" (slice "react" "react-dom") "minify"{ true) }}
```

Keywords from the above:

* The target will always be a *.js file -- if not set it will use the input as a template
* The loader will be determined by the MIME type/file extension: Current valid extensions are js, ts, jsx, tsx.

I would love some help on getting some basic documentation about this great new feature. Any takers? I think it belongs as a new page in the "Hugo Pipes" section: "JavaScript Building" or something.

**Addon**: I think an important disclaimer in this docs is that is currently does not fully support Hugo's union filesystem. I will work to get a proper fix for that, but if you have a theme component, I suspect that you need to build that to `/resources/_gen` to make it work. It walks upwards to find `node_module` folders, which is also worth noting.

**Comment by regisphilibert** [comment]
I'd love to help, but my understanding of bundlers, transpile etc... is limited.

For example, I would think that, because ESBuild transpiles, Babel is not needed anymore? But then I miss on the concept of Babel's `preset` and how they translate in the ESBuild universe...

**Comment by bep** [comment]
> But then I miss on the concept of Babel's preset and how they translate in the ESBuild universe...

The closest mapping from Babel's presets are the `target` option:

```go
   // The language target.
    // One of: es2015, es2016, es2017, es2018, es2019, es2020 or esnext.
    // Default is esnext.
    Target string
```

So, `esbuild` also supports having browsers as `target`, but Hugo does not support that (at least not yet).

A preset in Babel may look like this:

```
{
  "targets": {
    "chrome": "58",
    "ie": "11"
  }
}
```

As I said, we may add the browser option, too, but I suspect it's easier to just target some minima `es*` version, e.g.:

{{ $js := resources.Get "js/main.ts" | js.Build (dict "targetPath" "mypath.js" "target" "es2016") }}

Which will produce compatible code for these browsers:

https://kangax.github.io/compat-table/es2016plus/

`esnext` (default) will, I assume, let any new language feature stay as is.

**Comment by regisphilibert** [comment]
I'm trying this out with some use cases and I have trouble using it with React at the moment: From ESBuild [doc](https://github.com/evanw/esbuild#using-with-react):

> If you're using esbuild to bundle React yourself instead of including it with a <script> tag in your HTML, you'll need to pass '--define:process.env.NODE_ENV="development"' or '--define:process.env.NODE_ENV="production"' to esbuild on the command line.

I'm not sure how this should be addressed. I know for sure a lot of people might try this out with react components, so if we have a little note/disclaimer with a work around that would swell :)

**Comment by AbeEstrada** [comment]
I made React work adding this line before loading the `.js` file, of course it is not ideal:

```js
<script>var process = { "env": { "NODE_ENV": "development" } }</script>
```

The Hugo implementation includes [`Defines`](https://github.com/gohugoio/hugo/blob/9df98ec49ca9fa326125ccfee626b6e46c6ab14b/resources/resource_transformers/js/build.go#L69) but is not exposed in the options to pass `js.Build`

**Comment by bep** [comment]
>I know for sure a lot of people might try this out with react components

You currently can:

1. Pull in the React runtime via CDN
2. Add react/react-dom to the Externals

We may add `Defines` to the options if someone can figure out what it does.

**Comment by regisphilibert** [comment]
Thank you both!

**Comment by regisphilibert** [comment]
I'll try `.Define` as it seems to be what the documentation mention in there react section, substitute some code with something else.

> --define:process.env.NODE_ENV="development"

**Comment by regisphilibert** [comment]
I thought it was there, undocumented. My bad.

> We may add Defines to the options if someone can figure out what it does.

I suppose it's what is in the react section quoted above. as a CLI flag: `--define:process.env.NODE_ENV="development"` will replace `process.env.NODE_ENV` with the `production` string. I suppose we can declare several defines so it would be a slice looking something like:

```
{{ $options := dict "defines" (slice `process.env.NODE_ENV="development"`) }}
```

Here's their warning about the quotes:
> Note that the double quotes around "production" are important because the replacement should be a string, not an identifier. The outer single quotes are for escaping the double quotes in Bash but may not be necessary in other shells.

**Comment by regisphilibert** [comment]
Ok... well I've tried many approaches and I'm obviously doing something wrong (following https://github.com/evanw/esbuild#using-with-react)

I setup this minimal (failing) repo: https://github.com/regisphilibert/gohugo-hugoDocs-issue-1171
Script: https://github.com/regisphilibert/gohugo-hugoDocs-issue-1171/blob/master/assets/index.jsx
Template: https://github.com/regisphilibert/gohugo-hugoDocs-issue-1171/blob/master/layouts/index.html

If someone has a few minutes to take a look 🤷

**Comment by bep** [comment]
@regisphilibert I have created a PR. See the commit comments, but need the latest Hugo.

**Comment by regisphilibert** [comment]
Ok, I've updated the repo upthere, I think I will need some help from someone knowing their way around react (without a framework/starter).

Now I'm stuck with the `Uncaught SyntaxError: Cannot use import statement outside a module` which is clearly due to my very limited knowledge of js modules...

Anyone pulling the repo can use `74.2` as it's shipped as a binary with it. `bin/hugo* server` will do it...

**Comment by bep** [comment]
@regisphilibert see my PR.

**Comment by bep** [comment]
https://github.com/regisphilibert/gohugo-hugoDocs-issue-1171/pull/1

**Comment by bep** [comment]
That said, using React doesn't seem to (to me, anyway) be a very relevant documentation example.

**Comment by regisphilibert** [comment]
Sorry missed your PR addressing my major blunder. Will wrap this up tomorrow with a better example than react.
