### ISSUE TITLE
Related content default configuration appears to be incorrect

### ISSUE THREAD

**Issue by RealOrangeOne** [gohugoio/hugoDocs#1179]
When attempting to extend the existing configuration for `related`, i'd expect that adding the default configuration in would change nothing, and it could be tweaked from there.

Adding the default config from https://gohugo.io/content-management/related/#default-configuration makes any related content disappear, likely because the indices and weighting don't match the default. 

The default actually works really well, I just wanted to toggle `includeNewer`. I don't want to have to reverse-engineer the exact values. 

```
$ hugo version
Hugo Static Site Generator v0.73.0/extended linux/amd64 BuildDate: unknown
```

**Comment by bep** [comment]
It's pretty clearly documented:

>If you add a related config section, you need to add a complete configuration. It is not possible to just set, say, includeNewer and use the rest from the Hugo defaults.

**Comment by RealOrangeOne** [comment]
I'll admit it took me far longer to notice that than it should, but that's what I tried, before opening this issue. I copied the "default configuration" exactly into my `config.yml`, with no edits, and the related content changed drastically (and in most cases vanished)

**Comment by bep** [comment]
I have checked, and the defaults matches the documentation, so I'm not sure what's happening.

**Comment by RealOrangeOne** [comment]
Interesting, thanks for checking. In that case it's definitely not a documentation issue. I'll keep having a play around and maybe open an issue against the main repo if I find something concrete.
