### ISSUE TITLE
Add canonical header element

### ISSUE THREAD

**Issue by Jos512** [gohugoio/hugoDocs#118]
Google [advices](https://support.google.com/webmasters/answer/139066?hl=en) to use canonical URLs to indicate the preferred page version. I think this should be added to Hugo docs too. Especially since there are currently two versions (http and https). But it might have some benefit in the future too. I cannot think of situations in which it would be harmful.

For instance, something like the following in the page's head:

```
<link href="https://gohugo.io/variables/page/" rel="canonical">
```

**Comment by rdwatters** [comment]
I would agree with this, @Jos512. That said, this needs to happen at the templating layer, which is part of our theme. I'm going to close this here and have opened a new issue on your behalf here:

https://github.com/gohugoio/gohugoioTheme/issues/64

**Comment by budparr** [comment]
I'm happy to add this, but please point me to the duplicate links on the site. Thanks!
