### ISSUE TITLE
Invalid "Sections" Link

### ISSUE THREAD

**Issue by NicoHood** [gohugoio/hugoDocs#1186]
https://gohugo.io/content-management/sections/

Source:
https://github.com/gohugoio/hugoDocs/blob/master/content/en/content-management/sections.md
https://github.com/gohugoio/hugoDocs/blob/master/content/en/readfiles/sectionvars.md

Both links in `.Section` and `.Sections` point to nowhere. I am also not sure what the docs mean, so I have no idea how to correct it best. Should be easy for you though.

**Comment by NicoHood** [comment]
Still valid

**Comment by jmooring** [comment]
I'm not sure when this was fixed, but it was fixed.
