### ISSUE TITLE
How to install Hugo extended on Mac?

### ISSUE THREAD

**Issue by fvlasie** [gohugoio/hugoDocs#1198]
Hello all,

I am trying to install Hugo extended on the Mac platform. Apparently Brew does not do it but I have also tried building from source. The instructions do not discuss the extended version in the Mac install section. When I try building with ```go install --tags extended```
I get an error: ```# github.com/bep/golibsass/internal/libsass
In file included from inspect.cpp:2:
../../go/pkg/mod/github.com/bep/golibsass@v0.6.0/internal/libsass/../../libsass_src/src/inspect.cpp:1069:20: warning: expression with side effects will be evaluated despite being used as an operand to 'typeid' [-Wpotentially-evaluated-expression]```

Thank you!

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
