### ISSUE TITLE
Deploying Github Project Pages requires setting up Hugo's Configuration Directory

### ISSUE THREAD

**Issue by jzinner** [gohugoio/hugoDocs#1224]
Please add this section "Setup Hugo's Configuration Directory" in the "Github Project Pages" Deploy article.  

Because of fancy url appending Github performs for Github Project Pages, the configuration setup is necessary for the Hugo page to render correctly as a Github Project Page.

[PR 1223 created to solve issue](https://github.com/gohugoio/hugoDocs/pull/1223/files)

I found my way to this solution by [asking on the Hugo Discourse Board](https://discourse.gohugo.io/t/docsy-theme-not-rendering-using-github-pages/28109) - and am capturing the findings in the hugoDocs.

**Comment by jmooring** [comment]
Superseded by #1460
