### ISSUE TITLE
gcc is missing from requirements list ?

### ISSUE THREAD

**Issue by fvant** [gohugoio/hugoDocs#1227]
On page https://gohugo.io/getting-started/installing/ , these steps https://gohugo.io/getting-started/installing/#fetch-from-github fail on `go install --tags extended` with an error that `# github.com/bep/golibsass/internal/libsass
exec: "gcc": executable file not found in %PATH%`.

The requirements list in that section only mention Git and Go.

**Comment by ngdangtu-vn** [comment]
Can you tell me what OS you are using? Should I assume it is Windows? (Considering the `%PATH%` pattern, it may be a window) In that case, you must install `gcc` command in order to compile Hugo, because Windows doesn't have it out of the box. Here is a website with [recommended binaries](https://gcc.gnu.org/install/binaries.html). And remember to add the path contains `gcc` command to `%PATH%` so the go compiler could see it.

**Comment by ngdangtu-vn** [comment]
Hello, I've added a note for Windows' case: https://github.com/ngdangtu-vn/hugo-docs/commit/19a96fd906bd3eae345eb11ddb9f122fccb89bd7

Please checkout and lemme know if it is good for PR. @fvant @bep

**Comment by fvant** [comment]
gcc is only required when you use  `--tags extended`, a  `go install` works fine without. Should we recommend gcc for all Windows users ?

**Comment by davidsneighbour** [comment]
Little hair-splitting comment: Is gcc really missing or is it just not in the path?

**Comment by fvant** [comment]
I had not installed it; should be mentioned in requirements anyway imo

**Comment by ngdangtu-vn** [comment]
@davidsneighbour 
`gcc` is like `go`, they are compilers so we must install it manually. The msg error isn't sure if our pc has cpp compiler or not installed properly.

**Comment by ngdangtu-vn** [comment]
I've added few more text: https://github.com/ngdangtu-vn/hugo-docs/commit/507997706ec9e2c68316e0dece5fa49162256b89
I hope it could clear up the some misunderstanding. Please rechecked it again and tell me how you think @fvant @davidsneighbour 

So far, I still wonder should I add `MinGW` as recommendation. On my machine, it worked ok. But does that make the doc turns to commercial product?
