### ISSUE TITLE
Remove "Only leaf bundles can be made headless."

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugoDocs#1230]
This statement appears here:
<https://gohugo.io/content-management/page-bundles/#headless-bundle>

According to bep, this is no longer true. See:
<https://discourse.gohugo.io/t/getting-headless-to-be-headless/28359/3>

**Comment by davidsneighbour** [comment]
There was some kind of mini-stroke going on in my brain on #1233. Not sending PRs today anymore now ;)

**Comment by jmooring** [comment]
Fixed by https://github.com/gohugoio/hugoDocs/pull/1234
