### ISSUE TITLE
Documentation for safeJS function seems to be false

### ISSUE THREAD

**Issue by davidsneighbour** [gohugoio/hugoDocs#1232]
It states at the end:

```
Example: Given `hash = "619c16f"` defined in the front matter of your `.md` file:

* <span class="good">`<script>var form_{{ .Params.hash | safeJS }};…</script>` &rarr; `<script>var form_619c16f;…</script>`</span>
* <span class="bad">`<script>var form_{{ .Params.hash }};…</script>` &rarr; `<script>var form_"619c16f";…</script>`</span>
```

I assume the second sample should show various special characters encoded? Because if not then both lines produce the same result. The encoding probably disappeared somehow when somebody edited the file.

**Comment by jmooring** [comment]
> I assume the second sample should show various special characters encoded?

No, the only difference is between the two is the (undesirable) presence of quotation marks in the second example.

<img src="https://user-images.githubusercontent.com/335669/144883896-99c823eb-6d07-4e9e-a0de-a2df86a8af0f.png" width="40%" alt="">
