### ISSUE TITLE
Always add Hugo version number to title

### ISSUE THREAD

**Issue by davidsneighbour** [gohugoio/hugoDocs#1237]
The release notes on gohugo.io sometimes (often) include a version number (like "Hugo 0.75.1: A couple of Bug Fixes"). Sometimes they don't (like in https://gohugo.io/news/0.75.0-relnotes/). Is there a programmatical way to force @bep ;) to always include the version name in the title? 

I think this could be solved by a Github action that prepares the release news page automatically with links to changesets and pull requests. I don't have a full understanding of how these news are created to attempt this on my own.

This is a usability issue for people that try to find changes between specific versions.

**Comment by bep** [comment]
So, there is an auto-generated title which always includes the version number ... But for main releases I edit the title. And I don't think there is a way to ... force me to to do sensible things.

**Comment by coliff** [comment]
hey @bep - on the subject of the Release Notes, I noticed that the "thanks for the updates to the Documentation site" paragraph is always duplicated each time.

> And a big thanks to @digitalcraftsman for his relentless work on keeping the themes site in pristine condition and to @davidsneighbour, @coliff and @kaushalmodi for all the great work on the documentation site.
> 
> Many have also been busy writing and fixing the documentation in hugoDocs, which has received 24 contributions by 15 contributors. A special thanks to @jmooring, @bep, @jornane, and @inwardmovement for their work on the documentation site.

Maybe you can fix that for the next release. :-)

**Comment by kaushalmodi** [comment]
I agree. I haven't been an active contributor in recent months. My name should be removed from there.

**Comment by bep** [comment]
You could always _contribute_ by creating a PR that fixes that text.

**Comment by coliff** [comment]
Ok, opened a PR to fix that in the 0.75 release notes which I guess you copy and paste each time.

**Comment by jmooring** [comment]
Closing per https://github.com/gohugoio/hugoDocs/pull/1240#issuecomment-699849388, new issue is https://github.com/gohugoio/hugo/issues/8360.
