### ISSUE TITLE
The "new" command needs an example

### ISSUE THREAD

**Issue by BradyDale** [gohugoio/hugoDocs#1239]
https://github.com/gohugoio/hugoDocs/blob/master/content/en/commands/hugo_new.md

There needs to be an example on this page that **shows an example path**. Hugo is very fiddly about this. I never get it right and Hugo just concatenates everything and I have to go move it rename it in my File Manager. 

I can never remember if it's forward or back slash or whatever and if there's one at the front or not. So. An example would help here a great deal, in my humble opinion. 

I'd submit a fork myself but I can't get it right myself right now and haven't happened on the right format again yet.

**Comment by UtkarshVerma** [comment]
Using a backslash and forward slash is purely OS-dependent. On Windows you use backslash `\`m while on Linux you use forward slash `/` in paths. Also, using a leading slash is conventionally used to indicate that you're referring to the absolute path, rather than the relative.
My point is that, this isn't something related to Hugo, so I wouldn't think it's necessary to add something to docs for this.

**Comment by BradyDale** [comment]
It switches based on usage in Hugo and I didn't even know how to characterize the difference 
It is very frustrating as a user so while the issue may be further down in the stack ignoring it makes the UX much much worse

**Comment by davidsneighbour** [comment]
The sample could be added to the output of `hugo new --help`. At this point Hugo knows what OS it is on.

**Comment by jmooring** [comment]
On Windows, the following two commands produce _identical_ results:

```
hugo new post/foo.md
hugo new post\foo.md
```

I'm not sure what else needs to be done here.

The Quick Start section of the documentation provides two examples, one to [create a new site](https://gohugo.io/getting-started/quick-start/#step-2-create-a-new-site) and the other to [create new content](https://gohugo.io/getting-started/quick-start/#step-4-add-some-content).

https://gohugo.io/getting-started/quick-start

**Comment by BradyDale** [comment]
wait are both of those producing identical results new? Did something
change? I feel like I have done the above the wrong way and gotten a weird
concatenation

I think the problem I had was that on my site the newest posts are in their
own folder. This may have increased confusion.

So I would do, like

c:/mysite/post/new/foo.md
/mysite/post/new/foo.md
/post/new/foo.md

Took me a while to figure out that that first slash was no good

anyway an example would be cool on that page

>
