### ISSUE TITLE
add "baseURL" setting

### ISSUE THREAD

**Issue by shinji-kakimoto** [gohugoio/hugoDocs#124]
I tried to "Host on GitHub: Deployment via /docs Folder on Master Branch".
But I did not good well.
In my case I could not display the image because I forgot to add the baseURL setting.
Sure, it is written in the first section. But, it is easy to forget for beginners.

I suggest that we add baseURL setting.
How about this instructions?
```
"Host on GitHub: Deployment via /docs Folder on Master Branch"
1. Create a <YOUR-PROJECT> git repository on GitHub.
2. git clone <YOUR-PROJECT-URL> && cd <YOUR-PROJECT>
3. Make your website work locally (hugo server or hugo server -t <YOURTHEME>) and open your browser to http://localhost:1313.
4. Change baseURL in config.toml
5. Change publishDir in config.toml
6. run `hugo`
```

Thank you.

**Comment by jasonnerothin** [comment]
I'm not sure the behavior is well-defined, see here: https://discourse.gohugo.io/t/solved-what-should-be-used-for-the-value-of-site-baseurl/5896/3

I'm still investigating, but it may touch multiple doc sources...
