### ISSUE TITLE
My new gohugo.io site notable?

### ISSUE THREAD

**Issue by albertjmenkveld** [gohugoio/hugoDocs#1269]
Dear Hugo Professional:

I have re-created my site with gohugo.io (previous version was done in Jekyll).  I spent a lot of time searching for just the right template, but noticed I wanted more control.  So, in the end, I created my own site with the appropriate CSS.  For people who might have similar desires it might be good to know that such bare-bones site could be easily generated in gohugo.io.  I am happy to share my code as open source.  What do you think?  It is worth showcasing my site at gohugo.io?  If so, what are the next steps (please refer me to the right site with directions).  My site is: https://albertjmenkveld.com.

Thanks for all the GREAT work on gohugo.  I love it!  I have also featured it on my recommended software page.

Best, Albert

**Comment by bep** [comment]
It's a great looking Hugo website, but I don't think it passes the "notable threshold" for the featured websites section.

**Comment by albertjmenkveld** [comment]
Excellent. Understood. Thanks for letting me know!

Cheers, Albert

*Albert J. Menkveld*
*Vrije Universiteit Amsterdam (albertjmenkveld.com
<https://albertjmenkveld.com>)*

*Perhaps of interest (clickable):*
*• HFT literature survey
<https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2787542>*
*• Microstructure summer school 2021 <https://microstructure-course.com>*
*• 4nations cup 2021 <https://4nations.org>*
