### ISSUE TITLE
Improve "Host on GitHub" page

### ISSUE THREAD

**Issue by tgarlot** [gohugoio/hugoDocs#1275]
The setup explanation with the 2 GitHub repositories is not clear enough (I spent quite some time to make it work and have to search a lot).

I will propose an update to this page to detail more the "Step-by-step Instructions" for GitHub User page based on this "note" I created for myself:  https://tgarlot.github.io/posts/hugo-site-on-github/

PR to come shortly for review

**Comment by jmooring** [comment]
Superseded by #1460
