### ISSUE TITLE
Git version number on hosting-on-github page

### ISSUE THREAD

**Issue by aivarpaalberg** [gohugoio/hugoDocs#1293]
On page [https://gohugo.io/hosting-and-deployment/hosting-on-github/](https://gohugo.io/hosting-and-deployment/hosting-on-github/) under Assumptions is stated:

> You have Git 2.8 or greater [installed on your machine](https://git-scm.com/downloads).

However, link leads to the download page where the most recent version at the moment is 2.29. 

This is probably typo but it requires guessing to correct it to intended version number by others except author(s).

**Comment by coliff** [comment]
Good spot. I'm not sure what the correct minimum version of Git should be though.
@bep - any ideas?

**Comment by davidsneighbour** [comment]
Where is the issue here? 2.29 is greater than 2.8? Probably a required feature was introduced in 2.8.

**Comment by coliff** [comment]
ah yes, sorry. At a glance it's sometimes easy to mistake '2.8' as being a higher version number than '2.29'.

**Comment by aivarpaalberg** [comment]
Yes, @davidsneighbour and @coliff  you are absolutely correct and I didn't pay attention to version numbering of Git. My mistake.
