### ISSUE TITLE
Shortcode for github gist displays raw code

### ISSUE THREAD

**Issue by whoabuddy** [gohugoio/hugoDocs#1297]
On the Shortcodes page under [Example `gist` Display ](https://gohugo.io/content-management/shortcodes/#example-gist-display), the raw HTML for the shortcode is shown instead of the example.

![20201214_001_Selection](https://user-images.githubusercontent.com/9038904/102104639-a9c80900-3deb-11eb-8007-084e81d3a7f9.png)

**Comment by coliff** [comment]
It looks correct to me: https://gohugo.io/content-management/shortcodes/#example-gist-display

![image](https://user-images.githubusercontent.com/1212885/102155218-71ddc600-3ebe-11eb-8e80-8df4873fb1db.png)

Can you re-try? Maybe the GitHub Gist JavaScript wasn't loading when you tested.

**Comment by whoabuddy** [comment]
Yes, it's working for me now too, thanks for following up!
