### ISSUE TITLE
Versioning of docs

### ISSUE THREAD

**Issue by fridde** [gohugoio/hugoDocs#1305]
It would be helpful if the docs changed according to the version chosen in a drop down selector, with "newest" as the default.
[The Symfony project](https://symfony.com/doc/current/setup.html) does this and it works amazingly.

To be honest, in comparison to other projects the Hugo documentation looks unjustly "stale" as it's riddled with "current", "as of writing", "in future releases" and references to earlier releases. As a new user I am not inclined to learn about the history of Hugo, and sentences like "Note that before Hugo 0.76 force was the default behaviour, but this is inline with how Netlify does it" are purely distracting noise to anyone who joined Hugo recently.

These temporal comparisons are only relevant for a certain point in time and become quickly outdated and should usually be avoided. The current concept to mark every added feature with "new in version 0.80" doesn't help to keep the docs clean. 

This sounds a bit harsh, but it comes from a point of care.

**Comment by acanalis** [comment]
Agreed. I'd rather have that information presented with less emphasis. Notes and warnings interrupt the reading flow and in many times they are unnecessary. 

For example in https://gohugo.io/content-management/multilingual/ there are 4 notes, and one of them says: 
> From **Hugo 0.31** you no longer need to use a valid language code. It can be anything.
>
> See https://github.com/gohugoio/hugo/issues/3564

Hugo 0.31 was out [three years ago](https://gohugo.io/news/0.31-relnotes/) so the number of people to which that note is relevant is probably very low.

**Comment by jmooring** [comment]
Closing this for now...

1. We're not going to version the docs any time in the near future. This is, among other things, a resource issue.
2. We (meaning I) have made substantial progress in cleaning up many of the no-longer-necessary references to past behaviors.
3. The "New in vN.N.N" badges are now self-limiting. After 30 minor releases (something like 24-30 months) the badge will disappear, and a warning appears when building the site notifying editors (me) to remove the badge,

I am aware there are still outdated references to earlier releases, and I will get to them at some point. If you see something particularly egregious, please create a separate issue. Thanks.
