### ISSUE TITLE
Broken link in hugoDocs/content/about/benefits.md

### ISSUE THREAD

**Issue by aadeesh** [gohugoio/hugoDocs#131]
The link ["Static Site Generators”, O-Reilly](https://gohugo.io/documents/oreilly-static-site-generators.pdf) in hugoDocs/content/about/benefits.md is broken.

**Comment by digitalcraftsman** [comment]
Hello @aadeesh,

thanks for reporting this issue. Either the entire `documents` folder, in which the files are supposed to be, was been removed or it might happen when we merged the new version of the documentation.

/cc @rdwatters wasn't you who originally added this files? This problem affects all [links that point to files in the `documents` folder](https://github.com/gohugoio/hugoDocs/search?utf8=%E2%9C%93&q=documents&type=).

**Comment by rdwatters** [comment]
Thank you for pointing this out @aadeesh! I'll take care of it this weekend. BTW, if you're new to SSGs, that O'Reilly mini-paper is pretty fantastic, albeit a bit dated now a year and a half later.

**Comment by aadeesh** [comment]
Thanks @digitalcraftsman and @rdwatters for looking into this. Yes I'm new to SSGs so reading the Hugo Docs and others on the web. Great documentation though!

I tried looking for the O'Reilly paper on the web elsewhere with a hope it would have some philosophical working and benefits of the SSGs in general but couldn't find it. I'll check back in for your fix. Hope you could find it and fix the issue with `documents` folder in general. Thanks!

**Comment by jamesrhea** [comment]
Two options:

- [O'Reilly download page](http://www.oreilly.com/web-platform/free/static-site-generators.csp) 
- The PDF (attached): [static-site-generators.pdf](https://github.com/gohugoio/hugoDocs/files/1242701/static-site-generators.pdf)

**Comment by aadeesh** [comment]
Thanks @jamesrhea!

**Comment by jamesrhea** [comment]
@rdwatters - Should the PDF be uploaded somewhere? Should the link be changed to the O'Reilly page?
(There's no direct link via their site; you have to fill out a form first.) What's your preference?
