### ISSUE TITLE
'site' function Doc

### ISSUE THREAD

**Issue by andreseduardop** [gohugoio/hugoDocs#1324]
Can you include the 'site' function in the documentation?

**Comment by sebastiaan-lampo** [comment]
Would you mind giving a specific example of what you'd like to see documented? There is quite a lot of references to 'site' already documented including:

- `hugo new site` [command line function ](https://gohugo.io/commands/hugo_new_site/)
- `.Site` [variable](https://gohugo.io/variables/site/)

**Comment by andreseduardop** [comment]
Thanks @sebastiaan-lampo 
I mean the function that replaces '.Site'
As mentioned by @regisphilibert here:
https://discourse.gohugo.io/t/is-it-better-to-always-write-site-params-over-site-params-or-site-params/31085/3?u=andreseduardop
