### ISSUE TITLE
Github hosting guide has some renndering issue. 

### ISSUE THREAD

**Issue by Jack-alope** [gohugoio/hugoDocs#1327]
Inside https://gohugo.io/hosting-and-deployment/hosting-on-github/#build-hugo-with-github-action the link to the hugo github action setup is broken and the code blocks don't render properly. See pull request #1326.

**Comment by coliff** [comment]
Thanks for reporting this. Fixed now:
https://gohugo.io/hosting-and-deployment/hosting-on-github/
