### ISSUE TITLE
Update Site Variable page methods list with `site` function

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugoDocs#1333]
Following #1324 it seems sensible to me to stop referencing the `.Site` page object and only mention the `site` function when listing [Site Variables](http://localhost:1313/variables/site/#site-variables-list)

@bep to your knowledge Is there any reason/advantage for build speed or otherwise to keep directing users to use `.Site` instead of `site`. From the end user stand point, all I see is an easily avoidable context concern.

**Comment by genetikdisoda** [comment]
Cosign!
