### ISSUE TITLE
Add example for adding content and front matter to taxonomy pages to list templates explanation...

### ISSUE THREAD

**Issue by rdwatters** [gohugoio/hugoDocs#134]
Thanks to @guayom for pointing out our lack of examples for taxonomies in https://github.com/gohugoio/hugoDocs/pull/130.

I will add more information to the original section here:

http://gohugo.io/templates/lists/#add-content-and-front-matter-to-list-pages

**Comment by jmooring** [comment]
Resolved with https://github.com/gohugoio/hugoDocs/pull/130
