### ISSUE TITLE
Sponsor logos are blocked by Brave Shield (option "tracker & ads blocking")

### ISSUE THREAD

**Issue by divinerites** [gohugoio/hugoDocs#1348]
Sponsor logos from cloudfront.net are blocked by AdblockPlus (Chrome/Brave).
If I switch off ABP it works fine.

[EDIT] With Brave in private mode and without any addon, it is also blocked by basic privacy rules. Switching off those basic rules, makes logo load.

<img width="542" alt="Capture d’écran 2021-03-01 à 23 28 41" src="https://user-images.githubusercontent.com/32342823/109567657-03d09480-7ae6-11eb-9427-f1140808c84d.png">

**Comment by bep** [comment]
Hmm... I assume it is our GTM tracking.... I will check

**Comment by bep** [comment]
Quickly tested it with Brave private mode, and the logos shows up ...

**Comment by divinerites** [comment]
OK. Let me check then.

**Comment by divinerites** [comment]
OK. 
It seems that my "stock" Brave (without any extension) has the  "blocking tracking and advertising" option `on`.
This seems to be the cause.

<img width="983" alt="Capture d’écran 2021-03-02 à 10 49 31" src="https://user-images.githubusercontent.com/32342823/109630323-0f06dd00-7b45-11eb-94ea-ca3b7b87c533.png">
<img width="1669" alt="Capture d’écran 2021-03-02 à 10 46 26" src="https://user-images.githubusercontent.com/32342823/109630330-10d0a080-7b45-11eb-92cf-82b5ff928282.png">

**Comment by bep** [comment]
Hmm... In Brave, even if I turn it to Aggressive, it does not block the images. Hmm... I even installed AdblockerPlus, and even then those logos show.

What OS do you run?

**Comment by divinerites** [comment]
- Mac OSX 10.14.6.
- Brave 1.20.110

Switching this option on <-> off makes the image show <-> do not show.

I tried to remove all other possible effects (turned off VPN, turned off all extensions).
Strange. May be they created a special Brave version just for you the guy they sponsor so images show up 😁 .

**Comment by divinerites** [comment]
> even if I turn it to Aggressive, it does not block the images

I had this few times but it was related to browser cache not purged & reload.

**Comment by divinerites** [comment]
OK. The cause is `uBlock origin`.

For some reason it was operating even if it was off. 
Retesting carefully one by one brings the real guilty one.

So my bad it is not Brave or ABP, but `uBlock origin` plugin. Sorry for the disturbance.

**Comment by divinerites** [comment]
Well again sorry for the noise, but the cause is  **not** `uBlock origin`.

I switch off all extensions, quit brave and reload. Then it seems that it is really this option the cause.

<img width="682" alt="Capture d’écran 2021-03-02 à 11 27 22" src="https://user-images.githubusercontent.com/32342823/109635127-4f1c8e80-7b4a-11eb-992e-fae0a4424913.png">

**Comment by jmooring** [comment]
Unable to reproduce with a virgin installation of Brave Browser 96.1.32.113.
