### ISSUE TITLE
Note that tags are removed when processing images

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugoDocs#1354]
Image tags (EXIF, IPTC, XMP, etc.) are removed when an image is processed with the `.Resize`, `.Fit`, `.Fill`, or `.Filter` method. The original image (the resource) is untouched.

**Comment by bep** [comment]
Some would think of this as a feature {for privacy reasons -- this is how Facebook do it). However, I suggest that we create a "not shortcode" that we can post on the 2 relevant image proc pages saying something ala:

* None of the image processing operations preserve EXIF and similar metadata.
* If you want to access EXIF data (JPEG and TIFF only), you need to do that from the original (with a link to the EXIF section)
*

**Comment by jmooring** [comment]
Yes, I think of it as a feature, and have no interest in changing the current behavior.
