### ISSUE TITLE
front matter 'published' field not documented

### ISSUE THREAD

**Issue by jgreely** [gohugoio/hugoDocs#136]
`published=false` is equivalent to `draft=true`, but is not mentioned in the new docs. I stumbled across this while debugging something in the [forums](https://discourse.gohugo.io/t/hugo-chokes-on-125-000-pages/7921/13), where the user put dates in the `published` field that were being cast to boolean and ending up as false, preventing the pages from being rendered.

**Comment by rdwatters** [comment]
I want to say there was a Gitter conversation about this a while back and can't remember outcome. Need to defer to @bep as to whether this worth documenting...

**Comment by ronliskey** [comment]
I would like to throw my two beers in on the side of erring toward more documentation. If one person stumbles hard on an undocumented feature, probably more will. Why needlessly repeat the pain?

**Comment by bep** [comment]
It is marked as "Intentionally undocumented" in the code. Let us assume that whoever did that had good intentions.

**Comment by ronliskey** [comment]
Indeed. Good intentions are rightly assumed, and equally assumed to apply toward those who would document less as well as those who would document more. Assumptions of infallibility are less easily earned.

**Comment by bep** [comment]
I will add this:

* You people are not the main audience for the docs (you are specialists)
* Undocumented features are undocumented mainly because we want people to use some other "best practice"
* `published` is there I guess for compatibility reasons with Jekyll, and would make sense only in that context.
