### ISSUE TITLE
configuration-markup.md is missing `menu` front-matter variable

### ISSUE THREAD

**Issue by rootkea** [gohugoio/hugoDocs#1362]
https://raw.githubusercontent.com/gohugoio/hugoDocs/master/content/en/getting-started/configuration-markup.md doesn't have `menu` front-matter variable which is why that page ("Configure Markup") is inaccessible from navigation menu.

**Comment by jmooring** [comment]
Although configuration-markup.md exists within the content/en/getting-started/ directory, that doesn't mean it should have a menu entry. Logically it is a configuration subtopic, similar to "Configure Languages" and "Image Processing Config", neither of which have menu entries under "Getting Started."

**Comment by rootkea** [comment]
@jmooring 
> similar to "Configure Languages"

"Configure Languages" is a subtopic on ["Multilingual and i18n" page](https://gohugo.io/content-management/multilingual/#configure-languages) which has menu entry under "Content Management" chapter.

> and "Image Processing Config"

Similarly, "Image Processing Config" is a subtopic on ["Image Processing" page](https://gohugo.io/content-management/image-processing/#image-processing-config) which has menu entry under "Content Management" chapter.

The main problem here is if someone is trying to learn Hugo by going through the hugodocs nav menu then she will never see ["Configure Markup" page](https://gohugo.io/getting-started/configuration-markup) since it has no entry in chapter index (nav menu).

Currently, only way to reach that page is by know its exact URL or by clicking on "Configure Markup" link on https://gohugo.io/getting-started/configuration/ which is nested deep on that page and user might miss it.

Every hugo topic should either be a separate page or a subtopic on a page. And every hugo docs page should be accessible from nav menu.

**Comment by jmooring** [comment]
> only way to reach that page is by know its exact URL or by clicking 

Or by typing "Markup" or "Configure" in the search field. But I understand your point.

**Comment by rootkea** [comment]
> But I understand your point.

Thanks!

But since you haven't reopened this issue I assume you have decided to not let ["Configure Markup" page](https://gohugo.io/getting-started/configuration-markup) to have an entry in official hugo docs nav menu. i.e. to not let  ["Configure Markup" page](https://gohugo.io/getting-started/configuration-markup) be discoverable from hugo docs nav menu. :(

**Comment by jmooring** [comment]
Sure, it sure should potentially have a menu entry, but not here. The configuration options are spread throughout many sections of the documentation. Ultimately these should be organized under a configuration section, and each item would have a menu entry. But for now I'm leaving this alone.

**Comment by rootkea** [comment]
> The configuration options are spread throughout many sections of the documentation.

That's true. But the thing is all those documentation pages can be reached from left hand side navigation menu e.g. [0] except ["Configure Markup" page](https://gohugo.io/getting-started/configuration-markup).

Is there any other hugo documentation page besides "Configure Markup" page which doesn't have an entry in navigation menu?

I just don't understand why do we want Hugo documentation page to be left orphaned, why do we want a Hugo documentation page to be absent/hidden from table of contents (left hand side navigation menu).

Anyways, thanks for the reply though! :)

[0] https://github.com/gohugoio/hugoDocs/issues/1362#issuecomment-799847055
