### ISSUE TITLE
How to update `package.hugo.json`

### ISSUE THREAD

**Issue by robsonsobral** [gohugoio/hugoDocs#1366]
Hi!

Please, how to update the `package.hugo.json` after to install a new dependency? I considered updating the `https://gohugo.io/commands/hugo_mod_npm/`, but I couldn't find the right command to write there.

Is it `hugo mod npm what?`?

**Comment by jmooring** [comment]
This is the repository for Hugo documentation. Please post your question to <https://discourse.gohugo.io/>.

**Comment by robsonsobral** [comment]
Hi, @jmooring !

Please, let me try to explain myself better.

I know this is the repository for documentation. That's exactly my point. This info is missing from https://github.com/gohugoio/hugoDocs/edit/master/content/en/commands/hugo_mod_npm.md

**Comment by jmooring** [comment]
```
hugo mod npm --help

Various npm (Node package manager) helpers.

Usage:
  hugo mod npm [flags]
  hugo mod npm [command]

Available Commands:
  pack        Experimental: Prepares and writes a composite package.json file for your project.
```
