### ISSUE TITLE
improve Template Lookup Order presentation

### ISSUE THREAD

**Issue by whilei** [gohugoio/hugoDocs#1374]
Below is a screenshot of how Template Lookup Order is displayed, which I find very difficulty to read and use. 

Options for improvement might include
- using HTML lists (eg. `<ol><li>`) to show `Template Lookup Order` items
- presenting these items in a `tree` format
- at least separating items with commas...

![image](https://user-images.githubusercontent.com/10228550/111913395-ef741d80-8a3b-11eb-93df-d18558e5bbe9.png)
> https://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-regular-pages

**Comment by jmooring** [comment]
Changing the HTML to an ordered list (without any CSS changes) looks like this:

![image](https://user-images.githubusercontent.com/335669/112362373-99001c80-8c91-11eb-8b9d-e6060ee0ee59.png)

Comments?

**Comment by davidsneighbour** [comment]
The OCD in me would like to have those columns at the left top-aligned.

**Comment by coliff** [comment]
do some of the templates really end with `.html.html` or is that a bug?

**Comment by moorereason** [comment]
@coliff, it's real.  See https://github.com/gohugoio/hugo/pull/7840.

**Comment by davidsneighbour** [comment]
It's an html template for the html output format. If you (let's pretend there are reasons) have an html output format you could do another `.htm.html` template for that.
