### ISSUE TITLE
Incorrect meaning of .Next, .NextInSection, .Prev, .PrevInSection

### ISSUE THREAD

**Issue by J-Arun-Mani** [gohugoio/hugoDocs#1391]
Hello all.
In the [Page Variables](https://gohugo.io/variables/page/), the documentation for `.Next` is given as :

> .Next
> Points up to the next [regular page](/variables/site/#site-pages) (sorted by Hugo's [default sort](/templates/lists#default-weight-date-linktitle-filepath)). Example: `{{with .Next}}{{.Permalink}}{{end}}`. Calling `.Next` from the first page returns `nil`.

The last line says, calling `.Next` from the first page returns `nil`. But should not it be the exact opposite ? That is calling, `.Next` from the first page is valid and only calling it on the last page should return `nil`.

This contradiction is also found in similar functions :
 
> .NextInSection
> Points up to the next [regular page](/variables/site/#site-pages) below the same top level section (e.g. in `/blog`)). Pages are sorted by Hugo's [default sort](/templates/lists#default-weight-date-linktitle-filepath). Example: `{{with .NextInSection}}{{.Permalink}}{{end}}`. Calling `.NextInSection` from the **first** page returns `nil`.

> .Prev
> : Points down to the previous [regular page](/variables/site/#site-pages) (sorted by Hugo's [default sort](/templates/lists#default-weight-date-linktitle-filepath)). Example: `{{if .Prev}}{{.Prev.Permalink}}{{end}}`.  Calling `.Prev` from the last **last** returns `nil`.

> .PrevInSection
> : Points down to the previous [regular page](/variables/site/#site-pages) below the same top level section (e.g. `/blog`). Pages are sorted by Hugo's [default sort](/templates/lists#default-weight-date-linktitle-filepath). Example: `{{if .PrevInSection}}{{.PrevInSection.Permalink}}{{end}}`.  Calling `.PrevInSection` from the **last** page returns `nil`.

Thank you !

**Comment by J-Arun-Mani** [comment]
I tried the functions and found how they work.
`.Next` and `.NextInSection` points to the page to which the _current page_ is the next page. Similarly `.Prev` and `.PrevInSection` points to the page to which the _current page_ is the previous page.
If this is how it works, then the documentation sounds correct, except it can be worded clearly to avoid confusion.

For example, `.Prev` :
>Points down to the previous regular page (sorted by Hugo's default sort) to which the current page is previous. Example: `{{if >.Prev}}{{.Prev.Permalink}}{{end}}`. Calling `.Prev` from the last last returns `nil`.

But why did Hugo adopt the terms in a bit different manner ? :sweat_smile: 
In my host opinion, when someone reads `.Page.Prev`, their interpretation will be that _the page previous to the current page_.

**Comment by J-Arun-Mani** [comment]
> @J-Arun-Mani would this be clearer if I told you that these methods went in the opposite directions in an early version of Hugo and that we had long and similar discussion about why that was wrong -- then we did an elaborate and long fix by introducing temporary alternative methods and deprecate the old, then wait some Hugo versions and then switch the order of the old methods ...

Wow this sounds very interesting and I never knew.

I'm +1 for improving the documentation. I'm also not a native English speaker, but the best I could try is : 
> Points down to the previous regular page (sorted by Hugo's default sort) to which the current page is previous. Example: {{if .Prev}}{{.Prev.Permalink}}{{end}}. Calling .Prev from the last last returns nil.

If this format sounds fine, I can edit the docs and make a PR. 
Thanks your quick and sound reply :)

**Comment by J-Arun-Mani** [comment]
I have these pages (in the default sort order) : 
```
news3
news2
news1
```
Calling `.Next` in `news2` gives : `news3`
Calling `.Prev` in `news2` gives : `news1`.

Now this makes sense as `news3` came after `news2` and `news1` came before it.
So calling `.Prev` in `news1` is invalid as `news1` is the first post in that section. Similarly calling `.Next` in `news3` is invalid as it the last post in that section.

Wow ! So all the confusion was because of forgetting  the sort order :smile: .

**Comment by davidsneighbour** [comment]
It might make sense to introduce some form of alias that uses the newer/older terminology to prevent misunderstandings.

**Comment by J-Arun-Mani** [comment]
I don't think we need to modify the terminology. We need to define what the `last page` means in _Calling .Prev from the last page returns nil._. That is, whether last in chronological order or default sort order.

From my previous comment : Calling `.Prev` from the last page (in Hugo's default sort order) returns nil.
This sounds less confusing. But I'm open for reviews :smiley:

**Comment by jmooring** [comment]
First, "chronological order" is only relevant if the page weights are equal. As we keep pointing to [Hugo's default sort](https://gohugo.io/templates/lists/#default-weight--date--linktitle--filepath), it would probably help to remember what it actually is:

> Weight > Date > LinkTitle > FilePath

But that's incorrect. It's actually:

> Weight > Date.Reverse > LinkTitle > FilePath

So I would prefer to refer to "Hugo's default sort" instead of something else.

Second, each of the four related items on <https://gohugo.io/variables/page/> already includes the phrase "Hugo's default sort". Adding the phrase again to each description seems wordy.

I'm inclined to close this issue.

**Comment by J-Arun-Mani** [comment]
Looks like the confusion is cleared. I agree with @jmooring on how repetition of words is not a good idea. This issue can be closed. Thanks for Hugo !
