### ISSUE TITLE
Proposal: remove duplicate lookup order table

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugoDocs#1395]
On <https://gohugo.io/templates/lookup-order/> we have 5 tables describing the template lookup order, 418 items in total:

- [Examples: Layout Lookup for Regular Pages](https://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-regular-pages)
- [Examples: Layout Lookup for Home Page](https://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-home-page)
- [Examples: Layout Lookup for Section Pages](https://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-section-pages)
- [Examples: Layout Lookup for Taxonomy Pages](https://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-taxonomy-pages)
- [Examples: Layout Lookup for Term Pages](https://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-term-pages)

On <https://gohugo.io/templates/output-formats/> we have one massive table with the same 418 items:

- [Templates for Your Output Formats](https://gohugo.io/templates/output-formats/#templates-for-your-output-formats)

I would like to remove the table from <https://gohugo.io/templates/output-formats/>, and reference the tables on <https://gohugo.io/templates/lookup-order/>.

Thoughts?

**Comment by jmooring** [comment]
In the absence of negative feedback, I will proceed with this change.

**Comment by genetikdisoda** [comment]
The table on output formats page is truncated.
