### ISSUE TITLE
Document disableAliases setting

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#14]
See https://github.com/gohugoio/hugo/issues/3613

**Comment by bmackinney** [comment]
I think this can be closed. The setting is documented at https://gohugo.io/getting-started/configuration/#all-configuration-settings

**Comment by kenmorse** [comment]
It does seem like this was fixed in commit 8cba70e28c09e070f69dda1c56d6f4dcd883d99f as part of issue gohugoio/hugo#5722.
