### ISSUE TITLE
Description of robots.txt override is incorrect

### ISSUE THREAD

**Issue by bahamat** [gohugoio/hugoDocs#1404]
According to the documentation:

<https://github.com/gohugoio/hugoDocs/blob/b66567de20dafe690640f1d5c308371175164539/content/en/templates/robots.md#robotstxt-template-lookup-order>

> The lookup order for the robots.txt template is as follows:
> 
> * /layouts/robots.txt
> * /themes/<THEME>/layouts/robots.txt
> > If you do not want Hugo to create a default robots.txt or leverage the robots.txt template, you can hand code your own and place the file in static. Remember that everything in the static directory is copied over as-is when Hugo builds your site. 

But this is not happening:

```
> ls public
ls: public: No such file or directory
> cat static/robots.txt 
User-agent: *
Disallow:

Sitemap: /sitemap.xml
> cat themes/anubis/layouts/robots.txt 
User-agent: *
# robotstxt.org - if ENV production variable is false robots will be disallowed.
{{ if eq (getenv "HUGO_ENV") "production" | or (eq .Site.Params.env "production")  }}
  Disallow:
{{ else }}
  Disallow: /
{{ end }}
> hugo
Start building sites … 

                   | EN   
-------------------+------
  Pages            | 560  
  Paginator pages  |  64  
  Non-page files   |   0  
  Static files     | 126  
  Processed images |   0  
  Aliases          | 167  
  Sitemaps         |   1  
  Cleaned          |   0  

Total in 665 ms
> cat public/robots.txt 
User-agent: *
# robotstxt.org - if ENV production variable is false robots will be disallowed.

  Disallow: /
```

Hugo is copying the wrong robots.txt file.

### What version of Hugo are you using (`hugo version`)?

<pre>
> hugo version
hugo v0.81.0-59D15C97 darwin/amd64 BuildDate=2021-02-19T17:07:12Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

yes

**Comment by jmooring** [comment]
Notes:

1\) To generate a `robots.txt `file from a template, set `enableRobotsTXT = true` in the site configuration.

2\) The template lookup order is:

1. `/layouts/robots.txt`
2. `/themes//layouts/robots.txt`
3. [Internal](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/robots.txt)

3\) To create a static `robots.txt` file, set `enableRobotsTXT = false` in the site configuration and place a `robots.txt` file in the `static` directory.
