### ISSUE TITLE
Rework the PostProcess page

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugoDocs#1406]
<https://gohugo.io/hugo-pipes/postprocess/>

**Comment by davidsneighbour** [comment]
Notes about this:

- a link to https://purgecss.com/plugins/postcss.html seems appropriate
- two samples (see usage on the link above) seem required, there are many ways to configure postcss (I had to reconfigure everything so purgecss worked)
- I would move the notes about "what not to do" into the end of the page, having the first sample being something that works
- Some people say remove the tailwind references - I don't see them on that page, not sure, even if... it might be a good sample
- I think it makes sense to deeper explain what this does (waiting with executing minify/sass until after build) and also add some kind of "this is the order things get executed" graph
- remove fingerprint from sample code and add note box that explains that the hugo fingerprint will be wrong if added in a pipe (that is maybe a bug in my opinion, but I am not sure if it's at all possible to somehow work this out in Hugo coding).
- probably more. I am in the process of adding postprocessing to one of my sites and will add notes.
