### ISSUE TITLE
Update Hugo doc case: Templates for a specific file

### ISSUE THREAD

**Issue by ngdangtu-vn** [gohugoio/hugoDocs#1424]
[Surge](https://surge.sh/help/adding-a-200-page-for-client-side-routing) support `200.html` for various purposes. And I think it would be nice if Hugo could add this page too. It would be more convenient for me than create a dummy content and use `_default/single.html`. And that trick doesn't work well if I have a blog that need page content. Using `200.html` as static is also out of the question because my `200.html` needs data generated from Hugo.

(It would be even cooler if we could have custom Page Kind. But that seems expensive so I'll just request for 200.html)

**Comment by jmooring** [comment]
This appears to have been a support issue (better handled on the [forum](https://discourse.gohugo.io/) rather than a documentation issue.
