### ISSUE TITLE
Incomplete docs in `math-typesetting.md`

### ISSUE THREAD

**Issue by jph00** [gohugoio/hugoDocs#1425]
### What version of Hugo are you using (`hugo version`)?

<pre>
N/A
</pre>

### Does this issue reproduce with the latest release?

N/A

### Details

In [math-typesetting.md](https://github.com/gohugoio/hugoBasicExample/blob/master/content/post/math-typesetting.md) it claims that "mathematical notation in a Hugo project can be enabled by using third party JavaScript libraries", and then goes on to show how to add those libraries.

However, this is not enough to use math notation. Looking at the [underlying markdown](https://raw.githubusercontent.com/gohugoio/hugoBasicExample/master/content/post/math-typesetting.md), it is also necessary to use `{{< math.inline >}}` and `<p>` tags for inline math (at least, that's what's used in the above file - in my testing the `<p>` tag isn't actually needed). Furthermore, a `math.inline` shortcode needs to be created that returns `.Inner`.

I believe that this should be mentioned in the  `math-typesetting.md` example file and/or Hugo docs, or alternatively the goldmark-mathjax extension (which does not use cgo AFAICT) should be added to hugo, which would then make this workaround unnecessary.

**Comment by jmooring** [comment]
The Math Typesetting page is in the [gohugoio/hugoBasicExample](https://github.com/gohugoio/hugoBasicExample) repository, _which is no longer used_. That repository provided default content for themes added to [gohugoio/hugoThemes](https://github.com/gohugoio/hugoThemes), _which is no longer used_.

Theme authors create a repository for each site, and are responsible for providing sample content. They submit their site to [gohugoio/hugoThemesSiteBuilder](https://github.com/gohugoio/hugoThemesSiteBuilder) for inclusion on <https://themes.gohugo.io/>.

If a theme provides math typesetting abilities, or other functionality using third party JS libraries, the theme author needs to provide documentation corresponding to _their_ implementation of those libraries.
