### ISSUE TITLE
Language Problem (solved)

### ISSUE THREAD

**Issue by vsatmydynipnet** [gohugoio/hugoDocs#1433]
hugo 0.80

Docu says languages with l but it must be L . For me only working that way:

[Languages]

  [Languages.de]
    languageName = "De"
    languageCode = "de-de"
    contentDir = "content/german"
    weight = 1
    title = "my title"
    # copyright
    copyright = "my (c)"
    
    [Languages.de.menu]
      [[Languages.de.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 70

**Comment by jmooring** [comment]
The documentation is correct.

Please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
