### ISSUE TITLE
Rework the multilingual page

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugoDocs#1448]
<https://gohugo.io/content-management/multilingual/#missing-translations>

> If a string does not have a translation for the current language, Hugo will use the value from the default language.

No, it will not. For example, if french is the default language, and a translation is defined in fr.toml but not in en.toml, then nothing will be shown on the english page. However, if french is the default language, and a translation is defined in en.toml but not in fr.toml, the english translation will be shown on the french page.

> If no default value is set, an empty string will be shown.

I'm not sure how one would set a default value, and empty strings are, by definition, never shown.

**Comment by LHSnow** [comment]
Also, if the language is `'en'` in the hugo config, a translation file named `en_US.toml` in `/i18n/` does not get considered. A file named `en` does, however, so the only example that is correct regarding file naming in the docs is fr.toml. It does not seem to matter if the language is instead named `en_US` in the config, either.

**Comment by jmooring** [comment]
Closing in favor of https://github.com/gohugoio/hugoDocs/issues/2099.
