### ISSUE TITLE
Document --config flag (support for multiple config files)

### ISSUE THREAD

**Issue by digitalcraftsman** [gohugoio/hugoDocs#146]
The `--config` flag allows users to specify multiple config files via the CLI.

See https://github.com/gohugoio/hugo/pull/3532

**Comment by XhmikosR** [comment]
I was just looking for this, but thankfully Google pointed me to the issue and then to the PR and then here :)

**Comment by regisphilibert** [comment]
Hi! I’m willing to add this to the doc. I may come back with questions here. 

Thanks.

**Comment by regisphilibert** [comment]
Sorry about that. GitHub thinks CLOSE and COMMENT buttons should be on the same level...
I will fork and do a proper PR as I suppose the use of next branch was for emergency edit like Page Resources.

**Comment by kaushalmodi** [comment]
@regisphilibert While working on this spring cleaning commit https://github.com/gohugoio/hugoDocs/commit/c87c9c62e177a100d64cebb0f43c707fbffdf27d, I thought of taking care of this by adding few lines.

**Comment by kaushalmodi** [comment]
@regisphilibert Oops, just found this PR of yours, part of which took care of this: https://github.com/gohugoio/hugoDocs/pull/323/files#diff-f187629d6a90eae0945fddfe86ae3f90.

**Comment by regisphilibert** [comment]
Sure this is how I worded it this pending PR https://github.com/gohugoio/hugo/pull/4370: 

> config file(s), multiple files (a.toml,b.toml.c.toml) will be merged (default is path/config.yaml|json|toml)

**Comment by regisphilibert** [comment]
> @regisphilibert Oops, just found this PR of yours, part of which took care of this

Actually I moved the string directly into a PR on https://github.com/gohugoio/hugo because the part I edited in the doc was generated by Hugo.

**Comment by kaushalmodi** [comment]
OK, cool. I believe that we are good then. The `content/commands/hugo.md` will auto-update when that PR is merged. I modified only the manually maintained `configuration.md`.
