### ISSUE TITLE
TOML is rendered differently in code-toggle with v0.87.0

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugoDocs#1505]
Example:
<https://gohugo.io/hugo-modules/configuration/#module-config-mounts>

v0.86.1

<img alt="v0.86.1" src="https://user-images.githubusercontent.com/335669/128048009-8b686829-f614-4545-8cd2-08feb8d24049.png" width="285">

v0.87.0

<img alt="v0.87.0" src="https://user-images.githubusercontent.com/335669/128048334-8c409384-8048-4752-ba78-e7119d896f07.png" width="272">

I suspect this is due to the changes in the TOML library.

**Comment by jmooring** [comment]
IMO this is not a bug, it is just different than it was before. The `transform.Remarshal` function now encapsulates strings with single quotation marks by default, using double quotation marks only when needed.

This:

```
{{ $map := dict "test" (
  slice
    (dict "a" "foo\n" "b" 1)
    (dict "a" "bar" "b" 2)
  )
}}
<pre>{{ transform.Remarshal "toml" $map | safeHTML }}</pre>
```

Renders as:

```text
[[test]]
a = "foo\n"
b = 1
[[test]]
a = 'bar'
b = 2
```

Whether or not the lack of indentation and blank lines is a good thing is debatable, but there is nothing inherently wrong with the current behavior.

**Comment by bep** [comment]
What is the action you ask for in this issue?

**Comment by bep** [comment]
I will add indentation in https://github.com/gohugoio/hugo/issues/8850 -- the other remarks are improvements, in my head (or: they are in line with the TOML 1.0 spec where only 2 quotes are mentioned: single and triple; `go-toml` does support double quotes as well, which is good, at many sites would have blown up if now...).

**Comment by jmooring** [comment]
I am primarily concerned about possible confusion and inconsistent documentation:
- "Why do some examples use single quotes, while others use double quotes?"
- "When I convert YAML/JSON to TOML using online tools, the result has double quotes, not  single quotes. Why?"
- "Should I be using single quotes with YAML and JSON too?"
- "All of the examples on Discourse have double quotes, but..." 
- "Should I be using single quotes in my frontmatter too?"
- "Do I need to convert all my existing TOML from double to single quotes?"

But I'm paranoid.

**Comment by bep** [comment]
@jmooring I know what you're talking about, but all of this is a balance game: We replaced a buggy, non-spec-compliant and unmaintained TOML library with a faster, TOML 1.0-compliant and well maintained library. On the net side of everything, this is a win.

**Comment by jmooring** [comment]
I completely agree.
