### ISSUE TITLE
Unfinished content on production server

### ISSUE THREAD

**Issue by slashformotion** [gohugoio/hugoDocs#1507]
At this url : https://gohugo.io/categories/functions

![image](https://user-images.githubusercontent.com/45801817/128414895-fad02cb8-7bea-408e-b720-2c9b766c4bfd.png)

I suppose this is the file to change https://github.com/gohugoio/hugoDocs/blob/master/content/en/functions/lang.md

**Comment by bep** [comment]
Thanks
