### ISSUE TITLE
We need a list of commands for themes

### ISSUE THREAD

**Issue by ORESoftware** [gohugoio/hugoDocs#1531]
A table like this:

| Theme Name  | Shell Command |
| ------------- | ------------- |
| Nuo "nuo"  | `git submodule add https://github.com/laozhu/hugo-nuo themes/nuo`  |
| Ananke "ananke"  | `git submodule add https://github.com/ranke-danke/hugo-ananke themes/ananke` |
| Foobar "foobar"  | `git submodule add https://github.com/foobar/hugo-foobar themes/foobar`  |

it is really hard/painstaking to find the commands to add a new theme to a repo (as a newb, at least).

**Comment by jmooring** [comment]
The documentation for each theme should include detailed installation instructions. In some cases that may be a Git submodule, in others a Hugo Module, and yet in others, both.
