### ISSUE TITLE
Functions Quick Reference is truncated

### ISSUE THREAD

**Issue by PaulSD** [gohugoio/hugoDocs#1547]
https://gohugo.io/functions/ contains an incomplete list of functions.  It stops at `safeCSS`, and is missing `safeHTML` and everything after it.

On a large display, clicking "Functions" on the left expands a complete list of functions.  However, on a small display (eg. mobile), clicking "Functions" takes you to the Quick Reference, and it appears to be impossible to see the complete list of functions.

**Comment by thewheat** [comment]
This looks to be an issue with the theme itself. I've tried fixing it here https://github.com/gohugoio/gohugoioTheme/pull/240

**Comment by calalloo** [comment]
Any progress on this issue?
