### ISSUE TITLE
Snapcraft hugo does not work with quickstart instructions

### ISSUE THREAD

**Issue by mikedlr** [gohugoio/hugoDocs#1549]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.88.1 linux/amd64 BuildDate=2021-09-04T13:52:29Z
</pre>

### Does this issue reproduce with the latest release?

this is the latest release

### Reproducer 

1) sudo snap install hugo
2) follow https://gohugo.io/getting-started/quick-start/ exacty, running all commands as listed up till running hugo server
3) run `hugo server -D`

### Actual Result

```
Start building sites … 
hugo v0.88.1 linux/amd64 BuildDate=2021-09-04T13:52:29Z
Error: Error building site: TOCSS: failed to transform "ananke/css/main.css" (text/css). Check your Hugo installation; you need the extended version to build SCSS/SASS.
Total in 51 ms
```

### Expected Result

I'd expect running the quick start instructions to reliably get me to the stage of having a working web site with any reasonable up to date hugo setup.  Either the quick start instructions shouldn't use the extended version of hugo or hugo extended should be the default installation configuration almost everywhere.

**Comment by thewheat** [comment]
Created https://github.com/gohugoio/hugoDocs/pull/1828 to try address this

**Comment by jmooring** [comment]
This was actually fixed by @anthonyfok a while ago. When you install the snap, you get the extended version now.

**Comment by decapo01** [comment]
To anyone that comes across this, for me simply updating the snap package did not install the extended version.  I had to remove the hugo package then install it again to get the extended version.

**Comment by mikedlr** [comment]
Tested and confirmed that this works for me now following the original instructions - thanks to everyone. One comment that the snap doesn't work if you try to run it in a directory in /tmp for testing, but I think that's the way snaps are confined and nothing else.
