### ISSUE TITLE
Explain that you cannot create content pages under taxonomy directories

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugoDocs#1578]
If you have a taxonomy named "tags" you must not do this:

```
hugo new content/tags/foo.md
```

The only files you should create under a taxonomy directory are section pages to contain taxonomy or term metadata. For example:

```
content/tags/
├── foo/
│   └── _index.md
└── _index.md
```

Not quite sure where to put this in the docs.

Reference: <https://github.com/gohugoio/hugo/issues/7975>

**Comment by davidsneighbour** [comment]
Can you add that `hugo new content/tags/foo` is allowed if there is an archetype `foo/_index.md` with frontmatter? I am pretty sure that I have that somewhere in use, but can't find it right now.

**Comment by jmooring** [comment]
This will be addressed in https://github.com/gohugoio/hugoDocs/issues/2307
