### ISSUE TITLE
go get: installing executables with 'go get' in module mode is deprecated.

### ISSUE THREAD

**Issue by santosh** [gohugoio/hugoDocs#1591]
This ticket is regarding the discussion for outdated method of installing mage.

When inside the hugo repo, issuing `go get github.com/magefile/mage` throws this.

```
$ go get github.com/magefile/mage
go: downloading github.com/magefile/mage v1.11.0
go get: installing executables with 'go get' in module mode is deprecated.
        To adjust and download dependencies of the current module, use 'go get -d'.
        To install using requirements of the current module, use 'go install'.
        To install ignoring the current module, use 'go install' with a version,
        like 'go install example.com/cmd@latest'.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

@bep, if you want, I can submit a PR for the same.

**Comment by bep** [comment]
Please do.

**Comment by santosh** [comment]
I am actually confused where this change would go. 

I can see `/docs/content/en/contribute/development.md` in both main `hugo` repos as well as `hugoDocs`.

Are they kept in sync? Please shed some light on this.

**Comment by bep** [comment]
>Are they kept in sync? Please shed some light on this.

Changes to in /docs in the `hugo` repo should only contain doc changes that is tightly coupled with code updates (new features).

So, the mage change belongs here (in the main docs repo).
