### ISSUE TITLE
Clarify the definition of menus via site configuration

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugoDocs#1594]
Reference: <https://github.com/gohugoio/hugo/issues/9150#issuecomment-965798975>

Changes required on:
- <https://gohugo.io/content-management/menus/>
- <https://gohugo.io/templates/menu-templates/>
- <https://gohugo.io/variables/menus/>

We need to make it clear through descriptions and examples that `pageref` should be used to link to pages, while `url` should be used for external links.

Reference:
<https://discourse.gohugo.io/t/42770/4>

**Comment by genetikdisoda** [comment]
Genius! Funny how such a critical idea is hidden in issues. Moreover, clarify active classes (`.IsMenuCurrent` etal) rely on file directory path, not permalink/URL. Learned this the hard waty.
