### ISSUE TITLE
Reorg the get/create Resource pages

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#1599]
I tested the search now checking if I could find the "get remote resource" documentation:

![image](https://user-images.githubusercontent.com/394382/145237099-fb20b701-e3b1-4ff2-964c-b9ba2d6011ca.png)

And that's not great.

We can certainly also tweak the Algolia setup (wherever that is ...), but I suggest we do a reorg of this into fewer entities, e.g.:

```
# Get or Create a Resource

## Get Local Resource

## Get Remote Resource

## Create Resource from String

## Create Resource from Template

Etc...
....

This is a core Hugo concept that needs a more clear placement/disposition.


/cc @jmooring

**Comment by jmooring** [comment]
@bep I was planning to attack this once https://github.com/gohugoio/hugo/pull/9063 was implemented. Having identical calls regardless of resource type would make it a bit easier to explain, but it is certainly not a show stopper.

**Comment by bep** [comment]
Ah, OK, I had a PR for that, but I ... forgot it for some odd reason.

**Comment by jmooring** [comment]
This will be addressed in https://github.com/gohugoio/hugoDocs/issues/2307
