### ISSUE TITLE
Missing info on deploying to Azure

### ISSUE THREAD

**Issue by kilasuit** [gohugoio/hugoDocs#1611]
The [Hosting and Deployment page](https://gohugo.io/hosting-and-deployment/) is missing a link to a guide on how to deploy to Azure

This should ideally contain either full guides to both of the following or links to guides hosted on other platforms like [Microsoft Docs](https://docs.microsoft.com)

- Deployment to Azure Static Sites hosted on Azure Storage
- Deployment to Azure Static Websites

**Comment by bep** [comment]
There is some info here: https://gohugo.io/hosting-and-deployment/hugo-deploy/

**Comment by bep** [comment]
We have `hugo deploy` with Azure support, which is documented:

<img width="557" alt="image" src="https://user-images.githubusercontent.com/394382/172229690-d710d182-c610-44d3-9012-0e325fb25d1e.png">

@chrisreddington thanks, but we need to (and this is progress) rethink this section before adding new guides.
