### ISSUE TITLE
Add information on deploying to Cloudflare Pages

### ISSUE THREAD

**Issue by afrophi** [gohugoio/hugoDocs#1616]
The [Hosting and Deployment page](https://gohugo.io/hosting-and-deployment/) could use a guide on how to deploy to Cloudflare Pages.

**Comment by jmooring** [comment]
With limited exceptions, deployment documentation should be provided by the service provider. Cloudflare has already done this:

https://developers.cloudflare.com/pages/framework-guides/deploy-a-hugo-site
