### ISSUE TITLE
Reorg the Quick Start Page

### ISSUE THREAD

**Issue by Linux-Geezer** [gohugoio/hugoDocs#1617]
I'm new to Hugo and I attempted to make a practice run by following the Quick Start page. I think the page should be reorganized as follows:

Step 1: Install Hugo
Step 2: Create a New Site
Step 3: Add a Theme
Step 4: Customize the Theme
Step 5: Add Some Content
Step 6: Start the Hugo Server
Step 7: Build Static Pages

Justification for my recommendation:  The site displays nothing until you add the _theme = 'theme name'_ line in the _config.toml_ file.

**Comment by carerragt** [comment]
You need to see what you are customizing. Plus customization is a continuous process. So, having the server running when doing customization is the correct way.

**Comment by jmooring** [comment]
> The site displays nothing until you add the theme = 'theme name' line in the config.toml file.

That is already part of [Step 3](https://gohugo.io/getting-started/quick-start/#step-3-add-a-theme), and is not related to customizing a theme.
