### ISSUE TITLE
Suggestion for the Quick Start Page

### ISSUE THREAD

**Issue by Linux-Geezer** [gohugoio/hugoDocs#1618]
It took me awhile to figure out how to run the example site that comes with installed themes. It might be helpful to new users to document the steps to run the example site. Draft suggestion:

1. Switch to _projectfolder/themes/themename/exampleSite_
2. Run _hugo server --themeDir ../.._

I got the information from the Airspace Hugo theme page: https://themes.gohugo.io/themes/airspace-hugo/

**Comment by jmooring** [comment]
Each theme should provide documentation for building its sample site, if it even has one.
