### ISSUE TITLE
Document additional File variables

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugoDocs#1623]
The following are not listed on <https://gohugo.io/variables/files/>:

```text
.File.Filename
.File.FileInfo
.File.IsZero
.File.Section
```

Ref: <https://github.com/gohugoio/hugo/blob/master/source/fileInfo.go>

**Comment by bep** [comment]
We need to hold off on this change. Most/all of this is considered internal API and not documented by purpose (especially the FileInfo.Meta struct; it is used internally in Hugo and will certainly change without notice.)
