### ISSUE TITLE
Please document .GetTerms

### ISSUE THREAD

**Issue by okaestne** [gohugoio/hugoDocs#1639]
`.GetTerms` is not listed in the page variables, only in an example snippet on the Taxonomy Templates doc page.

Can you please document it?

**Comment by jmooring** [comment]
Yes, we will do this, but where we do it is another question.

1. We currently list several page methods (e.g., `.GetPage`, `.RenderString`) in the functions section, which to me seems wrong. 
2. The list of page variables is really just a list of page methods. But they are immutable, not variable, and this has occasionally caused confusion. Perhaps we were concerned that "method" was too technical.

So it seems like page methods that _return_ a thing are "page variables," and page methods that _do_ a thing are "functions." Sort of.

If I were starting from scratch I would do it differently.
