### ISSUE TITLE
Rework the showcase section

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#1642]
See https://discourse.gohugo.io/t/cool-sites-that-run-hugo/36815/22?u=bep

The current approach where we invite site owners to "write a little story about their Hugo experience" doesn't scale well.

So I suggest we keep the layout as it is now, but make the process more lenient.

I suggest that we  make it a dugnad and pick, lets say, 10 sites from https://discourse.gohugo.io/t/cool-sites-that-run-hugo/36815/21 -- and when we have agreed on that list in this thread, we can split it between us and:

1. Do a `hugo new content/en/showcase/cool-site`
1. Create a screenshot
1. Write a short neutral about description about the site/company.
1. Also, we should spread these out, so add a `publishDate` some time in the future.

**Comment by jmooring** [comment]
This section was removed with https://github.com/gohugoio/hugoDocs/commit/392afc8f93a7135d3604ef9e88a4932db1ceabd1.
