### ISSUE TITLE
Incomplete example: Counting Pages with where 

### ISSUE THREAD

**Issue by chineyk** [gohugoio/hugoDocs#1646]
This example of [Counting Pages with where](https://gohugo.io/functions/len/#len-example-2-counting-pages-with-where) seems incomplete. Shouldn't it be as follows?
```
{{ $posts := (where .Site.RegularPages "Section" "==" "posts") }}
{{ $postCount := len $posts }}
{{ $postCount }}
```

**Comment by davidsneighbour** [comment]
"figure out" means "to retrieve". What you do after that is left to your requirements. Your addition just echoes the post count and if one would want that one would rather remove the `$postCount := ` part of line 2.

**Comment by chineyk** [comment]
> "figure out" means "to retrieve".

For someone like me who is multilingual, with English being like a fourth language, this is not well articulated. I copy-pasted the code in the docs and got no result, with my expectation being that the count will show up but nothing showed up! So, this is not a trivial thing and it does not hurt to document it!
