### ISSUE TITLE
Setting up tempate formatting with prettier-plugin-go-template in VS Code

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#1656]
This had me head scratching, so we should consider adding it to the docs. Some notes from me.

* Installing this globally (e.g. `npm i -g prettier-plugin-go-template`) did not work for me (I tried lots of stuff, including checking the `Resolve Global Modules` config).
* So, I initially thought then that I would have to add a `package.json` with that dependency to every Hugo repo I had, which would be super annoying.
* But then I remember that Node's depdendency resolution walks up the file system.

So, the setup I now have and is pretty happy with is:

In `/Users/bep/dev`, which is basically a root for all my development stuff, I:

* Run `npm init` and just create a "fake NPM package"
* Run `npm i prettier-plugin-go-template --save-dev`
* Add a `.prettierrc` with the following content:

```json
{
  overrides: [
    {
      files: ["*.html"],
      options: {
        parser: "go-template",
      },
    },
  ],
   "goTemplateBracketSpacing": true
}
```

You also need to install the extension for VS Code: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

**Comment by coliff** [comment]
I think it'd be worth committing a `.vscode/extensions.json` file to the project with the following:

```
{
  "recommendations": [
    "EditorConfig.EditorConfig",
    "esbenp.prettier-vscode",
  ]
}

```
To help ensure consistent code formatting for everyone working on the repo (who are using VS Code). What do you think? Happy to open a PR...

**Comment by bep** [comment]
@coliff yea, create a PR for that -- but my writeup above was mostly targeted at the common Hugo user editing their own site, not just this site...

**Comment by NiklasPor** [comment]
If you need any help here, I'd also be happy to assist 👏

**Comment by bep** [comment]
@NiklasPor I have managed to set this up now, and have written about it elsewhere. Your last version of this plugin is rock solid, and your work on this is very much appreciated.

**Comment by ngdangtu-vn** [comment]
Does this still work for you guys? I put the config to `package.json` but I always get this problem:

```
["INFO" - 12:48:57 PM] Formatting file:///hugo_base_path/themes/hugo-theme/layouts/home.html
["INFO" - 12:48:57 PM] Using config file at '/hugo_base_path/package.json'
["INFO" - 12:48:57 PM] PrettierInstance:
{
  "modulePath": "/hugo_base_path/node_modules/prettier/index.cjs",
  "importResolver": {},
  "callMethodResolvers": {},
  "currentCallMethodId": 18,
  "version": "3.0.0"
}
["INFO" - 12:48:57 PM] Using ignore file (if present) at /hugo_base_path/.prettierignore
["INFO" - 12:48:57 PM] File Info:
{
  "ignored": false,
  "inferredParser": "go-template"
}
["INFO" - 12:48:57 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 12:48:57 PM] Prettier Options:
{
  "filepath": "/hugo_base_path/themes/hugo-theme/layouts/home.html",
  "parser": "go-template"
}
["ERROR" - 12:48:57 PM] Error formatting document.
["ERROR" - 12:48:57 PM] Couldn't resolve parser "go-template".
ConfigError: Couldn't resolve parser "go-template".
    at getParserPluginByParserName (file:///hugo_base_path/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:16912:9)
    at normalizeFormatOptions (file:///hugo_base_path/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:16983:24)
    at formatWithCursor (file:///hugo_base_path/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:18588:52)
    at file:///hugo_base_path/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:21784:12
    at async Module.format2 (file:///hugo_base_path/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:21789:25)
["INFO" - 12:48:57 PM] Formatting completed in 13ms.
```

Here is my config:

```JSON
{
	"devDependencies": {
		"prettier": "^3.0.0",
		"prettier-plugin-go-template": "^0.0.13"
	},
	"prettier": {
		"overrides": [
			{
				"files": ["*.html"],
				"options": {
					"parser": "go-template"
				}
			}
		]
	}
}
```

**Comment by NiklasPor** [comment]
Prettier 3.0 support isn't implemented yet. I guess that might be the issue.

**Comment by ngdangtu-vn** [comment]
What is your recommend version for prettier?

**Comment by h2kyaw** [comment]
no one mention about plugin. Here I fiexed according search result, I shared my solution.

```
{
  "plugins": ["prettier-plugin-go-template"],
  "overrides": [
    {
      "files": ["*.html", "*.css"],
      "options": {
        "parser": "go-template",
        "singleQuote": false
      }
    }
  ],
  "singleQuote": true
}
```

added **"plugins": ["prettier-plugin-go-template"],** and problem fixed.
