### ISSUE TITLE
Data Templates - Specs for Data Formats - "JSON Spec" link is broken (404)

### ISSUE THREAD

**Issue by magikstm** [gohugoio/hugoDocs#166]
Page: https://gohugo.io/templates/data-templates/#specs-for-data-formats

Current link: https://gohugo.io/documents/ecma-404-json-spec.pdf

I'm unsure, but I think link should be corrected to this one or directed to that PDF: https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf

**Comment by xjlim** [comment]
+1
All the internal pdf links - 'JSON spec' and '“Static Site Generators”, O-Reilly' are currently broken. 

A [quick search](https://github.com/gohugoio/hugoDocs/search?utf8=%E2%9C%93&q=pdf&type=) to bring up pages with these links.
