### ISSUE TITLE
generating URLs when blanks or capital letters in path

### ISSUE THREAD

**Issue by raum51** [gohugoio/hugoDocs#1664]
Hi,
I know that using blanks, capital and small letters or special characters isn't the best way for file and folder names. (And I wouldn't do it, if I start a new project.) But I have to continue work on a existing projects with blanks and capital letters in file and folder names.

I recognized that Hugo urlize nicely the URL to the page, but not to additional files surrounding a page!

For reproduction I've followed the quick start instruction https://gohugo.io/getting-started/quick-start/ and made a complete new hugo site. You can find the generated public files here: https://github.com/raum51/hugo-quickstart/tree/main/public/posts and compare it with the structure of the content files here: https://github.com/raum51/hugo-quickstart/tree/main/content/posts

Is there any given rule for file and folder naming in Hugo?
Is this - I would say bug - already known?

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
