### ISSUE TITLE
Question: No official docker image

### ISSUE THREAD

**Issue by jtemporal** [gohugoio/hugoDocs#1669]
Hello Hugo team! I was trying to run a Hugo Docker image, but upon searching docker hub, I found [this user named gohugoio](https://hub.docker.com/u/gohugoio) that has a Hugo image. Is that an official docker image?

I ask this [because the documentation states](https://gohugo.io/getting-started/installing/#docker):

> We currently do not offer official Hugo images for Docker, but we do recommend these up to date distributions: https://hub.docker.com/r/klakegg/hugo/

thanks in advance for the guidance

**Comment by bep** [comment]
The documentation is correct.
