### ISSUE TITLE
About "The world’s fastest framework for building websites."

### ISSUE THREAD

**Issue by Moxinilian** [gohugoio/hugoDocs#1681]
Re-opening of gohugoio/hugo#7050 as it has not been resolved and was instead required to be moved here.

> Can you share some data about this claim?
> I could not find anything in the documentation/blog. How does it compare to other static site generators?
> 
> This claim is written either in the project title or in bold on your website so I guess you made a solid assessment at some point?
> 
> I could only find [here](https://spf13.com/project/hugo/).
> `A typical website of moderate size can be rendered in a fraction of a second. A good rule of thumb is that Hugo takes around 1 millisecond for each piece of content. It’s so fast that it will render the site in less time than it takes to switch to your browser and reload.`
> 
> I've just tried zola, a rust static site generator. It could handle 10000 (empty) documents in 800ms. So it's more than 10 times faster than hugo?

To add to it, I have seen many instances of Hugo being beaten in performance by other static site generators, and such in very reasonable situations. The claim of Hugo being the fastest is made everywhere in Hugo documentation, yet it seems to be objectively false. Maybe it could be wise to change it to avoid being misleading.

Alternatively, documenting data backing up the claim would be good. But in my opinion, this sort of claim is just bizarre in this context because it's never going to be quite true. It makes the project sound either unprofessional or misleading, which it clearly is not otherwise.

**Comment by mgenge254** [comment]
I have noticed that sometimes, my simple site with about 300 articles takes about 7-8 seconds on the first build locally. The reload is faster after that. But local builds don't bother me like online builds (Netlify, Cloudflare Pages, etc) where Hugo shaves a lot of seconds compared to, let's say, Jekyll which I used before.

**Comment by jmooring** [comment]
In the absence of a overwhelming, statistically meaningful data to the contrary, we are not changing the tagline.
