### ISSUE TITLE
Double entries in search results

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#1684]
Seems like links somehow gets indexed both with and without trailing slash.

I'm investigating, but I have never touched the search setup, and don't have access. Have sent Algolia an email about it.

**Comment by coliff** [comment]
The canonical URLs for pages on the site end with a trailing slash. e.g:
`https://gohugo.io/getting-started/configuration-markup/`
but it's currently possible to view:
`https://gohugo.io/getting-started/configuration-markup` (without trailing slash) in the browser. Ideally it should redirect to the canonical URL - that way the URL without trailing slash will not be indexable and the Algolia search crawler will not crawl both URLs.

**Comment by coliff** [comment]
This is still an issue and it's pretty annoying.

@bep can you setup redirects for the URLs to add the trailing slash (see comment above)?

![image](https://user-images.githubusercontent.com/1212885/196746812-69c9abaa-a511-463f-ab1a-baeba345d1a0.png)

**Comment by bep** [comment]
@coliff I have enabled "Pretty URLs" in Netlify, which is documented to something entirely different, but does solve the trailing slash issue above. Let's see if that is also fixing the Algolia issue.

**Comment by bep** [comment]
Crawling now ....

**Comment by bep** [comment]
OK, that didn't fix it, will see if I understand it.

**Comment by coliff** [comment]
I think adding canonical link meta tag would work - so Hugo knows that the corect URL to index is:
`https://gohugo.io/templates/internal/` for example - and not `https://gohugo.io/templates/internal`

**Comment by bep** [comment]
OK ... I figured it out ... I will fix, wait a minute (to my excuse, this wasn't set up by me).
