### ISSUE TITLE
No default values and value format provided for non-content menus

### ISSUE THREAD

**Issue by EmilySeville7cfg** [gohugoio/hugoDocs#1693]
## Description

[There are](https://gohugo.io/content-management/menus/#add-non-content-entries-to-a-menu) no default values and required format provided for:

- identifier
- name
- pre
- post
- url
- weight

It is not clear what identifier format is and there is no any explicit list of valid keys for each menu.

**Comment by thewheat** [comment]
I believe the format details can all be found from a link earlier in the page https://gohugo.io/content-management/menus/#what-is-a-menu-in-hugo

> See the [Menu Entry Properties](https://gohugo.io/variables/menus/) for all the variables and functions related to a menu entry.

I've created this PR https://github.com/gohugoio/hugoDocs/pull/1827 to try address the issue in context by linking to the same section. Feels a bit redundant but open to other ideas of how best to link / display the appropriate information

**Preview of change with new text highlighted**

<img width="745" alt="image" src="https://user-images.githubusercontent.com/892961/193431609-f1abdff6-b294-4b1b-9417-cc8a6bcd8801.png">
