### ISSUE TITLE
Style guide: capitalization of page titles and headings

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugoDocs#1697]
For discussion...

As long as one is consistent throughout a publication, there is nothing grammatically incorrect with a page or heading title such as:

```
This is the page title
```

instead of:

```
This is the Page Title
```

I am of the opinion that the first is easier to read, and is more common than it used to be. For example, I find this:

<img alt="screen capture" width="35%" src="https://user-images.githubusercontent.com/335669/160247452-78265a4d-b81e-44f8-9f43-5ebf1525a26a.png">

is easier to read than this:

<img alt="screen capture" width="35%" src="https://user-images.githubusercontent.com/335669/160247535-36aab13d-8cf9-4406-a3b8-50a6b0ba5882.png">

Yes, the examples above show headings, not page titles, but the same is true when displaying a list of pages in a sidebar.

I think I first noticed this style in the Bootstrap docs (powered by Hugo). For example:
<https://getbootstrap.com/docs/5.1/components/accordion/>

This is not something that can be handled with template functions or styling due to proper nouns (e.g., Hugo) and acronyms (e.g., CSS) within the page title or heading.

To reiterate, there is nothing incorrect about choosing to capitalize just the first letter, as there is not a universal standard, but you must be consistent. Here's another example:
<https://docs.microsoft.com/en-us/style-guide/capitalization>

**Comment by davidsneighbour** [comment]
Isn't that more a question of "subscribing to a writing style" (like AP or Chicago style) and then taking care that they are adhered to? I see this not only in automatically created navigations but all over the place for instance frontmatter has multiple ways: frontmatter, front matter, Front Matter. That the first character is uppercase is a heading reason. 

Having only the first character uppercase, then all titles, names, places with an uppercase character is more readable and parseable. Not only my opinion, but also [Jakob Nielsen's](https://www.nngroup.com/articles/microcontent-how-to-write-headlines-page-titles-and-subject-lines/) (the god of usability)

**Comment by danielfdickinson** [comment]
Is there a Hugo command like 'humanize' that can get rid of the caps for purposes like lists but leave for the actual headings? I think that would leave the headings as many expect them.

I don't mind either way though, just offering a suggestion.

**Comment by danielfdickinson** [comment]
Given that we can't automate thing to have it both ways, I think @jmooring is right and only initial caps is preferable. (FWIW).

**Comment by coliff** [comment]
Yep, let's go with the Microsoft style as @jmooring suggested.
https://learn.microsoft.com/en-us/style-guide/capitalization

**Comment by jmooring** [comment]
@coliff Should we leave this open until the changes have been made?

**Comment by genetikdisoda** [comment]
I prefer the capitalization, but consistency is key!

**Comment by jmooring** [comment]
I'm planning to implement this; the change set will be large.

@bep Any comments before I proceed?
