### ISSUE TITLE
Dead link for RST format

### ISSUE THREAD

**Issue by chicks-net** [gohugoio/hugoDocs#1703]
On https://gohugo.io/content-management/formats/ the link for RST format goes to https://docutils.sourceforge.net/rst.html which looks dead. 💀   https://en.wikipedia.org/wiki/ReStructuredText would be better.

**Comment by jmooring** [comment]
How this instead?
<https://docutils.sourceforge.io/rst.html>

**Comment by chicks-net** [comment]
Since the link is talking about the software specifically and not the format generally I think that would be better.

I figured the page was totally gone, but I guess sourceforge lost their `.net` at some point.
