### ISSUE TITLE
Fix data templates page

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugoDocs#1728]
<https://gohugo.io/templates/data-templates>

This is wrong:

> i.e., given two files with the same name and relative path, the file in the root project data directory will override the file in the themes/<THEME>/data directory).

No. The data is merged, with the data in the project directory taking precedence when there are duplicate keys.

The rest of this page needs some love too.

Include a callout regarding valid file names. See <https://github.com/gohugoio/hugo/issues/9796>.

**Comment by lazyguru** [comment]
I submitted a PR that addresses both points raised here (update language around duplicate keys/files and callout about valid filenames)
