### ISSUE TITLE
Unclear use of parameter name and values in documentation pages

### ISSUE THREAD

**Issue by athulin** [gohugoio/hugoDocs#1734]
Offending page: https://gohugo.io/templates/lookup-order/

Most/all of the sections carry verbiage such as "with posts set" or "with layout set", but doesn't say to what.  In a few cases it is stated ("with type set to "blog"" etc.), but in most cases it is not.  This turns interpretation in a trial-and-error game: is "demolayout" the value or is it a static text that must be used without change?

On some other pages, constructs such as `<path>/<type>.html`  are used, which makes it very easy to see what parameters are used, and how they will be used.  Using this form of presentation consistently, and in particular on this page, would (I strongly suspect) simplify the contents.  For example, on Home page with type set  (presumably to 'demotype', but not explicitly stated), there would not be any need to use "demotype", as it could just be replaced by `<type>`, or equivalent construction.

**Comment by genetikdisoda** [comment]
That whole page is "too much" for a beginner. I propose using diagrams/charts where possible.
