### ISSUE TITLE
Document boolean operators in their own page

### ISSUE THREAD

**Issue by rbn30117** [gohugoio/hugoDocs#1745]
Version 0.92.0 broke several "ne" function occurrences in my theme. "not" works, but it is undocumented. Perhaps document the boolean operators in their own page like [here](https://hugoif.github.io/hugo-by-example/operators/boolean/).

**Comment by bwc69151** [comment]
I was looking if an issue like this exists. Some progress is required here.

**Comment by calalloo** [comment]
Which boolean operators exist in Hugo? cc @jmooring
