### ISSUE TITLE
Document relationship between `services.googleAnalytics.id` and `googleAnalytics` etc

### ISSUE THREAD

**Issue by chalin** [gohugoio/hugoDocs#1780]
For context, see https://discourse.gohugo.io/t/config-is-services-googleanalytics-id-an-alias-for-googleanalytics/39469/6.

Related:

- https://github.com/gohugoio/hugoDocs/issues/1673#issuecomment-1080904294
- See the PR servies by @tuthugo, such as #1773, etc.

**Comment by jmooring** [comment]
This was addressed by https://github.com/gohugoio/hugo/pull/11568
