### ISSUE TITLE
[Not Mentioned] .Format copies unrecognised text

### ISSUE THREAD

**Issue by billthefarmer** [gohugoio/hugoDocs#1789]
The docs for the [Format](https://github.com/gohugoio/hugoDocs/edit/master/content/en/functions/format.md) function do not mention (that I can see) that unrecognised text is copied unchanged, so if I put...
```yaml
copyright: Copyright &copy; 2006 Bill Farmer
```
in `config.yaml` and...
```html
          {{ now.Format .Site.Copyright | markdownify }}
```
in `layouts/_defaults.baseof.html`. It comes out `Copyright © 2022 Bill Farmer`. This doesn't seem to be mentioned in the Go docs either. I only found out because this behaviour is common in other languages and I thought it was worth a try.

**Comment by jmooring** [comment]
<https://pkg.go.dev/time#pkg-constants>

> Text in the layout string that is not recognized as part of the reference time is echoed verbatim during Format and expected to appear verbatim in the input to Parse.
