### ISSUE TITLE
Passing .Content to lower function escapes some punctuation

### ISSUE THREAD

**Issue by anakinsleftleg** [gohugoio/hugoDocs#1798]
If the raw content of a markdown file contains certain punctuation like quotes, and it gets rendered and in the template `.Content` is passed to the function `lower`, that punctuation gets escaped. But if you pass `.RawContent` it remains without being escaped.

__index.md_
```md
---
title: Homepage
---

I'll do what we've always done! > greater < less.
```

_index.html_
```go-html-template
{{ .Content | lower }}
```

_Output_
```
<p>i&rsquo;ll do what we&rsquo;ve always done! &gt; greater &lt; less.</p>
```

What I would expect is all the punctuation to remain, simple the letters to be all lowercase.

**Comment by jmooring** [comment]
Hugo is doing exactly what it should be doing.

markdown

```
Eat at Joe's.
```

template

```
{{ .Content }} --> `<p>Eat at Joe&rsquo;s.</p>`

{{ .Content | lower }} --> `&lt;p&gt;eat at joe&amp;rsquo;s.&lt;/p&gt;`

{{ .Content | lower | safeHTML }} --> `<p>eat at joe&rsquo;s.</p>`

**Comment by anakinsleftleg** [comment]
So I guess it flows from the rendering in Go. Still unexpected. I'll add a note in the docs to expect it.
