### ISSUE TITLE
Pull request backlog

### ISSUE THREAD

**Issue by ddomdel** [gohugoio/hugoDocs#1803]
Hello, I'd like to contribute to the documentation for Hugo docs, however, I'd like to know why so many contributors' pull requests in improving the docs aren't approved. Thank you!

**Comment by callaloo** [comment]
See [this discussion](https://discourse.gohugo.io/t/were-trying-to-help-with-the-docs-many-pull-requests-are-not-being-merged/39784)

**Comment by coliff** [comment]
We're working our way through them. :-)

PRs to improve the docs are welcome!
