### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by ilya1st** [gohugoio/hugoDocs#1808]
https://gohugo.io/content-management/menus/#simple
here
<img width="757" alt="image" src="https://user-images.githubusercontent.com/9489084/189526036-991805e3-c03d-4a42-84bb-a7d0b6827fa1.png">
If make copy-paste of this this will cause following error:
Error: "/Users/iazarov/work/config.toml:1:1": unmarshal failed: toml: key menu should be a table, not a value

**Comment by callaloo** [comment]
You are supposed to add the value to your content. Anyways, ask support questions here discourse.gohugo.io

**Comment by jmooring** [comment]
The documentation you refer to is in the section titled [Add content to menus](https://gohugo.io/content-management/menus/#add-content-to-menus), which is about creating menu entries in front matter, not in site configuration.

> Hugo allows you to add content to a menu via the content’s [front matter](https://gohugo.io/content-management/front-matter/).

You tried to use this syntax in site configuration.

In the future, please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
