### ISSUE TITLE
Supported Content Formats Doc reports wrong management for HTML format?

### ISSUE THREAD

**Issue by c84c** [gohugoio/hugoDocs#1829]
Hi, I'm a noob in Hugo and I want to render a static site with already present HTML contents.

I read docs and in the [List of content formats](https://gohugo.io/content-management/formats/#list-of-content-formats) table I read for HTML format:

> |Name | Markup identifiers | Comment
> |-- | -- | --
> |HTML | html, htm | To be treated as a content file, with layout, shortcodes etc., it must have front matter. **If not, it will be copied as-is**.

So for HTML without front matter I assume that **[...] it will be copied as-is**, but if I put an HTML inside `content` directory I get 
```
Start building sites … 
hugo v0.104.2 linux/amd64 BuildDate=unknown VendorInfo=mage
Error: Error building site: "<contentDir>/<subDir>/index.html:1:1": plain HTML documents not supported
Total in 163 ms
```

Finally, wrong documentation or I misinterpreted documentation?

Thanks for your work!

**Comment by jmooring** [comment]
If the file begins with an HTML comment ( `<!-- something -->` ), it will be parsed as a markdown document and must contain front matter. 

Does your HTML file begin with an HTML comment? If yes, remove it.

In the future, pease use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
