### ISSUE TITLE
Outdated Docs: Configure Minify

### ISSUE THREAD

**Issue by momasta** [gohugoio/hugoDocs#1830]
Hi!

I found a little inconsistency in docs.

In this article: https://gohugo.io/getting-started/configuration/#configure-minify
Under _[minify.tdewolff.html]_, it says _keepWhitespace = false_.

But issue https://github.com/gohugoio/hugo/issues/8771 says the value has been changed to true.
And it is the case as I just verified.
Upon explicitly setting _keepWhitespace = true_ in my config.toml, I finally got rid of white space in my HTML.

Very confusing. I expected --minify to give me output without white space right away.
Docs said "yep, that's the default". Nah, I still got line breaks in output.

Please update, some other people were confused by it too: https://discourse.gohugo.io/t/is-html-minification-broken/34174

**Comment by jmooring** [comment]
The documentation is correct. With [v0.94.0](https://github.com/gohugoio/hugo/releases/tag/v0.94.0) and later, the default value for `minify.tdewolff.html.keepWhitespace` is `false`:

<https://github.com/gohugoio/hugo/blob/master/minifiers/config.go#L38>

We reverted https://github.com/gohugoio/hugo/pull/8772 with https://github.com/gohugoio/hugo/pull/9630 on 8 March 2022.

**Comment by momasta** [comment]
Uh, I see, getting lost in all the info.
Ubuntu says 0.92.2-1 is the latest one which is way out of date. https://packages.ubuntu.com/jammy/hugo

I guess I'll install the snap package instead, that one is at version 0.104.2

My apologies
