### ISSUE TITLE
Update deployment workflow for hosting on GitHub Pages

### ISSUE THREAD

**Issue by JamesMGreene** [gohugoio/hugoDocs#1833]
The [current documentation for hosting Hugo sites on GitHub Pages](https://gohugo.io/hosting-and-deployment/hosting-on-github/) provides a lot of information and an example GitHub Actions workflow that utilize Actions such as [wonderful ✨] `peaceiris/actions-gh-pages`, and mentions the need for manually editing the `baseURL` configuration in the `config.toml` file.

A few months back, the GitHub Pages team announced a [beta release for deploying Pages sites using custom Actions workflows](https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/). While that description doesn't necessarily sound like a big improvement over the existing workflow included in the documentation, it includes several noteworthy aspects:
- Will programmatically configure the `baseURL` during the build
- Can be deployed from _any_ branch
- Does not require pushing to the `gh-pages` branch in order to deploy via the default GitHub Pages build, which avoids the need for an entire second [internal] Actions workflow to be run, thus usually shaving off several minutes from the overall deployment time
  - Doesn't require a `.nojekyll` file present in the repository to avoid the default GitHub Pages build from triggering

Although the feature is currently still considered a beta, as a member of the GitHub Pages team, I can vouch that we have every intention of advancing that feature toward general availability in the future, so I wouldn't let that prevent the documentation from being updated to reflect this improved process.

It might also be worth mentioning that the GitHub UI will now also suggest a Hugo deployment starter workflow if a Hugo site is detected when enabling the GitHub Actions custom workflow deployment setting in a repository. 🚀 

Other links:
- [GitHub documentation for deploying Pages via custom workflows](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#creating-a-custom-github-actions-workflow-to-publish-your-site)
- [Hugo starter workflow template](https://github.com/actions/starter-workflows/blob/main/pages/hugo.yml) utilized by the GitHub UI
  - :warning: Cannot be _just_ copy-and-pasted as it contains template variables :warning:

**Comment by jmooring** [comment]
Resolved with https://github.com/gohugoio/hugoDocs/pull/1991
