### ISSUE TITLE
mod and modBool does not show up in search

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#184]
Not sure how they vanished.

**Comment by digitalcraftsman** [comment]
They aren't. As part of the `math` namespace they have been moved into the same-named [subsection](https://gohugo.io/functions/math/). I guess, all math related functions have been moved into a single file because documenting every function on it's own seemed a bit odd.

**Comment by bep** [comment]
OK; that is fine -- but I tried to search for it, and neither "mod", "modBool" or "Modulus" give any match.

**Comment by digitalcraftsman** [comment]
Tried it as well. The search should be adjusted to take the content into account as well (at least here).

**Comment by kaushalmodi** [comment]
Should this issue be closed? Because it seems to be the same issue as https://github.com/gohugoio/gohugoioTheme/issues/63.

**Comment by jmooring** [comment]
`modbool` shows up in search, but `mod` and `modulus` do not. 

`math mod` will show the mod function.

I don't know where to adjust this.

**Comment by jmooring** [comment]
Closing as duplicate of #2081
