### ISSUE TITLE
Revise installation instructions (setting PATH) for Windows

### ISSUE THREAD

**Issue by alfawal** [gohugoio/hugoDocs#1841]
The two commands in step 3 of Installation -> Windows -> Technical Users ([link](https://gohugo.io/getting-started/installing#technical-users)) has managed to override all of my current user's environment variables just to add Hugo to the PATH.

I've went through the file history and seems that the commands were added/modified in this pull request #1520 

Please fix so no one gets his variables messed up and then needs to waste a day to fix some of them.

**Comment by jmooring** [comment]
I am unable to reproduce the problem. This command seems fine to me:

```
setx PATH "%PATH%;C:\Hugo\bin"
```

**Comment by alfawal** [comment]
I am not sure if the first or the second command broke the environment variables but I am pretty sure that one of them did.

The commands were ran from PowerShell under C:\Users\{username}, not sure if running the commands with PowerShell in this directory would make a difference.

OS: Windows 11
PowerShell version: 7.2.6

**Comment by jmooring** [comment]
The existing documentation says:

> Open Windows Command Line (cmd, “DOS”)

Furthermore:

> but not “Git Bash”, PowerShell, or any other “CLI”

**Comment by jmooring** [comment]
If you use Powershell with the setx command as written in the current documentation, the current user's PATH environment variable is irrevocably hosed. I suggest we dumb this down a bit, and only document setting the environment variable through `rundll32.exe sysdm.cpl,EditEnvironmentVariables`.

**Comment by alfawal** [comment]
I did not realize that it's not supposed to be ran from PowerShell, it would be better to mention it before the commands rather than after, because I thought that it doesn't matter for this command whether its CMD or PowerShell until you mentioned that it was mentioned in the documentation page literally after the two commands.
