### ISSUE TITLE
Proposal - Promote "Installation" to a section

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugoDocs#1866]
I suggest we move "Installation" from "Getting Started" to its own section, located _above_ the "Getting Started" menu entry in the left sidebar. Then we can have sub-pages:
- Overview
- Linux
- MacOS
- Windows
- etc.

The current page is quite long and needs some organizational love.

cc: @coliff

**Comment by coliff** [comment]
Great idea. I'm all for it!
