### ISSUE TITLE
Quickstart fails on windows systems

### ISSUE THREAD

**Issue by deining** [gohugoio/hugoDocs#1918]
The [quick start](https://gohugo.io/getting-started/quick-start/) guide uses this command to define the `ananke` theme in the site configuration:

```
echo "theme = 'ananke'" >> config.toml
```

This command works fine on unix-based systems, but it fails on the windows command line. After issuing this command this line is added at the end of `config.toml`):

```
"theme = 'ananke'"
```

This breaks both site preview and build on windows systems.

I don't have a really good solution here. One workaround I could come up with is to use `yaml` format for the config file:

```
hugo new site quickstart -f yaml
cd quickstart
git init
git submodule add https://github.com/theNewDynamic/gohugo-theme-ananke themes/ananke
echo theme: ananke >> config.toml
hugo server
```

This solution works both on the shell and at the command line. Do you like this approach?

**Comment by jmooring** [comment]
TOML may be a little more trouble to write (tables), but it is harder to get wrong. 

And this fails on PowerShell, which is arguably the default Win shell these days:

```
echo theme: ananke >> config.yaml
```

My first thought is either another sentence, or a notation, beneath:

> You must also be comfortable working from the command line.

**Comment by jmooring** [comment]
We can use the existing command with PowerShell if we change `hugo new site` to write \r\n instead of \n.

**Comment by jafaican** [comment]
Just emphasize Git as the default command 'tool' for Hugo. This is a PowerShell issue. Even VS Code was unable to open the configuration file.

**Comment by jmooring** [comment]
The commands in the Quick Start guide work fine with PowerShell (7.x), but not with Windows PowerShell (5.1) or Command Prompt (cmd.exe), all of which can be run from Windows Terminal. I'm trying really hard not to have an opinion about this, but there's a product manager somewhere who needs some help.

I'm going to footnote this, and if users get it wrong we can make it more prominent in the future.
