### ISSUE TITLE
Provide clear documentation for Dart Sass installation, configuration, and usage

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugoDocs#1921]
See <https://github.com/gohugoio/hugo/issues/8299#issuecomment-1327841933>

Ref: <https://discourse.gohugo.io/t/first-stable-release-of-dart-sass-embedded/36911/2>

**Comment by Kissaki** [comment]
[Current Sass docs](https://gohugo.io/hugo-pipes/scss-sass/) link for reference

What scope and place would you like Sass setup docs to have? A short section at the beginning of that page? A separate page with a lot of optional details?

I feel like short setup notes would be helpful and reasonable. But I don’t think extensive configuration or usage of sass itself is in scope for Hugo.

So what are you looking for in configuration and usage beyond what is already documented?

**Comment by jmooring** [comment]
This isn't actionable at the moment. If we add something to the docs at some point, it would be somewhere else.

We have a broad spectrum of users, from those have never used the command line, to those who build everything from source. Inexperienced users sometimes have trouble modifying their PATH environment variable, but I don't think it is our job to teach them. I recently rempoved this from the Hugo installation documentation, for very good reasons, replacing it with:

> Please consult your operating system documentation if you need help setting file permissions or modifying your PATH environment variable.

For inexperienced users, using a package manager is easier, assuming they can install a package manager. Ideally there would be dart-sass-embedded community packages (not created or maintained by the Hugo developers) for:

- Chocolatey (Windows)
- Homebrew (macOS, Linux)
- MacPorts (macOS)
- Scoop (Windows)
- Snap (Linux)

Hugo is available for each. Only the Snap package is maintained by the Hugo developers.

Related article by @brycewray:
<https://www.brycewray.com/posts/2022/05/using-dart-sass-hugo-nitty-gritty/>

**Comment by merchako** [comment]
Thank you for the work you've done creating installers for Snap, Chocolatey, and Scoop, @jmooring. I agree that there's only so much that can be communicated in a ReadMe. 

> Inexperienced users sometimes have trouble modifying their PATH environment variable, but I don't think it is our job to teach them.

There are some particulars about installing and configuring Embedded Dart Sass that were exceptionally unintuitive even for more experienced developers, that

1. Dart Sass Embedded is completely different from other Dart Sass packages when it comes to solving their Hugo problems, and 
2. Users must add the `sass_embedded/` to their path, not just its containing folder. 

```
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/bin/sass_embedded:$PATH"
```
I was only able to work out this detail thanks for [Bryce Wray's articles](https://www.brycewray.com/posts/2022/05/using-dart-sass-hugo-nitty-gritty/).

This is the chain of Hugo documentation that I believe for users to notice the need for Dart Sass Embedded:
 
1. [Hugo Pips Docs on  Sass](https://gohugo.io/hugo-pipes/scss-sass/)
2. "You need to download a release binary from [Embedded Dart Sass](https://github.com/sass/dart-sass-embedded/releases) and make sure it’s in your PC’s $PATH"
3. Embedded Dart Sass release page has no instructions for installation, so go to [Readme](https://github.com/sass/dart-sass-embedded)
4. Readme has no installation or configuration instructions, but it links to the [Dart Sass page](https://sass-lang.com/dart-sass) on the Sass website
5. Sass website has [installation instructions](https://sass-lang.com/install) for completely different packages, as well as to [Sass Embedded on NPM](https://www.npmjs.com/package/sass-embedded)

With a lack of any installation instructions in that chain, it's likely users will get confused, maybe google and wind up who knows where, try to install a different Sass package, or try to install the Node package.

**Comment by merchako** [comment]
Homebrew now has a [dart-sass-embedded formula](https://github.com/sass/homebrew-sass/blob/HEAD/dart-sass-embedded.rb). (See [completed issue](https://github.com/sass/homebrew-sass/pull/49)).

Package manager | OS | Status | Installation
-- | -- | -- | --
Chocolatey | Windows | Pending approval 1 | chocolatey.org
Scoop | Windows | ✔️ | scoop.sh
Snap | Linux | ✔️ | snapcraft.io
Homebrew | macOS, Linux | ✔️ |  
MacPorts | macOS | Possible 3 |

**Comment by jmooring** [comment]
This will ultimately change with <https://github.com/gohugoio/hugo/issues/11059>.

**Comment by jmooring** [comment]
Embedded Dart Sass was deprecated in favor of [Dart Sass](https://github.com/sass/dart-sass). Hugo [v0.114.0](https://github.com/gohugoio/hugo/releases/tag/v0.114.0) and later are compatible with both Dart Sass (v1.63.4 and later) and Embedded Dart Sass (v1.62.1 and earlier). 

To install Dart Sass:

OS|Package manager|Site|Installation
:--|:--|:--|:--
Linux|Homebrew|[brew.sh](https://brew.sh/)|`brew install sass/sass/sass`
Linux|Snap|[snapcraft.io](https://snapcraft.io/dart-sass)|`sudo snap install dart-sass`
macOS|Homebrew|[brew.sh](https://brew.sh/)|`brew install sass/sass/sass`
Windows|Chocolatey|[chocolatey.org](https://community.chocolatey.org/packages/dart-sass-embedded)|`choco install sass`
Windows|Scoop|[scoop.sh](https://scoop.sh/#/apps?q=sass)|`scoop install sass`

You may also install [prebuilt binaries](https://github.com/sass/dart-sass/releases/latest) for Linux, macOS, and Windows.

To determine which transpiler will be used when you build a site:

```text
hugo env
```

**Comment by bep** [comment]
@jmooring that table is great. A foot note: I haven't checked, but I was also hoping that this move also would get the dart binary into the build setups of the most popular build hosts (e.g. Netlify, `SASS_VERSION=v1.63.4`), but there's probably some more plough work to be done there.

**Comment by brycewray** [comment]
@bep @jmooring I've already been talking to the Cloudflare Pages folks about that, since their new "v2" build image already has `EMBEDDED_DART_SASS_VERSION` (also at my request for Hugo users). I am told that, within the next couple of weeks, they'll also add `DART_SASS_VERSION` to accommodate the new packaging.
