### ISSUE TITLE
Quick Start guide gives errors

### ISSUE THREAD

**Issue by ANJ-Projects** [gohugoio/hugoDocs#1954]
https://gohugo.io/getting-started/quick-start/

At the
https://gohugo.io/getting-started/quick-start/#commands

Error
`
Start building sites …
hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168 windows/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=gohugoio
Error: Error building site: TOCSS: failed to transform "ananke/css/main.css" (text/css). Check your Hugo installation; you need the extended version to build SCSS/SASS with transpiler set to 'libsass'.: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
`

Success install instead
```
hugo new site quickstart   
cd quickstart
git init
git submodule add https://github.com/adityatelange/hugo-PaperMod themes/papermod
echo "theme = 'papermod'" >> config.toml
hugo server
````

Here I just replaced the theme ananke with papermod found from
https://themes.gohugo.io/themes/hugo-papermod/

**Comment by jmooring** [comment]
I'm not sure how we can we make this requirement any clearer:

![image](https://user-images.githubusercontent.com/335669/213280145-e28cce73-2eb9-4ea9-b8b1-61dd282d5d78.png)

**Comment by ANJ-Projects** [comment]
https://gohugo.io/#:~:text=%24%20choco%20install%20hugo%20%2Dconfirm
Update the main site to include Extended edition then. There is no reason a quickstart should require extra stuff. If it requires extra stuff then it is not a quick start.

Must have skipped ahead the small text because it was already installed. (Sometimes if I think I have read something I miss important details) Of course if extra complicity is no problem and simplicity is not a goal of Hugo then ignore this. It's just to help newbies not make the same mistake. Sorry dude. It's just stuff here on github, some love making their stuff as easy and dumb proof as can be and some seem to directly make stuff more complicated than needed to be.
