### ISSUE TITLE
Uniq: It's unclear what "subsequent duplicate elements" means

### ISSUE THREAD

**Issue by willfaught** [gohugoio/hugoDocs#1961]
https://github.com/gohugoio/hugoDocs/blob/914ca0c387424313454b7cdf6d4fc3b00c13f3ec/content/en/functions/uniq.md?plain=1#L4

Subsequent to what? Does it mean adjacent duplicate elements?

**Comment by bep** [comment]
I suspect the person who wrote that wanted to show off his/hers word skills. It "removes duplicate elements". I tried to edit it directly on GitHub, but now that doesn't work ... I suspect this comes from me upgrading to MacOS Ventura last night. Have had all kinds of issues since then, so glad I took a full backup before upgrading.

**Comment by jmooring** [comment]
Fixed.

**Comment by willfaught** [comment]
Does it require duplicates to be adjacent, like Unix's uniq? In other words, do I need to do `sort | uniq`? That was my original question when looking at the doc. It would help to explain that in the doc, either way.

**Comment by jmooring** [comment]
@willfaught I've changed the example to show that it does not sort, but have left the description as-is. If it sorted, we would add that to the description. We document what things do, not what they don't do.

**Comment by willfaught** [comment]
Unix command uniq doesn't sort input either, but it only removes duplicates that are adjacent. In other words, `printf "a\na\n" | uniq` prints `a\n`, but `printf "a\nb\na\n" | uniq` prints `a\nb\na\n`. This is why you have to ensure the input for `uniq` in Unix is sorted, hence `sort | uniq`. My question is whether Hugo's `uniq` works this way too. Does uniq require its input to be sorted to remove duplicates?

**Comment by jmooring** [comment]
> Does uniq require its input to be sorted to remove duplicates?

If it did, we would say so. The example makes this clear.

**Comment by bep** [comment]
The examples does not show this very well, but all of the similar collection/set funcs in Hugo can operate on any comparable types (which in Go excludes maps, slices and funcs), that means that you can pass slices of objects to `uniq` that doesn't have a natural sort order (e.g. lists of pages).
