### ISSUE TITLE
Inconsistent "URL" capitalization

### ISSUE THREAD

**Issue by willfaught** [gohugoio/hugoDocs#1976]
https://github.com/gohugoio/hugoDocs/blob/3e3458f09d37fe22d5ddfed239a62194760883f5/content/en/functions/urls.Parse.md?plain=1#L3

"url" vs "URL"

Should be "URL" everywhere.

**Comment by jmooring** [comment]
Closed with https://github.com/gohugoio/hugoDocs/commit/6f0a5f3f0feefc742b64ff95a0862c163da88c7a

**Comment by willfaught** [comment]
Dang, you beat me to it! 😁
