### ISSUE TITLE
urls.Parse doc doesn't explain what happens if URL is invalid

### ISSUE THREAD

**Issue by willfaught** [gohugoio/hugoDocs#1977]
https://github.com/gohugoio/hugoDocs/blob/3e3458f09d37fe22d5ddfed239a62194760883f5/content/en/functions/urls.Parse.md?plain=1#L26

What's the result value then? Nil? A zero net.URL? I hope it's nil so we can test for falsey values.

**Comment by jmooring** [comment]
Run this code:

```text
{{ $s := slice 0 false true "" " " "a" "a:" "htp://a" "htp:a" "http:/a" "http://a" }}

{{ range $s }}
<pre>
url = {{ . }}

{{ jsonify (dict "indent" "  ") (urls.Parse .) }}
</pre>
<hr>
{{ end }}
```

**Comment by willfaught** [comment]
Right, I'm sure there's a way to figure it out like that. The point is that the doc should explain it so we don't have to do that.
