### ISSUE TITLE
getting-started/quick-start.md - Windows Powershell works fine

### ISSUE THREAD

**Issue by mmikeww** [gohugoio/hugoDocs#1982]
There is a note on this page:
https://github.com/gohugoio/hugoDocs/blob/master/content/en/getting-started/quick-start.md

That the commands must be run with the new Powershell (ie, not "Windows Powershell"). But I believe I'm still on the old Windows Powershell on my win10 machine and the commands worked fine. 

I'm using the chocolatey hugo package. Running ` $PSVersionTable` reports Powershell version 5.1

**Comment by jmooring** [comment]
The `hugo new site` command creates a config.toml with UTF-8 encoding.

But when you do this with Windows Powershell...

```
echo "theme = 'ananke'" >> config.toml
```

...the config.toml file is corrupted.

Why? Because std out from Windows Powershell is encoded in UTF-16 LE.

**Comment by mmikeww** [comment]
Yes you are correct, I had to edit the config.toml. Nevermind. Closing this
