### ISSUE TITLE
dateformat func doesn't show in search results

### ISSUE THREAD

**Issue by willfaught** [gohugoio/hugoDocs#1989]
https://github.com/gohugoio/hugoDocs/blob/0651a76e030228354bcdecc8610e538a2693b501/content/en/functions/dateformat.md?plain=1#L21

**Comment by bep** [comment]
<img width="656" alt="image" src="https://user-images.githubusercontent.com/394382/222951585-286cb39b-7551-4077-8f49-ca23cedb38b4.png">

?

**Comment by willfaught** [comment]
It’s not listed on the left side as a function. A quick skim through the results looking at that side finds nothing.On Mar 5, 2023, at 1:05 AM, Bjørn Erik Pedersen ***@***.***> wrote:﻿

?

**Comment by jmooring** [comment]
It's an alias to `time.Format`, which is listed in the sidebar. I believe the existing documentation was written before the template functions were name-spaced, so what we now consider aliases were, at some point, not aliases.

Consequently, the existing documentation sidebar is inconsistent, showing aliases in some cases, and name-spaced definitions in others.

There's new documentation in the works that eliminates this inconsistency---all functions are name-spaced, but still searchable by alias.
