### ISSUE TITLE
.Fragments need clearer explanation

### ISSUE THREAD

**Issue by chrillek** [gohugoio/hugoDocs#2001]
> The .Fragments method returns a list of fragments for the current page.

is too short, self-referring and redundant to help much. Readers would like to know what "fragments of a page" even _are_. Something like

> The .Fragments method returns HTML elements or attributes from the rendered content of the current page. Currently, it can deliver all headings (`.Fragments.Headings`) and ID attributes (`Fragment.Identifiers`). 

Then, under the heading `.Headings`, the sentences

> A recursive list of headings for the current page. Can be used to generate a table of contents.

might be rewritten as 

> .Fragments.Headings returns a list of all headings for the current page in order of appearance. This list can be used to generate a table of contents. 

The term "recursive" is at best misleading (I do _not_ see any recursion in a simple list of all `h*` elements on a page), at worst irritating.

**Comment by bep** [comment]
>The term "recursive" is at best misleading (I do not see any recursion in a simple list of all h* elements on a page), at worst irritating.

What I probably had in mind when writing that was that you will need a recursive template to render that data structure.

**Comment by chrillek** [comment]
> What I probably had in mind when writing that was that you will need a recursive template to render that data structure.

From the original first sentence ("a list of fragments") I'd conclude that `.Fragments.Headings` returns something like
```html
<h1>Heading 1</h1>
<h2>Heading 1-2</h2>
<h3>Heading 1-2-3</h3>
<h2>Heading 1-2, the 2nd</h2>
```
which I could directly convert to a toc, no recursion at all. But maybe my assumption is wrong.

**Comment by bep** [comment]
>But maybe my assumption is wrong.

Yes. It's possible to build the same structure as `.TableOfContents`, which is a tree structure.
