### ISSUE TITLE
Add frontmatter.codes to Website

### ISSUE THREAD

**Issue by Simon99de** [gohugoio/hugoDocs#2019]
This tool could be added here:
https://gohugo.io/tools/frontends/

https://frontmatter.codes/

**Comment by jmooring** [comment]
See <https://github.com/gohugoio/hugoDocs/issues/1573#issue-1053364284>

> I understand that people want a link to their project they have worked hard on, but we cannot be a link collection.

**Comment by Simon99de** [comment]
OK, I am aware of that, but this is not a project of mine. The project is active now over 3 years and has also several programmers and sponsors. The current page includes projects that are no longer programmed (even the alpha). (And that already years)
A revision would be useful possibly.
https://github.com/estruyf/vscode-front-matter
