### ISSUE TITLE
Is this documented?

### ISSUE THREAD

**Issue by bwc69151** [gohugoio/hugoDocs#2044]
https://github.com/gohugoio/hugo/pull/4494#issue-304147539

**Comment by jmooring** [comment]
<https://gohugo.io/getting-started/configuration/#configure-front-matter>

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by bwc69151** [comment]
None of the keywords I searched on google pointed to the docs. Only the different issues on Github. That section needs to be reworked. One of the key words was "extract date from filenam hugo".
