### ISSUE TITLE
Documentation: Installation: Linux: Snap: a warning should be put there about Snap's known shortcoming due to Snap's strict confinement policy

### ISSUE THREAD

**Issue by kirisakow** [gohugoio/hugoDocs#2049]
**Problem**

Installing Hugo with Snap results in shortcomings, and these have already been abundantly discussed since 2016 (see issues https://github.com/gohugoio/hugo/issues/10757 https://github.com/gohugoio/hugo/issues/10337 https://github.com/gohugoio/hugo/issues/5573 https://github.com/gohugoio/hugo/issues/4336 https://github.com/gohugoio/hugo/issues/3143 https://github.com/gohugoio/hugo/issues/2532). Still, to this day there is no warning about that matter in the [Snap section of the installation documentation](https://github.com/gohugoio/hugo/blob/master/docs/content/en/installation/linux.md#snap).

**Proposal**

Add a warning saying something like

> ⚠️ Keep in mind that due to Snap's strict confinement policy, installing Hugo with Snap will make it impossible to run the main Hugo commands (`hugo mod`, `hugo new`, `hugo server`) in directories located outside the user's `home` directory.

**Comment by jmooring** [comment]
I will add a note next to the Snap installation instructions, but this is inaccurate:

> will make it impossible to run the main Hugo commands (hugo mod, hugo new, hugo server) in directories located outside the user's home directory.

The isolation provided by strict confinement does not prevent you from running the hugo commands in any directory. Instead, it prevents you from creating and building sites outside of your $HOME directory or outside of directories on removable media.

We have permission to offer classic confinement, but have taken the conservative approach to isolation--opening interfaces as needed is simple; closing them after release is not. There are currently around 13,000 snap installations in the wild, and the requests for classic confinement have been limited.

The Hugo snap package initially had a number of limitations related to dependencies (Git, Go, Dart Sass, etc.). @anthonyfok has done a remarkable job of removing these limitations, and I am grateful for his efforts.
