### ISSUE TITLE
re: #2060. Search not working

### ISSUE THREAD

**Issue by jesusfj710** [gohugoio/hugoDocs#2062]
Hello,

Yesterday, I reported a bug related to the search feature on the website (#2060). Despite receiving a response from the maintainer, the issue still persists. I have tested the search feature on multiple browsers and platforms, and it appears that there is an issue with the details of the request and the response.

In response to my report, @jmooring suggested searching for a term that exists, but it should be noted that this did not resolve the issue. In fact, even searching for the term "list" does not return any results.

After doing some testing, I have found that the bug occurs when a user types something in the search box and presses the enter key before getting any results in the search box suggestion. This happens regardless of the search term used.

To replicate the issue, follow these steps:
1. Go to the search box on the website.
2. Type any search term.
3. Before any results appear in the search box suggestion, press the enter key.

I have also attached twos video demonstrating this issue.

Please let me know if you require any further information or clarification.

Thank you for your attention to this matter. I believe that resolving this issue will improve the user experience for all visitors to the website.

https://user-images.githubusercontent.com/71794881/232471536-df560f2d-4854-4b56-88b8-d7fe33188867.mov

https://user-images.githubusercontent.com/71794881/232471586-a13a979c-6871-49de-8248-b4fa82038cf6.mov

**Comment by bwc69151** [comment]
I can confirm that this happens sometimes on the first attempt after opening the site, but not on subsequent attempts. Typing the search term and quickly pressing enter reloads the page, but no search terms appear. I observed this some months ago, but I thought it was a minor delay in fetching the Algolia index.

**Comment by bep** [comment]
>Yesterday, I reported a bug related to the search feature on the website (https://github.com/gohugoio/hugoDocs/issues/2060). Despite receiving a response from the maintainer, the issue still persists.

@jesusfj710 do you remember the last time you reported something like this to a commercial company, e.g. Google, how long was the response time? One day? And the n remember that this is a open source project where people spend their free time.

**Comment by jesusfj710** [comment]
@bep I am sorry for my comment. My intention was not to highlight how long it took or not to resolve the problem (whether the bug exists or not). What I meant to refer to is that the issue was closed and locked without a clear or coherent explanation, when I provided evidence that it was clearly happening.

Please consider reviewing the original issue when you have time and I think you can better understand the context of what I was trying to say. I still apologise if it was misunderstood.

**Comment by jmooring** [comment]
I still can't reproduce this, and other than @bwc69151's comment about intermittently seeing this a few months ago, there have been no other reports of this behavior. And the search feature is used frequently by many, many people.

I don't think this is actionable.

**Comment by bwc69151** [comment]
> I don't think this is actionable.

Agreed. https://prnt.sc/QWhe9yepDSV1

**Comment by bwc69151** [comment]
> > I don't think this is actionable.
> 
> Agreed. https://prnt.sc/QWhe9yepDSV1

@jesusfj710 what's your operating system, browser(s) and browser version?
