### ISSUE TITLE
Document the correct way for linking internally in Hugo

### ISSUE THREAD

**Issue by bwc69151** [gohugoio/hugoDocs#2066]
I found [this discussion](https://discourse.gohugo.io/t/41939) while looking for a similar solution to omit the language prefix. Coming from WordPress, I cannot change my previous posts, nor use the recommended method in that post since Hugo throws hundreds of errors. with that in mind, I strongly support the idea to document the idea, especially for those moving to Hugo.

**Comment by jmooring** [comment]
It would be helpful to have a minimal example (a repository) of what you are starting with, but it would be better to continue this discussion as a [forum topic](https://discourse.gohugo.io/) until there's a bit more clarity. Closing this for now.
