### ISSUE TITLE
The Quick Start section is very vague about the difference between PowerShell and Windows PowerShell.

### ISSUE THREAD

**Issue by bradykelly** [gohugoio/hugoDocs#2070]
The 'Create a site' section for Windows users says to use `PowerShell` and not `Windows PowerShell`. It goes on to be greatly helpful explaining the difference between these versions with the terse sentence, "PowerShell and Windows PowerShell are different applications."

For the average Windows user just wanting to build a simple website, that could be tremendously confusing. I think you should state that one must use the cross-platform version of PowerShell and supply a link to instructions for installing the correct PowerShell version.

**Comment by bwc69151** [comment]
It is even more confusing when there is a step to install git and again being told to use Powershell. Git can ran all the commands and I decided to use it  by default.

**Comment by jmooring** [comment]
> It is even more confusing when there is a step to install git and again being told to use Powershell.

This was clarified on 27 Feb 2023. See https://github.com/gohugoio/hugoDocs/pull/1984.

![Screenshot 2023-07-02 131337](https://github.com/gohugoio/hugoDocs/assets/335669/b725ca5d-c85e-4e3c-afcd-219d2d5310fe)

**Comment by jmooring** [comment]
>  supply a link to instructions for installing the correct PowerShell version

This was addressed on 27 Feb 2023. See https://github.com/gohugoio/hugoDocs/pull/1984 and the screen capture in my previous comment. The link points to the [installation instructions](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.3).

>  It goes on to be greatly helpful explaining the difference between these versions with the terse sentence

We added a link to Microsoft's description of the differences between PowerShell and Windows PowerShell in https://github.com/gohugoio/hugoDocs/commit/d1aa1c1f5202462056ed7eba7268ccd1553c0ca2. If that explanation is insufficient, please raise an issue with Microsoft.
