### ISSUE TITLE
Some of the math functions do not appear in search results

### ISSUE THREAD

**Issue by chrillek** [gohugoio/hugoDocs#2081]
Currently, one has to search for "Math" to find "div", "mul", "add" etc. OTOH, String functions and path properties are easier to discover.

**Comment by dryscord** [comment]
Related #184

**Comment by jmooring** [comment]
Missing from results:

- [ ] add
- [ ] sub
- [ ] mul
- [ ] mod

**Comment by jmooring** [comment]
This was resolved with https://github.com/gohugoio/hugoDocs/pull/2296.
