### ISSUE TITLE
Settle on one term for map/dictionary and slice/array

### ISSUE THREAD

**Issue by chrillek** [gohugoio/hugoDocs#2085]
Especially for newbies, the mix of terms (`dict` creates a dictionary, but `range` iterates over a map, a slice or an array – never a dictionary) is irritating. If a slice is the same as an array, say `slice` (since that's the function used to create the object). Same for dictionary and map. If they are different, the difference should be explained clearly.

**Comment by jmooring** [comment]
Addressed "map" vs. "dictionary" in #2183.

How we use "slice" and "array" is not as simple. Sometimes we should use "array" (e.g., when referring to a YAML array), sometimes we should use "slice", and sometimes we should refer to both.

From <https://go.dev/tour/moretypes/7>:
 
>Slices
>An array has a fixed size. A slice, on the other hand, is a dynamically-sized, flexible view into the elements of an array. In practice, slices are much more common than arrays.

Let's address this in a glossary of terms. See <https://github.com/gohugoio/hugoDocs/issues/2184>.
