### ISSUE TITLE
Quick Start - recommended template - submodules vs Hugo Modules

### ISSUE THREAD

**Issue by gavinr** [gohugoio/hugoDocs#2096]
The current quick start page suggests to use Git submodules:

![image](https://github.com/gohugoio/hugoDocs/assets/209355/d2ff24d7-1539-4bb2-817f-b5897cf98f7c)

but if you go to the [theme's README](https://github.com/theNewDynamic/gohugo-theme-ananke#installation), they suggest using Hugo modules:

![image](https://github.com/gohugoio/hugoDocs/assets/209355/a31a39c2-8d64-493d-a9d4-08aab1dbfca6)

I guess the Hugo Quick Start might be avoiding requiring installing Go as a dependency, which makes total sense. Also it seems like Hugo Modules are new .... but just wanted to ask the question if/when the Quick Start page should recommend using Hugo Modules for getting the theme over a Git submodule?

Thank you!!

**Comment by jmooring** [comment]
There are a couple of reasons to keep the quick start guide as is (using `git submodule add`).

First, as you pointed out, the only dependency is Git. 

Second, with `git submodule add`, the user can **immediately** see and explore the theme's structure and templates; they can poke around. Installing the theme as Hugo module, they would have to `hugo mod vendor` to see the files, and we would have to explain what that means, how to undo it, etc.
