### ISSUE TITLE
Document navigateToChanged

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#21]
Once this is merged: https://github.com/gohugoio/hugo/pull/3645

**Comment by digitalcraftsman** [comment]
A picture, well it's a GIF, tells more than a thousand words. We should include the sneak peak video from Bjørn as well.

https://twitter.com/GoHugoIO/status/879065641315119104

**Comment by bep** [comment]
>We should include the sneak peak video from Bjørn as well (or something alike).

If you want to use my first name, you should use my full first name ("Bjørn Erik"); If someone shouts "Bjørn" at me in the street, I don't react.

**Comment by digitalcraftsman** [comment]
> If you want to use my first name, you should use my full first name ("Bjørn Erik"); If someone shouts "Bjørn" at me in the street, I don't react.

I'm sorry and know it better the next time :wink: Most people I know that have a middle name omit it in their daily life

**Comment by bep** [comment]
>You Norwegians might handle them differently

I think that is about 50/50, but in my case using the first would be ambiguous.

**Comment by anthonyfok** [comment]
I didn't know that either!  Thanks for letting us know!
(I was avoiding using "@bep" too so I don't wake you up in an opportune time, hehe.)

**Comment by kaushalmodi** [comment]
Related: https://github.com/gohugoio/gohugoioTheme/issues/63#issuecomment-373811385

**Comment by bmackinney** [comment]
I think this can be closed - the option is currently documented at https://gohugo.io/commands/hugo_server#options

**Comment by kenmorse** [comment]
Yes, looks like this was added in commit 0a55ad11b8d6a882373caac4cf49563a4009a998.
