### ISSUE TITLE
Quick start site does not work usign hugo.toml instead of config.toml

### ISSUE THREAD

**Issue by Cirius1792** [gohugoio/hugoDocs#2100]
Following the instructions in the quick start guide results in a site not showing no content. 

To fix the issue the line:
`echo "theme = 'ananke'" >> hugo.toml`
Should be replaced with:
 `echo "theme = 'ananke'" >> config.toml`

I don't know the cause of this  problem as this is my first approach with Hugo

**Comment by jmooring** [comment]
<https://gohugo.io/getting-started/quick-start/#prerequisites>

![b57c562a-89ba-4171-86bf-9ad0e4a3a7df](https://github.com/gohugoio/hugoDocs/assets/335669/794f13fb-62ac-44a5-a862-9e48a84a0ad9)
