### ISSUE TITLE
Consider updating the docs for Dart Sass on Netlify to use Brewfile.netlify

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#2122]
I have confirmed that this works out of the box with Hugo:

https://github.com/bep/galleriesdeluxe/blob/main/Brewfile.netlify

It's marked as experimental in the Netlify docs, but so is lots of stuff these days ...

@jmooring

**Comment by jmooring** [comment]
If you are paying for build time...

```text
$ time brew install sass/sass/sass

real	1m27.077s
user	0m46.632s
sys	0m35.418s


$ time curl -LJO https://github.com/sass/dart-sass/releases/download/1.63.5/dart-sass-1.63.5-linux-x64.tar.gz && tar -xf dart-sass-1.63.5-linux-x64.tar.gz

real	0m1.007s
user	0m0.132s
sys	0m0.033s
```

I'm not sure if brew installations are cached between builds.

It is also useful to be able to specify _any_ version instead of what's available in the tap (e.g., roll back).

**Comment by bep** [comment]
Yea, right ...

I'll see if I can somehow get this into Netlify's (cached) setup.
