### ISSUE TITLE
Getting started page - hugo.toml instead of config.toml

### ISSUE THREAD

**Issue by soumen-basu** [gohugoio/hugoDocs#2125]
In the getting started page, one of the first steps is to install the ananke theme and add it to the config file.  However, the command given appends it to hugo.toml, which raises an error.

This theme needs to be set in config.toml.

**Comment by jmooring** [comment]
<https://gohugo.io/getting-started/quick-start/#prerequisites>

![prereq](https://github.com/gohugoio/hugoDocs/assets/335669/7ae2951f-294b-4821-8e9b-843ab3c8655b)
