### ISSUE TITLE
Does `defaultContentLanguage` still need to be lowercase?

### ISSUE THREAD

**Issue by adrian5** [gohugoio/hugoDocs#2146]
With [this](https://github.com/gohugoio/hugoDocs/commit/763dd64046695447094cada69cb622686f21b254#diff-9860ea8505d0df2001fb852358a055e97a6815fc1e796a17339553a17ebde6edL70) change, does [this](https://github.com/gohugoio/hugoDocs/blob/master/content/en/content-management/multilingual.md?plain=1#L54) still hold true?

> The project's default language tag as defined by [RFC 5646]. **Must be lower case**, and must match one of the defined language keys. Default is `en`.

**Comment by adrian5** [comment]
Thanks Joe, I hadn't run Hugo yet to try! I'm currently in the project setup phase going through the docs and had read an [earlier](https://github.com/gohugoio/hugo/issues/7344#issuecomment-1569277649) comment of yours. Has this change been reverted?

**Comment by jmooring** [comment]
site configuration

```
defaultContentLanguage = 'EN'

[languages.en] (or [languages.EN] 
```

command

`hugo`

result: site renders w/o errors

**Comment by adrian5** [comment]
Ah, right.
