### ISSUE TITLE
theme.gohugo.io site's twitter logo is different position

### ISSUE THREAD

**Issue by mingkyme** [gohugoio/hugoDocs#2155]
<img width="225" alt="스크린샷 2023-07-26 10 30 46" src="https://github.com/gohugoio/hugoDocs/assets/45954551/a4fadbc7-cd46-4468-8c54-65a6a2484cb2">
<img width="225" alt="스크린샷 2023-07-26 10 30 40" src="https://github.com/gohugoio/hugoDocs/assets/45954551/ec60b246-a158-412c-947b-1160e20f329e">

**Comment by jmooring** [comment]
If you feel strongly about this, please create an issue in <https://github.com/gohugoio/gohugoioTheme>.
