### ISSUE TITLE
List valid values for `language` parameter for `highlight` shortcode

### ISSUE THREAD

**Issue by i-give-up** [gohugoio/hugoDocs#221]
Both [Shortcode](https://gohugo.io/content-management/shortcodes/#highlight) and [Syntax Highlighting](https://gohugo.io/content-management/syntax-highlighting/) page don't list the valid `language` values for `highlight`. What I mean is mentioning for example that you can use either `js` or `javascript` to highlight the block as JavaScript.

Easiest way is probably to mention that you can use `pygmentize -L lexers` or `chroma --list` to get a list of valid values for the corresponding syntax highlighter. The problem is that Hugo users don't have to install `chroma` to use it in Hugo, so they won't have the `chroma` command. So how would the users get the list of languages/aliases for `chroma`?

**Comment by NuLL3rr0r** [comment]
That would be great if a list of supported languages could be added to the documentation.

**Comment by bep** [comment]
Yes, that would be useful. But it would also be nice if we didn't have to maintain that list.

I will create a mirror-issue in the other repo for this to add:

A docs helper to create a JSON with those values and then show then on this site.
