### ISSUE TITLE
Add `.Name` to archetype documentation

### ISSUE THREAD

**Issue by chrillek** [gohugoio/hugoDocs#2222]
Here
https://gohugo.io/content-management/archetypes/#functions-and-context
is a list of variables/functions/methods available to archetypes. However, `.Name` is not explained, but it is obviously present:

https://discourse.gohugo.io/t/what-variables-are-exposed-to-the-archetype-file-when-using-hugo-new-like-name/34132/7

I'd suggest completing this part of the documentation with the missing variables/functions/methods.

**Comment by jmooring** [comment]
I intentionally removed `.Dir` and `.Name` as they are both covered by `.File.xxx`.

**Comment by chrillek** [comment]
I do not see `.Name` documented in `.File` (though there are `BaseFileName`, `LogicalName` and a simple `Filename`. Also, It's not clear if one had to use `.File.<whatever>` in the Archetype or simply `.<whatever>`. 

And if `.Name` exists in `.File`, why can't searching in the doc find it, at all?

**Comment by jmooring** [comment]
1\) In the context of an archetype, `.Name` returns `.File.ContentBaseName`.
<https://github.com/gohugoio/hugo/blob/94fbab2a8865737c8fb7fe1469215a688ba21314/hugolib/content_factory.go#L179-L181>

2\) `.Name` isn't descriptive. What is it? The best explanation is... the same thing as `.File.ContentBaseName`. So why even mention `.Name` in the documentation?

3\) In the next release, the default archetypes (site, theme, and fallback) use `.File.ContentBaseName`.

> It's not clear if one had to use `File.<whatever>`

Both examples on the [archetypes page](https://gohugo.io/content-management/archetypes/) show `.File.ContentBaseName`.

To reduce confusion, I've removed outdated forum topic to which you referred.
