### ISSUE TITLE
Improve "where with boolean values"

### ISSUE THREAD

**Issue by chrillek** [gohugoio/hugoDocs#2225]
The https://gohugo.io/functions/where/#use-where-with-boolean-values uses 
```
{{ range where .Pages "Draft" true}}
  <p>{{ .Title }}</p>
{{ end }}
```
I understand that in _this_ case, the `where` condition always returns `true` or `false` because `Draft` is a page variable/method/function (that perhaps returns returns `false` if the parameter is _not_ set at all in frontmatter). But what about user-defined parameters like 
```
---
…
exclude: true
---
```
What's the result for `where .Pages "Params.exclude" true` if the parameter is _not_ defined at all in the frontmatter? 

I suggest augmenting this part with an example that explains the behavior of `where` with defined and undefined booleans in the frontmatter. 

And then there is https://gohugo.io/functions/where/#unset-fields which says "Filtering only works for defined fields". Which seems irritating given the example in "Boolean values": If the field is _not_ set (i.e. absent in frontmatter), what does the example give?

**Comment by jmooring** [comment]
> Filtering only works for defined fields

Yeah, the whole page needs some love.
