### ISSUE TITLE
Hugo Showcase: Logo update for Digital.gov page

### ISSUE THREAD

**Issue by ToniBonittoGSA** [gohugoio/hugoDocs#2227]
Hello,

Our logo for Digital.gov was updated last year. Please use the attached to update this page: https://gohugo.io/showcase/digitalgov/ 

![DigitalGov-2022-logo-hugo-showcase](https://github.com/gohugoio/hugoDocs/assets/19961574/b86188ab-b28c-48de-a01f-06173f622231)

Thank you!

**Comment by jmooring** [comment]
Closed with https://github.com/gohugoio/hugoDocs/pull/2228
