### ISSUE TITLE
Let jsonify refer to unmarshal in "See also"

### ISSUE THREAD

**Issue by chrillek** [gohugoio/hugoDocs#2232]
The documentation of `jsonify` does not mention the inverse operation (`unmarshal`) in its "See also" section. Instead, it mentions "anchorite" and "emojify", which is of limited usefulness in this context.

**Comment by dryscord** [comment]
Seems those related topics are generated automatically

**Comment by chrillek** [comment]
Then maybe that's not always a good idea. The See also part should point to the relevant information, I think
