### ISSUE TITLE
Logging should be more promintent and documented

### ISSUE THREAD

**Issue by privatemaker** [gohugoio/hugoDocs#2315]
Perhaps I did not see it while scanning the docs (apologies if so 👀), but I saw no dedicated pages 
or sections about **logging** on the hugoDocs site.

Since debugging and logging are such important parts of development it seems this should be better documented, more prominent, and/or easier to find. 

1. HugoDocs has: [errorf page](https://gohugo.io/functions/fmt/errorf/)
2. HugoDocs (Chinese fork) has a different: [errorf page](https://hugo-docs.netlify.app/en/functions/errorf/) which mentions `warnf` which does exist (as of `v0.119.0`) and is helpful.
3. Hugo Discussions [asking for an infof command](https://discourse.gohugo.io/t/would-we-accept-a-pr-for-an-infof-template-function/35565/2) which exists somewhat in [the source code](https://github.com/search?q=repo%3Agohugoio%2Fhugo+infof&type=code), but is only an internal function that causes Hugo to fail if run with it, so I assume this is not existing.

To make the two functions easier to find in a logical grouping, I would suggest making a dedicated page called `Logging` which is located under the `Troubleshooting` section. I'll send a pull-req with this shortly.

**Comment by privatemaker** [comment]
@jmooring it was very clear to me what the "canonical documentation" was. By saying "Chinese fork" I was implying it **did not seem official.** My links relating to `infof` was for thoroughness about the scope of confusion in the community. Cool it's being worked on, thanks 😄 

I'm curious about the hugoDocs [contributor policy](https://github.com/gohugoio/hugoDocs#contributing), as per:

> We welcome contributions to Hugo of any kind including documentation, suggestions, bug reports, pull requests etc...  We would love to hear from you.

I assumed describing an issue, proposing a plan, and then submitting a simple pull-req, was a desired path for new contributors. Why did you open a new issue basically stating my proposed suggestion and say:

> Please do not submit a PR. Your request will be addressed in #2316

Are new contributors not welcome at this time?

**Comment by jmooring** [comment]
@privatemaker Regarding https://github.com/gohugoio/hugoDocs/issues/2316... I have a branch that includes this work, and I expect to merge it next week sometime. Another PR just generate merge conflicts. Please follow this issue, and feel free to comment or submit changes once I've merged the branch.
