### ISSUE TITLE
Add Versions to function documentation

### ISSUE THREAD

**Issue by cmahnke** [gohugoio/hugoDocs#2323]
With Hugo 0.120.0 I'll get a message regarding `.Site.IsServer`:
```
INFO  deprecated: .Site.IsServer was deprecated in Hugo v0.120.0 and will be removed in a future release. Use hugo.IsServer instead.
```

Since the is coming from one of my themes, I'd like to know since when the replacement `hugo.IsServer` is available to set the required min version in `theme.toml`.

My proposal is as follows:
Each function documentation page (like for [`hugo.IsServer`](https://gohugo.io/functions/hugo/isserver/)) should have a field `since` indicating the version in which a function has been introduced. The same goes for deprecated functions (or variables) like `.Site.IsServer`, they should't been [silently removed from the docs](https://github.com/gohugoio/hugoDocs/commit/e3ec2a4f20cae295597392f77becf119f6032b78), but marked as deprecated.

BTW: Maybe this issue need to be [moved](https://github.com/gohugoio/hugoDocs).

**Comment by jmooring** [comment]
New features in v0.120.0 are visually tagged with "New in v0.120.0". That is our common practice, but I inadvertently removed a couple of the tags with a recent change.

- <https://gohugo.io/functions/debug/timer/>
- <https://gohugo.io/functions/hugo/isdevelopment/>
- <https://gohugo.io/functions/hugo/isserver/>
- <https://gohugo.io/functions/images/padding/>

I've added a deprecation notice to the site methods deprecated in v0.120.0:

- <https://gohugo.io/methods/site/disqusshortname/>
- <https://gohugo.io/methods/site/googleanalytics/>
- <https://gohugo.io/methods/site/isdevelopment/>
- <https://gohugo.io/methods/site/isserver/>

Note that deprecated functions and methods will not appear in lists, including section menus. They will, however, appear in search results. You won't be able to search for them today. The search index will be updated in a few days... I'm guessing the pages will appear in the search results by 15 November 2023.

I added two new sections to the documentation guidelines:

- <https://gohugo.io/contribute/documentation/#deprecated-features>
- <https://gohugo.io/contribute/documentation/#new-features>

Our deprecation practice is described here:
<https://gohugo.io/troubleshooting/deprecation/>

**Comment by dongorgan** [comment]
@jmooring I suggest the deprecation warning to be placed at the start of the page.

**Comment by cmahnke** [comment]
@jmooring : Thanks for your fast response and work!
I guess that 6 + 6 minor version for `notice` and `warning` will be enough, since my themes are internal and under (more or less) constant development.

**Comment by hugo-sid** [comment]
This is a great initiative. Thanks for the work @jmooring.
