### ISSUE TITLE
Search for the whole doc and not just titles

### ISSUE THREAD

**Issue by pH142857** [gohugoio/hugoDocs#2335]
Hi, I'm new to Hugo and trying the make my way through the documentation. As far as I can tell, the search bar only allows me to look for strings in the docs titles. It's a bit limiting.
Could it be possible to make the search look through the whole docs instead of only the titles? Or is there a way to achieve this that I failed to see?

**Comment by jmooring** [comment]
> the search bar only allows me to look for strings in the docs titles

No, it doesn't.

![Screenshot-20231120102209-535x352](https://github.com/gohugoio/hugoDocs/assets/335669/e372c786-45c7-4604-9f33-70cb76c8cd11)

**Comment by pH142857** [comment]
Then I guess I just don't understand how the search results are selected or filtered. Maybe it only displays a certain number of results? For instance when I look for "posts", the page https://gohugo.io/content-management/organization/ doesn't come up, while it features the term "posts" a few times.

**Comment by pH142857** [comment]
Then I guess I just don't understand how the search results are selected or filtered. For instance when I look for "posts", the page https://gohugo.io/content-management/organization/ doesn't come up, while it features the term "posts" a few times.

 Maybe it only displays a certain number of results? In that case could this number be increased?
Thanks for the Google workaround.
