### ISSUE TITLE
gohugo.io blocked in Iran

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#237]
Not sure what we can do about it, but I'll create this issue to track it.

As reported by one user, who sounds like he knows what he is talking about:

> This has no problem https://discourse.gohugo.io. But https://gohugo.io can not be opened.

The first is hosted by discourse.com, the last address resolves to:

```
▶ nslookup 104.198.14.52
52.14.198.104.in-addr.arpa	name = 52.14.198.104.bc.googleusercontent.com.
```

Google search comes up with some old posts related to this:

https://www.theguardian.com/world/2012/sep/23/iran-block-access-google-gmail

Is this something that Netlify is aware of, @biilmann ?

**Comment by pouya-barzegar** [comment]
We also have this problem.
our group built a website with hugo, you can see it [here](http://shirazlug.gitlab.io/)
and we constantly need access to the documents. and the same issue really bothers us

**Comment by bep** [comment]
>and we constantly need access to the documents

Note that the Gohugo.io site is really easy to get up and running locally.

```bash
git clone https://github.com/gohugoio/hugoDocs.git
cd hugoDocs
hugo server
```

**Comment by nimabeh** [comment]
i think this issue is still going on. gheychi.net which is made with Hugo can't be accessed from users in Iran.
why would gohugo.io block Iran IPs?

**Comment by bep** [comment]
>why would gohugo.io block Iran IPs

We don't, but our hosting provider may be at fault (Netlify), but that is a little out of our control, I'm afraid.

**Comment by nimabeh** [comment]
true. just checked thats the same story when site is deployed on Netlify, Fleek and Render. but Hugo works fine on Github Pages.

**Comment by bep** [comment]
@nimabeh I'll reopen this, not sure that will help much towards fixing the problem, but we're at least making a statement.

**Comment by jmooring** [comment]
Not actionable.
