### ISSUE TITLE
Site Search Resources

### ISSUE THREAD

**Issue by gavinr** [gohugoio/hugoDocs#2376]
I really think we need to improve the "site search" story for Hugo. The [Search for your Hugo Website](https://gohugo.io/tools/search/) page is insufficient - there are too many half-baked options listed. Why not have a single, well-documented recommended setup? Here are a few specific issues but I'm really more interested in a holistic improvement of the "site search" story. 

- [GitHub Gist for Hugo Workflow](https://gist.github.com/sebz/efddfc8fdcb6b480f567) - this feels old - I realize that it's been updated over the years, but it's using Grunt which feels old in 2019 and I have to process through all the comments to figure out how to piece this solution together. Tough sell.
- https://www.npmjs.com/package/hugo-lunr - this is not maintained - last commit in 2016 and there are un-merged PRs
- Algolia - You have to create the records manually or figure out how to build hugo to push to the Algolia API?
    - I would propose we **remove Algolia from the recommended list** - in my experience as soon as you sign up for the free account you get bombarded by high-pressure sales tactics, contacting you via phone and even email addresses that they have found online that you did not give them. 
- [Bonsai](https://docs.bonsai.io/article/105-hugo) - part of the way there but I need to figure out how to push the data to Bonsai automatically

Thanks to the Hugo team for a quality product - I really appreciate it and am just trying to give some feedback to help future users.

**Comment by jmooring** [comment]
Closing in favor of https://github.com/gohugoio/hugoDocs/issues/1573
