### ISSUE TITLE
Changes required for v0.123.0

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugoDocs#2385]
#### 1\) :heavy_check_mark: <https://gohugo.io/methods/site/sites/>

See [gohugoio/hugo#11860](https://github.com/gohugoio/hugo/issues/11860). Change this:

> Returns a collection of all Site objects, one for each language, ordered by language weight.

to this:

> Returns a collection of all Site objects, one for each language, ordered by default content language then by language weight.

#### 2\) :heavy_check_mark: <https://gohugo.io/content-management/page-bundles/>

See [gohugoio/hugo#11439](https://github.com/gohugoio/hugo/issues/11439). Change this:

> Only in the directory level of the branch bundle directory i.e. the directory containing the _index.md ([ref](https://discourse.gohugo.io/t/question-about-content-folder-structure/11822/4?u=kaushalmodi)).

to this:

> At any directory level within the branch bundle directory.

#### 3\) :heavy_check_mark: <https://gohugo.io/methods/site/lastchange/>

See [gohugoio/hugo#11457](https://github.com/gohugoio/hugo/issues/11457). Mark as deprecated, add new page methods/site/lastmod.

#### 4\) :heavy_check_mark: <https://gohugo.io/methods/page/bundletype/>

`.Page.BundleType()` return type changed to `string` (the old internal string type is removed)

#### 5\) :heavy_check_mark: <https://gohugo.io/functions/data/getcsv/>

See <https://github.com/gohugoio/hugo/pull/11932>. Deprecate in favor of using page or global resources with transform.Unmarshal.

#### 6\) :heavy_check_mark: <https://gohugo.io/functions/data/getjson/>

See <https://github.com/gohugoio/hugo/pull/11932>. Deprecate in favor of using page or global resources with transform.Unmarshal.

#### 7\) :heavy_check_mark: New `fmt.Warnidf` function

See <https://github.com/gohugoio/hugo/pull/11940/commits/098a0ce0d3b22619603663184a7675e4a434d1a1>

#### 8\) :heavy_check_mark: Rename config `ignoreErrors` => `ignoreLogs`

See <https://github.com/gohugoio/hugo/pull/11940/commits/098a0ce0d3b22619603663184a7675e4a434d1a1>

#### 9\) :heavy_check_mark: <https://gohugo.io/templates/output-formats/>

See [gohugoio/hugo#11551](https://github.com/gohugoio/hugo/issues/11551).

See [gohugoio/hugo#8927](https://github.com/gohugoio/hugo/issues/8927).

#### 10\) :heavy_check_mark: <https://gohugo.io/troubleshooting/faq/>

See [gohugoio/hugo#11809](https://github.com/gohugoio/hugo/issues/11809).

#### 15\) :heavy_check_mark: Params key in front matter

- <https://gohugo.io/methods/page/param/>
- <https://gohugo.io/methods/page/params/>
- <https://gohugo.io/templates/introduction/#use-content-page-parameters>

When updating the front matter fields list, do not document the `kind`, `path`, or `lang` front matter fields at this time; they are for future use.

See:
- <https://github.com/gohugoio/hugo/pull/11934>
- <https://github.com/gohugoio/hugo/pull/11940>

#### 16\) :heavy_check_mark: Add something, somewhere about default render hooks

- See <https://github.com/gohugoio/hugo/issues/11933>.
- The existing render hooks page almost needs to be its own section, with one page for each type of render hook. There are default render hooks for images, links, and GoAT code blocks.
- Need to include Goldmark config for default link and image render hooks (how to enable).

```text
[markup.goldmark.renderHooks.image]
  enableDefault = false
[markup.goldmark.renderHooks.link]
  enableDefault = false
```

#### 17\) :heavy_check_mark: Remove/replace deprecated calls in github.com/gohugoio/gohugoioTheme

- `data.GetJSON`
- `.Page.Lang`

#### 18\) :heavy_check_mark: Remove deprecated calls from Hugo's built-in templates

<https://github.com/gohugoio/hugo/issues/11971>

#### 20\) :heavy_check_mark: https://gohugo.io/content-management/multilingual/#page-bundles

See https://github.com/gohugoio/hugo/issues/11453. For multilingual sites, "shared" page resources are no longer accessible via markdown link/image elements without render hooks designed for portability. 

Document:

```text
[markup.goldmark]
duplicateResourceFiles = false
```

**Comment by cmahnke** [comment]
Two additions:
* [Nil pointer error instead of warning when checking .File.Something without a backing file](https://github.com/gohugoio/hugo/issues/11956#top)
   Maybe as a part of a section o upgrading? (Related to 14?)
* [Consider _build vs build](https://github.com/gohugoio/hugo/issues/11970#top)
   What ever the final field name might be, there should be advice / convention like "_Avoid adding front matter fields starting with underscore_" or "_Avoid adding custom front matter fields, use the new params key instead_" (15)

**Comment by jmooring** [comment]
@cmahnke 

> Nil pointer error instead of warning when checking .File.Something without a backing file

This is no longer relevant with hugo v0.123.0-DEV-28733248 and later.

```text
Error: error building site: render: failed to render pages: render of "home" failed: "/home/jmooring/code/hugo-testing/layouts/_default/home.html:16:10": execute of template failed: template: _default/home.html:16:10: executing "main" – File is nil; wrap it in if or with: {{ with .File }}{{ .Path }}{{ end }}
```

> Consider _build vs build

Done.

![image](https://github.com/gohugoio/hugoDocs/assets/335669/b3735231-5a0e-40fa-b42f-ac9d80dd3580)
