### ISSUE TITLE
Old Ubuntu versions, incompatibilities with Hugo documentation

### ISSUE THREAD

**Issue by jensilo** [gohugoio/hugoDocs#2398]
Upfront, I'm on Ubuntu 22.04.3 LTS.

When following the installation guide for Debian (and Ubuntu) with apt, Hugo v0.92.2 is installed. Taking into consideration that we're currently at v0.121.2, v0.92.2 is very, very outdated. Yes, I am aware that this is not our (Hugo's) fault.

And yes, I am also aware that the docs state:
`Due to Long Term Release policies, some Linux package repositories will not contain the [latest release](https://github.com/gohugoio/hugo/releases/latest).`
However, this sounds quite soft, like: It might be that you're not surfing the bleeding edge but it'll be fine.

After all, I noticed, it is not at all fine. The rest of the docs - espacially the getting started guide - does not work or comply with this ancient version. E.g. the first part of the guide:
`hugo new site quickstart
cd quickstart
git init
git submodule add https://github.com/theNewDynamic/gohugo-theme-ananke.git themes/ananke
echo "theme = 'ananke'" >> hugo.toml
hugo server`

This will lead to (weird) behaviour when starting the server as the theme is defined in `hugo.toml` but v0.92 will create a `config.toml` instead and just ignore the `hugo.toml`. The error for the user is not really visible, no compilation errors or similar. Instead, the page will just render empty with warnings. Took me a while to figure out why that is. I had to first find out that this behaviour has changed and that I am on an ancient version. Sounds easy when you know but when you don't know it's quite frustrating.

Same goes for creating a new page with the default archetype, I don't quite now yet why that fails in the older version but I am sure it will work in a newer version:
`hugo new content posts/my-first-post.md`

This will lead to this error: `Error: failed to resolve "content" to a archetype template`.
Also quite frustrating when you have no clue that you're version is just very outdated.
And it's not just me noticing this: [Upgrading Hugo on Linux: A Step-by-Step Guide to Any Version You Need](https://rodneymaiato.dev/posts/how-to-install-a-different-version-of-hugo-in-linux-debian/).

I think the documentation should warn about this. Best on the installation page under the Debian section and(!) the getting started guide as this is where beginners usually begin. This would be much more accessible.

Again, I know this is of nobody's blame, espacially not the great team behind Hugo but I would highly appreciate if we could make the documentation and setup process even more accessible.

I'd also be up to make these changes but wanted to have some feedback on that first issue first.
Thanks and have a great day :)

**Comment by jmooring** [comment]
At the beginning of the quick start guide...

![hugo-installation-prerequisites](https://github.com/gohugoio/hugoDocs/assets/335669/7f4b7568-0abc-41a3-978f-79988dd396f3)

When users ignore this they will have problems. I'll give this some thought, but I'm leaning towards a simple "version verification" step before the "hugo new site..." commands. \

> Due to Long Term Release policies, some Linux package repositories will not contain the latest release.

This is not specific to Debian, but maybe we can add version verification instructions here as well. I'll give it some thought.

**Comment by jensilo** [comment]
> At the beginning of the quick start guide...

I saw that and I also know that

> When users ignore this they will have problems.

but I don't think that I'm stupider than the average user and ofcourse I should've seen the notice and checked my version beforehand. Somehow, I didn't and I guess many others won't either. That's definitely the user's (my) fault.

However, I think we could improve user-/beginner-friendliness and accessibility here, just give it a thought.
