### ISSUE TITLE
Change hugolib.pageState => page.Page

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#2406]
<img width="490" alt="image" src="https://github.com/gohugoio/hugoDocs/assets/394382/a83e8268-5f86-40bd-bb11-366251496765">

While the above is (mostly) technically correct, it isn't very user friendly. The return value of that method is the interface `page.Page`. which is one of 2 core interfaces in Hugo (the other being `resource.Resource`).

**Comment by jmooring** [comment]
Yeah, I had it on my list to make some of the return types more friendly, but I ran out of steam. I'll take care of this.
