### ISSUE TITLE
Lots of empty commit / bad merge from the Hugo docs tree

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#2449]
E.g. 1083bf7c08e6f35826279065b8a09a16cc991c7f

This is my mistake. Not sure what's happened (I suspect this happened when I deleted and recreated the docs sub tree in the hugo repo), and must have pushed these "orphan commits" when I released Monday.

I will have a look to see if I can find a Git magic command to fix this, but advice from some Git expert reading this would be appreciated.

/cc @jmooring

**Comment by bep** [comment]
@jmooring I stupidly deleted/recloned the docs repo thinking it was a "local issue". If you have a local version with some history, could you:

1. Do `git reflog` and find a commit that's Sunday or earlier and create a branch from that.
2. Push that branch to this repo.

Then I should be able to fix the rest and do a force push once the branches are functionally the same.

**Comment by jmooring** [comment]
@bep See https://github.com/gohugoio/hugoDocs/tree/for-bep

**Comment by bep** [comment]
@jmooring OK, I will fix this in the next few days. Thanks.

**Comment by jmooring** [comment]
@bep Is this resolved?

**Comment by bep** [comment]
No.

**Comment by bep** [comment]
@jmooring the trouble commits are these:

```bash
commit a8ad989c610e62d1038e14c73b323b41601db38e
Merge: fc7de7136 5c085a37b
Author: Bjørn Erik Pedersen <bjorn.erik.pedersen@gmail.com>
Date:   Sat Jan 27 10:48:33 2024 +0100

    Merge commit '9b0050e9aabe4be65c78ccf292a348f309d50ccd' as 'docs'

    ```
    git subtree add --prefix=docs/ https://github.com/gohugoio/hugoDocs.git master --squash
    ```

    Closes #11925

commit fc7de7136acbcf0aef54ae8460c7702bc83709be
Author: Bjørn Erik Pedersen <bjorn.erik.pedersen@gmail.com>
Date:   Sat Jan 27 10:47:28 2024 +0100

    docs: Prepare for new sub tree

    See #11925
```

I will try to fix the above in a separate branch now, but will add another "shout" to this PR before I'm doing any pushes. We need to fix this, and I don't think there's a way around a force push, but I will create a backup branch and double check  the diff before doing anything.

**Comment by bep** [comment]
@jmooring I need to push this for later ... the fix isn't obvious (to me, anyhow).

**Comment by jmooring** [comment]
Closing per <https://github.com/gohugoio/hugo/issues/12430#issuecomment-2076778159>
