### ISSUE TITLE
`.Date` in archetype templates appears to be a string instead of a time

### ISSUE THREAD

**Issue by akbyrd** [gohugoio/hugoDocs#2455]
According to the [documentation](https://gohugo.io/content-management/archetypes/#include-content), `.Date` inside an archetype template should be a time object. Instead, it appears to be evaluating to a string. I noticed this when attempting to use `{{ .Date.Format "..." }}` inside of an archetype template.

Steps to repro:
* Create archetypes/default.md
* Add `date = {{ .Date.Format "2006-01-02" }}`
* Create a new post
* Notice the error
    > Error: failed to execute archetype template: template: archetype.md:8:15: executing "archetype.md" at <.Date.Format>: can't evaluate field Format in type string: template: archetype.md:8:15: executing "archetype.md" at <.Date.Format>: can't evaluate field Format in type string
* Replace with `date = {{ (time.AsTime .Date).Format "2006-01-02" }}`
* Create a new post
* Notice no error

Hugo version: 0.123.3

**Comment by bep** [comment]
This is what's passed to the archetype template:

```go
type archetypeFileData struct {
	// The archetype content type, either given as --kind option or extracted
	// from the target path's section, i.e. "blog/mypost.md" will resolve to
	// "blog".
	Type string

	// The current date and time as a RFC3339 formatted string, suitable for use in front matter.
	Date string

	// The temporary page. Note that only the file path information is relevant at this stage.
	Page page.Page

	// File is the same as Page.File, embedded here for historic reasons.
	// TODO(bep) make this a method.
	*source.File
}
```

If the documentation says otherwise, the documentation needs to be updated.

Note that if you need the current date on another format, you can do `now.Format ...` etc.
