### ISSUE TITLE
Page bundle page states "no content files in home page bundle allowed" but hugo behaves different

### ISSUE THREAD

**Issue by irkode** [gohugoio/hugoDocs#2476]
The [Page Bundles](https://gohugo.io/content-management/organization/#page-bundles) page in the docs states that a home page bundle may not contain content files.

but hugo will accept that without any warning and error and generates the site.

looks like the candidate for [#2307]

tested with:
* hugo v0.123.7-312735366b20d64bd61bff8627f593749f86c964+extended windows/amd64 BuildDate=2024-03-01T16:16:06Z VendorInfo=gohugoio
* hugo v0.123.8-5fed9c591b694f314e5939548e11cc3dcb79a79c+extended windows/amd64 BuildDate=2024-03-07T13:14:42Z VendorInfo=gohugoio

[https://github.com/gohugoio/hugoDocs/blob/master/content/en/content-management/organization/index.md](https://github.com/gohugoio/hugoDocs/blob/master/content/en/content-management/organization/index.md)

> Page bundles
> Hugo 0.32 announced page-relative images and other resources packaged into Page Bundles.
> 
> These terms are connected, and you also need to read about [Page Resources](https://github.com/gohugoio/hugoDocs/blob/master/content-management/page-resources) and [Image Processing](https://github.com/gohugoio/hugoDocs/blob/master/content-management/image-processing) to get the full picture.
> 
> {{< imgproc "1-featured-content-bundles.png" "resize 300x" >}} The illustration shows three bundles. **Note that the home page bundle cannot contain other content pages, although other files (images etc.) are allowed.** {{< /imgproc >}}
> 

but it's not a problem to create content pages at the root level

Steps to reproduce and discussion on : [Discourse 48737](https://discourse.gohugo.io/t/home-page-bundle-may-contain-content-pages-but-the-documentation-states-its-not-allowed/48737)

**Comment by jmooring** [comment]
Thanks for the detailed report. I have included this in the TODO list for #2307.
