### ISSUE TITLE
Update docs vs templates and language

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#25]
See https://github.com/gohugoio/hugo/pull/3670

**Comment by jmooring** [comment]
This is covered by <https://gohugo.io/templates/lookup-order/#hugo-layouts-lookup-rules>

> **Language**
> We will consider a language code in the template name. If the site language is fr, index.fr.amp.html will win over index.amp.html, but index.amp.html will be chosen before index.fr.html.
