### ISSUE TITLE
Improve RSS feed

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugoDocs#2520]
Reference: <https://discourse.gohugo.io/t/rss-of-gohugo-io-website/49204>

- [ ] Remove feeds from all sections except for news and home.
- [x] Generate the news feed using the GitHub API[^1], same as we do for the news list page.
- [ ] Make the home page feed the same as the news feed.

Feeds such as <https://gohugo.io/functions/strings/index.xml> don't make sense to me.

[^1]: This was addressed with [#2521](https://github.com/gohugoio/hugoDocs/pull/2521). See <https://gohugo.io/news/index.xml>.

**Comment by davidsneighbour** [comment]
It was quite a while back when there was news. I remember posts about speed optimization that didn't make it into release notes. The "RSS feed" could be redirected to the Github release feed. Having a feed only for home (releases) and news (there is no pagination and the current news section shows only a list of releases) makes sense, if there are (or would be) news, if not, go down to one single feed. 

I think one feed with only releases makes sense.
