### ISSUE TITLE
Typo in documentation (BlackFriday option "extensionsmask")

### ISSUE THREAD

**Issue by itc-ger** [gohugoio/hugoDocs#253]
See [https://github.com/gohugoio/hugo/issues/4043](https://github.com/gohugoio/hugo/issues/4043)

Please correct :-)

**Comment by kaushalmodi** [comment]
Thanks for reporting this. I'll submit a PR soon with fixes.

>I guess the (purpose) description of extensionsmask should be:
>
>>Purpose: Disable one or more of Blackfriday’s Markdown extensions (if they aren’t Hugo defaults).
>>Enable -> Disable

Yes, will change that to disable.

>See also: purpose of option extensions:
>>Purpose: Enable one or more Blackfriday’s Markdown extensions (if they aren’t Hugo defaults).

I didn't follow that.

>Plus, maybe the Blackfriday flag has also to be altered to
>Blackfriday flag: EXTENSIONMASK_*
>EXTENSION_* to EXTENSIONMASK_* I guess

The `extensions` and `extensionsmask` are to enable and disable [Blackfriday extensions][1]. All extensions start with `EXTENSION_`.. there is no `EXTENSIONMASK_`. I'll try to clarify this.

[1]: https://github.com/russross/blackfriday/blob/067529f716f4c3f5e37c8c95ddd59df1007290ae/markdown.go

**Comment by kaushalmodi** [comment]
@itc-ger How does this look: https://59fcbea9a6188f09adf85874--gohugoio.netlify.com/getting-started/configuration/#configure-blackfriday ?
