### ISSUE TITLE
symbolic link references in Documentation obsolete?

### ISSUE THREAD

**Issue by irkode** [gohugoio/hugoDocs#2566]
I could swear I read somewhere that _symbolic link_ support is cancelled. (v123.0) https://github.com/gohugoio/hugo/issues/11556
and also failed to use a symbolic link link in within content

if so - there are still some references in the docs that needs to be handled

* [content/en/about/security.md](https://github.com/gohugoio/hugoDocs/blob/b608f3165b05a141576db0d8e396e42c5ee2c577/content/en/about/security.md?plain=1#L25):

  > `* Only the main project can walk symbolic links.`

  I would change that to:  `* Usage of symbolic links is not supported`

* [content/en/troubleshooting/audit/index.md](https://github.com/gohugoio/hugoDocs/blob/b608f3165b05a141576db0d8e396e42c5ee2c577/content/en/troubleshooting/audit/index.md?plain=1#L48)

  > <pre>
  > -r, --recursive
  > : Read all files under each directory, recursively, following symbolic links only if they are on the command line.  
  > </pre>

Dunno exactly, but I tink I would just remove ` following symbolic links only if they are on the command line`

* [content/en/hugo-modules/configuration.md](https://github.com/gohugoio/hugoDocs/blob/b608f3165b05a141576db0d8e396e42c5ee2c577/content/en/hugo-modules/configuration.md?plain=1#L150)

  > <pre>
  >source
  >: The source directory of the mount. For the main project, this can be either project-relative or absolute and
  > even a symbolic link. For other modules it must be project-relative.
  ></pre>

  I would remove `and even a symbolic link`

* [content/en/getting-started/directory-structure.md](https://github.com/gohugoio/hugoDocs/blob/b608f3165b05a141576db0d8e396e42c5ee2c577/content/en/getting-started/directory-structure.md?plain=1#L153)

  > If you think you need a symbolic link in your project directory, use Hugo's union file system instead.

  I would change that to `Symbolic links are not supported. If you need them consider using Hugo mounts and the union files system.`

I would raise a PR the changes are ok

**Comment by jmooring** [comment]
> I would change that to: * Usage of symbolic links is not supported

How about this instead? "Hugo does not follow symbolic links." That would make the wording consistent with the last item below.

> but I tink I would just remove  following symbolic links only if they are on the command line 

Leave as-is. The documentation is describing the grep flag, not a Hugo capability.

> I would remove and even a symbolic link

I agree.

> I would change that to Symbolic links are not supported. If you need them consider using Hugo mounts and the union files system.

How about this instead? "Hugo does not follow symbolic links. If you need the functionality provided by symbolic links, use Hugo's union file system instead."

**Comment by irkode** [comment]
too slow ;-)
