### ISSUE TITLE
Add RSS feed for news

### ISSUE THREAD

**Issue by anayrat** [gohugoio/hugoDocs#260]
Hello,

Is it possible to add a RSS feed for this page : https://gohugo.io/news/ ?

Thanks!

**Comment by bep** [comment]
https://gohugo.io/news/index.xml

**Comment by anayrat** [comment]
Thanks, but it seems it does not appear in headers?

**Comment by inwardmovement** [comment]
Thanks for the link, I was looking for it. 

I'd suggest it be displayed on the frontend view.
