### ISSUE TITLE
plainify doc doesn't say that it transforms chars into entities

### ISSUE THREAD

**Issue by willfaught** [gohugoio/hugoDocs#2600]
What I did:

```
{{ "Things <i>I've</i> done" | markdownify | plainify }}
```

What I got:

```
Things I&rsquo;ve done
```

What I expected:

```
Things I've done
```

I have to use htmlUnescape to undo the entity mangling:

```
{{ "Things <i>I've</i> done" | markdownify | plainify | htmlUnescape }}
```

Result:

```
Things I've done
```

This isn't clear from [the plainify doc](https://gohugo.io/functions/transform/plainify/):

>Returns a string with all HTML tags removed. [...]
>
>```{{ "<b>BatMan</b>" | plainify }} → BatMan```

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.126.1+extended darwin/arm64 BuildDate=2024-05-15T10:42:34Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by jmooring** [comment]
I find it helpful to take Go's html/template package out of the mix by printing to console.

With Hugo's default markdown configuration:

```text
{{ "Things <i>I've</i> done" | warnf "%v" }} → Things <i>I've</i> done
{{ "Things <i>I've</i> done" | plainify | warnf "%v" }} → Things I've done
{{ "Things <i>I've</i> done" | markdownify | warnf "%v" }} → Things <!-- raw HTML omitted -->I&rsquo;ve<!-- raw HTML omitted --> done
{{ "Things <i>I've</i> done" | markdownify | plainify | warnf "%v" }} → Things I&rsquo;ve done
```

So plainify isn't transforming the character... markdownify is, and that's due to the typographer extension being enabled by default.
