### ISSUE TITLE
Document Pager methods in methods section

### ISSUE THREAD

**Issue by willfaught** [gohugoio/hugoDocs#2612]
<img width="1027" alt="Screenshot 2024-06-07 at 12 56 35 PM" src="https://github.com/gohugoio/hugoDocs/assets/63830/2315b6af-c1ab-4d94-9dfc-bb4246d31c6a">

**Comment by jmooring** [comment]
Yeah, I've got a long-standing item on my todo list for this. Need to add a Pager section to document each of the Pager methods, including PageGroups. These are currently documented [here](https://gohugo.io/templates/pagination/), but PageGroups is buried (difficult to find and easy to miss).
