### ISSUE TITLE
Unclear how i18n (lang.Translate) determines the target language

### ISSUE THREAD

**Issue by xlsigned** [gohugoio/hugoDocs#2619]
When I use `{{ i18n "key" }}` in a template, there appears to be no way to change/set the target language. E. g. if `$page` is a translated page (from `$.AllTranslations`), neither

```
{{ with $page }}
   {{ i18n "key" }}
{{ end }}
```

nor

```
{{ i18n "key" $page }}
```

has any effect on the target language, while `{{ $page.Content }}` clearly shows that I have indeed looked up a translated page.

The documentation should state how (or rather when) the language is determined and what the optional parameter `[CONTEXT]` actually means and if it is at all possible to change the target language within a template.

---

The scenario is a **Multilingual Site** where I want language specific pages that are still incomplete to show the content of the default language (or any other language).

For this I'm using a custom frontmatter value in the incomplete page which triggers the fallback when set, i. e. the template looks up the already completed/translated (default) $page and calls `{{ $page.Content }}` instead of `{{ .Content }}`.

**Comment by jmooring** [comment]
Thanks for logging this.

I'll add an admonition to <https://gohugo.io/functions/lang/translate/> making it clear that the target language (a) is determined by `Page.Language.Lang` and (b) cannot be changed.

I'll also add a section heading named "Context" to describe usage of the optional second argument. There are some examples of this on the page already, but they should be in their section to make it clearer.

**Comment by jmooring** [comment]
We are not changing the name of the second argument. `CONTEXT` may be a number or a map, as described in the examples:

i18n/en.toml

```text
[age]
  one = '{{ .name }} is {{ .count }} year old.'
  other = '{{ .name }} is {{ .count }} years old.'
```

template

```text
{{ T "age" (dict "name" "Will" "count" 1) }} → Will is 1 year old.
{{ T "age" (dict "name" "John" "count" 3) }} → John is 3 years old.
```

The `CONTEXT` argument is in no way related to the current value of the dot in a template. This documentation has been in place for a very long time, and this is the first time someone has been confused by the argument name. We can revisit if the issue comes up again.

**Comment by xlsigned** [comment]
Honestly, this is rather surprising. I'd thought to most people `CONTEXT` would mean [context](https://gohugo.io/templates/introduction/#context) aka **the dot**.

If improving the documentation requires a higher number of **confused user reports**, so be it.
