### ISSUE TITLE
docs typo: hugo new content posts/my-first-post.md

### ISSUE THREAD

**Issue by jakegatsby** [gohugoio/hugoDocs#2624]
I believe there is a typo on the https://gohugo.io/getting-started/quick-start/ page for "Add content":

```
hugo new content posts/my-first-post.md
```

I don't think the `content` arg is supposed to be there, and the command should be:

```
hugo new posts/my-first-post.md
```

**Comment by jmooring** [comment]
All of these work with v0.112.0 or later, which is why the quick start guide requires v0.112.0 or later.

```text
hugo new content content/posts/foo.md
hugo new content posts/foo.md
hugo new content/posts/foo.md
hugo new posts/foo.md
```

We currently don't require the "content" subcommand; this provides backward compatibility. The "content" subcommand was added in v0.112.0.
