### ISSUE TITLE
Build to docs directory broken

### ISSUE THREAD

**Issue by uberdave** [gohugoio/hugoDocs#265]
![issue](https://user-images.githubusercontent.com/3323239/32945916-e690f6b4-cb5a-11e7-81f2-d01fb408bed9.png)

**Comment by kaushalmodi** [comment]
You haven't provided enough information to help you with your problem (what build? site repo? why post this in hugoDocs repo? etc..). Also such issues are better discussed at https://discourse.gohugo.io/.
