### ISSUE TITLE
Change the wording for hugo config file name

### ISSUE THREAD

**Issue by yaardie** [gohugoio/hugoDocs#2651]
I think this should be more 'explicit' https://gohugo.io/getting-started/configuration/#configuration-file

>With v0.109.0 and earlier the basename of the site configuration file was config instead of hugo. You can use either, but should transition to the new naming convention when practical.

Something like

>With v0.109.0 and earlier the basename of the site configuration file was config instead of hugo. You should transition to the new naming convention for newer versions of Hugo.

**Comment by jmooring** [comment]
I think the existing text is sufficient and more accurate.

**Comment by yaardie** [comment]
> You can use either

Then I don't understand why the renaming was done if it is optional. Anyway, your choice. I went back to config myself.
