### ISSUE TITLE
Docs are missing documentation for configuration setting _paginate = NN_

### ISSUE THREAD

**Issue by irkode** [gohugoio/hugoDocs#2652]
There are some references that there's something configured in the configuration file. But without any details and the effect.

seems setting `paginate = NN` affects both `.Paginate` and `.Paginator`. 

### https://gohugo.io/methods/page/paginate/ 

> By default, the number of elements on each pager is determined by your [site configuration](https://gohugo.io/getting-started/configuration/#pagination). The default is 10.

### https://gohugo.io/methods/page/paginator/

> The number of elements on each pager is determined by your [site configuration](https://gohugo.io/getting-started/configuration/#pagination). The default is 10.

Both then link to the pagination configuration which only lists `PagerSize`
I would have expected to have that in "All Configuration Settings" 

Its defined in the docs repo at 
* .hugo_toml_schema.json (line 2619) - incl a non existing  anchor-link 
   ```json
    "paginate": {
      "description": "The default number of elements per page in pagination\nhttps://gohugo.io/getting-started/configuration/#paginate",
      "type": "integer",
      "default": 10
    },
    "paginatePath": {
      "description": "The path element used during pagination\nhttps://gohugo.io/getting-started/configuration/#paginatepath",
      "type": "string",
      "default": "page",
      "minLength": 1
    },
     ```
* docs.yaml (line 1598) 
   ```yaml
  paginate: 0
  paginatePath: ""
   ```

**Comment by bep** [comment]
```
paginate: 0
paginatePath: ""
```

The two above was replaced by a `pagination` struct a while ago so they're deprecated and undocumented. 

See https://gohugo.io/getting-started/configuration/#pagination

**Comment by irkode** [comment]
thought like so ;-)

please keep in mind that there are a lot of old sites out there and the number grows. and it's hard to find "vanished" stuff. In some cases things are removed, others not, no deprecation warning when building - 

for paginate it just works like a charm.

I found no (easy) way to find out deprecated/removed methods and matching version.

Did I oversee some docs / notes - is there an option. 

If not we could consider to build a list listing deprecated remoed stuff per version.

On the long run people will ignore such message if everything works - and I would consider the contained code "technical dept"
