### ISSUE TITLE
"RegularPages" docs don't define what "regular" means

### ISSUE THREAD

**Issue by jmhodges** [gohugoio/hugoDocs#2656]
(This is a documentation bug for what's live on gohugo.io, so there's no version info to provide)

The page https://gohugo.io/methods/site/regularpages/ doesn't actually define what a "regular" page is. It merely uses the word "regular" repeatedly. It's also unclear why you should use this rather than other pages.

**Comment by bep** [comment]
It's defined here, but it should maybe have more links to it:

https://gohugo.io/getting-started/glossary/#regular-page

**Comment by jmhodges** [comment]
That may feel explanatory to other experts, but I'm still at a loss when I click that glossary entry and its further links in it. I have no idea what "'page' page kind" is.

**Comment by bep** [comment]
@jmhodges if you follow the links you get to this page: https://gohugo.io/methods/page/kind/

I think we do a pretty good of explaining it.
