### ISSUE TITLE
Add sponsor-section

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#269]
I open issue here; easier to make the changes here and then port it to the theme.

* Add to the footer and "somewhere" on the home page. A little subtle and not too big.
* See my mockup below. I want some placeholders to indicate that there is room for two more.

![image](https://user-images.githubusercontent.com/394382/33136299-2a182774-cfa5-11e7-8cc9-ec8813e740f6.png)

**Comment by budparr** [comment]
Are you set on the dark background? Most logos sit pretty easily on light backgrounds.

**Comment by bep** [comment]
>Are you set on the dark background? Most logos sit pretty easily on light backgrounds.

No. That was just the example that Scott sent me. My main point with my mockup was the placeholders.

/cc @scottgallant

**Comment by bep** [comment]
But note that that strip of banners will **also** have to look good in the footer, which is dark.
