### ISSUE TITLE
Add a note about context when using `.RenderString`

### ISSUE THREAD

**Issue by scopartu** [gohugoio/hugoDocs#2707]
Like the need for `.Page.RenderString` or `$.Page.RenderString` or even `page.RenderString`.

Affected URL: https://gohugo.io/methods/page/renderstring/

**Comment by jmooring** [comment]
You must be aware of context for all templates, methods, `with` blocks, and `range` blocks. The need for context awareness is not limited to the `RenderString` method.

This topic is covered in detail here:
<https://gohugo.io/templates/introduction/#context>
