### ISSUE TITLE
Please mention the breaking changes made to the summary feature in the documentation.

### ISSUE THREAD

**Issue by ajbuz** [gohugoio/hugoDocs#2734]
I just spent >6 hours debugging why automatic summary wasn't working properly after upgrading hugo from 129 to 135. 
![image](https://github.com/user-attachments/assets/b1c16187-4500-460f-af08-620da79a14e5)
 
This change was not mentioned anywhere in the documentation.
- [methods.page.summary](https://gohugo.io/methods/page/summary/)
- [automatic summary](https://gohugo.io/content-management/summaries/#automatic-summary)

All I could see is that the example was changed
![image](https://github.com/user-attachments/assets/bc58c9f7-c5b8-4631-9606-13216fb01646)

This change also seems work `summaryLength`  differently, i had to change my code from 
```hugo
{{- .Summary -}}
```  
to 
```hugo
{{- .Summary | plainify | strings.Truncate $count -}}
```

**Comment by jmooring** [comment]
Changes, including breaking changes, are handled in the release notes.
