### ISSUE TITLE
Editing content with math sometimes reloads a blank page in Chrome

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#2745]
I create this issue mostly to avoid having people creating a bug in Hugo about this. 

* It does not happen in Safari
* It does happen in Brave and Chrome (on MacOS), but not if I turn off the cache in dev console.

We have some logic in there for the pages where we use client side math where we hide the body on and then show it when the math is ready.

We should probably replace this with using the recently added server side math function?

**Comment by jmooring** [comment]
> We should probably replace this with using the recently added server side math function?

I've been thinking about this for a few days. Currently, the [Mathematics in Markdown](https://gohugo.io/content-management/mathematics/) page describes client side rendering. It seems misleading to use the transform.ToMath function to show examples on this page. Instead, I'm thinking of removing the workaround we implemented to address the FOUC. That way browser rendering of the current documentation will match what users will see when they implement this themselves.

Let me know if you have a strong opinion about this.

**Comment by bep** [comment]
> I'm thinking of removing the workaround we implemented to address the FOUC. 

Yea, that sounds OK.
