### ISSUE TITLE
Mention language negotiation in the documentation about Multilanguage mode

### ISSUE THREAD

**Issue by FiableDotBiz** [gohugoio/hugoDocs#2748]
I suggest to explain in page "[Multilanguage mode](https://gohugo.io/content-management/multilingual)" what language negotiation is, to say that it requires (as far as I understand) to choose "Translation by file name" and to provide links to explanations about language negotiation configurations in the main web servers (For Apache, it's [here](https://httpd.apache.org/docs/2.4/content-negotiation.html)) and to give all useful information to configure at least Nginx and Apache to get language negotiation for a Hugo site.

**Comment by jmooring** [comment]
This belongs in a Tips and Tricks article in the [forum](https://discourse.gohugo.io/) (feel free to create one). If it gets any traction we can consider adding something to the documentation.
