### ISSUE TITLE
mermaid works for some content only

### ISSUE THREAD

**Issue by king-11** [gohugoio/hugoDocs#2751]
hugo version: 0.118.0
theme: [hugo-PaperMod](https://github.com/adityatelange/hugo-PaperMod)

I had a working mermaid integration as per the [docs](https://gohugo.io/templates/partial/) but recently for a new content [file](https://github.com/king-11/blog/blob/main/content/posts/cloudflare-integration/index.md?plain=1) I started missing it out.

Mermaid is loaded in dev server if `disableFastRender` isn't used with
```bash
pkgx hugo@0.118.0 server -w
```

layouts defined:
- [render-codeblock-mermaid](https://github.com/king-11/blog/blob/main/layouts/_default/_markup/render-codeblock-mermaid.html)
```html
<pre class="mermaid" align="center">
  {{- .Inner | safeHTML }}
</pre>
{{ .Page.Store.Set "hasMermaid" true }}
```
- [extend_head](https://github.com/king-11/blog/blob/main/layouts/partials/extend_head.html)
```html
{{ if .Page.Store.Get "hasMermaid" }}
<script async type="module">
  var theme = localStorage.getItem("pref-theme") === "dark" ? 'neutral' : 'base';
  import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11.3.0/dist/mermaid.esm.min.mjs';
  mermaid.initialize({
    startOnLoad: true,
    'theme': theme,
  });
</script>
{{ end }}
```

i don't think is related but just for completness the [config](https://github.com/king-11/blog/blob/main/config.yml)

Mermaid is loaded on all other content files for [example](https://github.com/king-11/blog/blob/main/content/posts/process-management.md?plain=1)

I am not able to figure out the reason for the same and have tried looking up options for now what I have done is include an explicit param in frontmatter with or condition. So the issue seems to be around Page.Store set and get.

I validated things by running
```bash
pkgx hugo@0.118.0 --minify --baseURL localhost:7000
python -m http.server -d public 7000
```

the mermaid head isn't included in new content but is included for the other example.

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting.

**Comment by king-11** [comment]
I think this is related to how code blocks or store works in the system because I have done troubleshooting on my hence such a long issue 😅
