### ISSUE TITLE
question about license

### ISSUE THREAD

**Issue by genisaban** [gohugoio/hugoDocs#277]
hey, 

I find this theme great and it's also apache licensed,

Where did we get the home page icons from ? such [icon-fast.svg](https://github.com/gohugoio/hugoDocs/blob/master/themes/gohugoioTheme/static/images/icon-fast.svg), what is the license of these icons?

Thanks

**Comment by digitalcraftsman** [comment]
I guess @budparr made them himself while redesigning the Hugo website. He should know more about it :)

**Comment by budparr** [comment]
Hi @genisaban I contributed the icons from my Noun Project account, from which there is a perpetual, non-exclusive, worldwide right to use each icon.

**Comment by asaf** [comment]
Awesome thanks guys
