### ISSUE TITLE
Document permalinks custom date formats

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#2782]
I saw some related discussion in the forum, but I don't see the custom permalinks format handling mentioned here:

https://gohugo.io/content-management/urls/#tokens

According to one of our tests:

```
/:2006_01_02_15_04_05.000 => /2012_04_06_03_01_59.000
```

**Comment by jmooring** [comment]
If I understand your suggestion, I think we handle it here:

![image](https://github.com/user-attachments/assets/03c168a3-f24d-4120-8c84-af116ad2cf63)

**Comment by bep** [comment]
Yea, OK, I didn't see that.
