### ISSUE TITLE
Extend anchor ID link to h3 elements

### ISSUE THREAD

**Issue by maiki** [gohugoio/hugoDocs#286]
Took me a little while to figure out where this was coming from, but I believe it is the JS at   [`hugoDocs/themes/gohugoioTheme/src/js/anchorforid.js`](https://github.com/gohugoio/hugoDocs/blob/master/themes/gohugoioTheme/src/js/anchorforid.js) that sets those cool copyable "links" on h2 elements.

![screenshot-2017-12-18 front matter](https://user-images.githubusercontent.com/74557/34140995-41d16d74-e433-11e7-88cd-5c18a6af41d4.png)

As is obvious, it is a pain to otherwise get the anchor URL for a heading, and I find myself constantly wanting to link to an `h3` element. I haven't needed to link to an `h4` or lower.

Could we extend that linking to `h3`? I'd submit a patch, but I don't know JS.

**Comment by kaushalmodi** [comment]
The fix seems to be simple enough.. just change `level <= 2` to something like `level <= 4` [here][1]. Then, we will get anchor links up to `h4` tag.

Are there any issues in doing so? @bep? @budparr? 

[1]: https://github.com/gohugoio/gohugoioTheme/blob/e0ad9f32a1f0fe6cd1d7f38b71533d9befdce5f7/src/js/anchorforid.js#L30

**Comment by kaushalmodi** [comment]
Fixed in https://github.com/gohugoio/hugoDocs/commit/7ae9cf2ccb3eecc1ff50f686925249d01cf37c6c.
