### ISSUE TITLE
html content not recognised

### ISSUE THREAD

**Issue by githubgnulinux** [gohugoio/hugoDocs#290]
As requested, bug posted here, from:

https://github.com/gohugoio/hugo/issues/4194

**Comment by githubgnulinux** [comment]
The bug has been closed and the discourse web site does not show the html content, shown below

+++
title = "test"
date = "2017-12-29T12:15:02-00:00"
categories = [“test”]
tags = [“test”]
layout = “hyde-master”
+++
<!DOCTYPE HTML>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		</head>
	<body>
	<h1>
		Welcome
	</h1>
		<p>
			test html content
		</p>
	</body>
</html>

**Comment by githubgnulinux** [comment]
+++
title = "test"
date = "2017-12-29T12:15:02-00:00"
categories = [“test”]
tags = [“test”]
layout = “hyde-master”
+++
<pre>
<!DOCTYPE HTML>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		</head>
	<body>
	<h1>
		Welcome
	</h1>
		<p>
			test html content
		</p>
	</body>
</html>
</pre>

**Comment by githubgnulinux** [comment]
`+++
title = "test"
date = "2017-12-29T12:15:02-00:00"
categories = [“test”]
tags = [“test”]
layout = “hyde-master”
+++
<!DOCTYPE HTML>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		</head>
	<body>
	<h1>
		Welcome
	</h1>
		<p>
			test html content
		</p>
	</body>
</html>
`

**Comment by githubgnulinux** [comment]
unable to show html code! Why not?

**Comment by bep** [comment]
Take this on the discussion forum.
