### ISSUE TITLE
Update ref/relref documentation about optional extensions

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugoDocs#307]
Update the `ref`/`relref` documentation with:

- Mention that the extension portion of the document name is optional. 
- Once v0.35 is released, also document the feature requested in https://github.com/gohugoio/hugo/issues/4312.. Now the index.?? portion for page bundles is optional too.

**Comment by bep** [comment]
I suggest waiting for 0.35 and make a "overhaul" of this.

**Comment by Jibec** [comment]
I would love to see this included in documentation, this is vital for internal links while and multilingual site, so the link is language agnostic!

**Comment by kaushalmodi** [comment]
- [ ] Clarify that `ref` and `relref` can be used to link only regular pages (not section pages, taxonomy pages, etc.) ([ref][1])

[1]: https://discourse.gohugo.io/t/linking-to-the-index-page-for-a-section/10427?u=kaushalmodi

**Comment by jmooring** [comment]
This was resolved on September 5, 2020 with https://github.com/gohugoio/hugoDocs/pull/1213.

Note that these statements were removed from the documentation because they are no longer true:

> ref looks up Hugo “Regular Pages” only. It can’t be used for the homepage, section pages, etc.

> relref looks up Hugo “Regular Pages” only. It can’t be used for the homepage, section pages, etc.
