### ISSUE TITLE
Add Showcase

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#322]
Work branch: 

* https://github.com/gohugoio/hugoDocs/tree/next
* https://next--gohugoio.netlify.com/

Let us finish it in this issue.

**Comment by bep** [comment]
@budparr I have refactored it to use bundles and image resources. There are probably some more small items on that list (I'm not sure about the image sizes, but I have to say that the new image API in Hugo is a pleasure to use -- just have to remember running `hugo --gc` before committing to Git).

On my TODO list:

* Add some simple metadata (title) to the featured image
* Complete the creator etc. data model
* On a slightly unrelated topic, I think we need a "global RSS feed" with news+showcase. I guess we can add a RSS template to home page. That way we can release the showcases a little-by-little and make it news items on the Twitter feed etc. (undraft them).

There is some "funkynes" on the single page that you could look at:

* The prev-next looks ... odd?
* When there are content (https://next--gohugoio.netlify.com/showcase/esolia/) it looks a little untidy. It will probably help with more text/paragraphs, but maybe the featured image should be integrated better with the text? Not sure.

**Comment by bep** [comment]
Also:

The list page only shows the first item on mobile:

https://next--gohugoio.netlify.com/showcase/

**Comment by budparr** [comment]
> The list page only shows the first item on mobile:

I'm guessing that's an issue with lazyload. I'll have a look when I do the rest.

**Comment by bep** [comment]
@spf13 could you share your thoughts on this, you are way better in this area than me ...

When we get technical stuff working, I was thinking that instead of just publishing a set of screenshot we could

1. Ask the site owners to tell/write a little story about the site. Some self-advertising would be fine, but it should at least mention Hugo ...
2. Then publish/updraft those one by one and make it a "news item".

I think I will reach out to the paceup.com CEO, as he has shown great interest in Hugo and that site is both multilingual and uses all the new features.

I'm assuming that some will not bother to take the time to respond, so we will eventually just post the screenshot with a link etc. ...

What do you think?

Also, what kind of metadata model would be natural to ask them to fill out (most of them being optional)?

**Comment by DirtyF** [comment]
@bep you mean like http://www.trysmudford.com/perfomance-wins-with-hugo-and-netlify/ ? 😉

**Comment by bep** [comment]
@DirtyF exactly; in that case I would ask the author if we could cross-post that same article. But I would settle for less; the most important part (in most cases) is to show to people that the site is built with Hugo.

**Comment by budparr** [comment]
@bep I fixed the issue with the list page bonking on mobile. I improved(?) the styling of the prev/next buttons.

However, I'm not sure how the new image processing works, but they look horrible now. The images are pixelated, and on single pages they don't take up the full width of the space. 

I fooled around with them a bit, taking the height out and making them wider, which fixed one problem but the quality issue remained, so I left it as I don't understand what's making them so bad. 

Perhaps you can point me in the right direction, or since you kind of took over my work on this anyway, you might just want to fix it yourself. Let me know as I'm happy to help how I can.

**Comment by bep** [comment]
>since you kind of took over my work on this anyway, you might just want to fix it yourself.

This is a collaborative project. Using bundles/resources for this was the obvious choice, even if you only take the "eat your own dog food" argument into account. I will look at the "quality" issues. Not sure why they need to take up the "full width of the space", though. They are not that interesting.

**Comment by budparr** [comment]
Indeed it is. I figure since you broke the images, you might want to fix them. At any rate, I can make the column for the images (on single layout) smaller. That's not a problem and makes perfect sense. I think they should be a bit larger than the listing page, but can be smaller than they are now.

**Comment by bep** [comment]
>Indeed it is. I figure since you broke the images, you might want to fix them. 

I will have a look at it tomorrow.

**Comment by budparr** [comment]
I made the layout on large screens three columns, and moved the prev/next functionality to a list of the latest 20 showcase sites (with an optional link back to the showcase page when the list is longer than that). I think that makes the image size more reasonable and makes for a better user experience, because users than can then sift through the list rather than go one at a time. Let me know what you think. I also gave the details

Here's an example:


<img width="1438" alt="screen shot 2018-02-05 at 9 16 40 am" src="https://user-images.githubusercontent.com/115347/35809170-dd48ebf4-0a55-11e8-8433-e11d10b0a867.png">


I may tweak this still, particularly on mobile.

p.s. I'm seeing odd behavior with intermittent errors that hit once and go away on the next save. I can file this later, but thought it might be obvious to you or helpful in the image quality issue.
```
error processing shortcode "_internal/shortcodes/relref.html" for page "content-management/image-processing/index.md": template: _internal/shortcodes/relref.html:1:76: executing "_internal/shortcodes/relref.html" at <relref .Page (.Get 0...>: error calling relref: No page found with path or logical name "content-management/organization".
```

**Comment by budparr** [comment]
I was just thinking we should add a page with submission guidelines and instructions to include minimum amount of data, as well as image criteria. If so, I think it should live as a page in documentation (under "contribute") with a link from the showcase page.

**Comment by bep** [comment]
I have done some stuff:

* Redone some of the images (garbage in ...), set a different scaling filter as default, proper size in CSS etc. They look fine on my Retina; if the still look bad on your screen. @kaushalmodi @regisphilibert do you see "bad images"? See the showcase images: https://next--gohugoio.netlify.com/ https://next--gohugoio.netlify.com/showcase/ https://next--gohugoio.netlify.com/showcase/forestry/
* I agree about the "standard image" size. For the new screenshots I took, I did them in PNG at 1400x700; 2:1 ratio seems to be good for sharing. 

As to the metadata, I have thought a little, and it is hopeless to come up with a common and good set. So I have:

* Limited the front matter params to `siteURL`, `siteSource` (and `description`)
* Added an `bio.md` page where they can write the rest freely in markdown. See https://next--gohugoio.netlify.com/showcase/forestry/

One last thing:

I'm not totally sold on the left side navigation. The focus should really be on the _site in question_ Let's think about it a little.

**Comment by bep** [comment]
I added some dummy cotntent to some of the pages, and now the side nav looks balanced and good:

https://next--gohugoio.netlify.com/showcase/forestry/

If we can agree on the image size(s), this looks good.

I see from the theme site: "Screenshot should be 1500×1000 in pixels"

And that is probably better ratio for screen shots...?

**Comment by bep** [comment]
@budparr the error you got suggests you need to upgrade to a newer Hugo version. Which also explain other issues ...

**Comment by budparr** [comment]
I was on the latest available in Brew. 0.35. But apologies If I accused you of bonking the images when it was just my Hugo version. 

I think the screenshot is fine.

I think the side nav is not visually wonderful, but practical in that I believe the user would want to sift through the showcase and it makes for easy browsing.

**Comment by budparr** [comment]
In fact, just thinking out loud here: Perhaps when someone lands on the Showcase list page, they should land on the latest showcase item, rather than the list, and then they can sift through from there. Thoughts?

**Comment by bep** [comment]
>I was on the latest available in Brew. 0.35. 

The error you got suggests Hugo < 0.35.

**Comment by bep** [comment]
> land on the latest showcase item, rather than the list, and then they can sift through from there. Thoughts?

Hmm... The thing is, I think the list page looks really good, so ...

There are a couple of entry points here:

* Announcements of the single page on Twitter etc.
* RSS feed
* Front page

All of those go to the "single page".

**Comment by budparr** [comment]
Yeah, but my thinking here is the purpose of the showcase. The user story  (at least of our most critical user) is someone who wants some "social proof" to either convince themselves, or convince their boss that Hugo is a good choice. I want them to be able to hone in on the right showcase item for them. I think the nice-looking landing page wastes their time.

**Comment by bep** [comment]
But if we want site owners to spend time on writing an "article", it should get proper focus.

**Comment by budparr** [comment]
Well having the landing page as the latest showcase item puts even more focus on their article, no? I mean if you have a landing page with a bunch of images a fairly high percentage of users are never even going to click through.

**Comment by bep** [comment]
But I'm not sure. Will think a little.

**Comment by budparr** [comment]
- [ ] Add a slight border around showcase images on single page (some blend in to the background)

**Comment by bep** [comment]
What I think will work and be a good balance is to move the left showcase list/menu on the single page below the right "bio-box". And just leave the left column blank. That way the focus is on the content/site. In some cases (long bios), it may even drop out of sight, but that is fine.

**Comment by bep** [comment]
Oh, and just do your edits directly in the `next` branch. Much easier to work that way. Mistakes can be fixed/rolled back.

**Comment by budparr** [comment]
In that case, I'd just go back to the prev/next buttons and make the center column wider again to fill some of that space.

**Comment by bep** [comment]
That makes a very wide column on big screens ... Why not pull the title into the center column? And let the space be ... space.

**Comment by budparr** [comment]
That's fine. Maybe a bit wider.

**Comment by budparr** [comment]
Also, again thinking aloud, we could put the details on the left and the nav list on the right.

**Comment by bep** [comment]
>Also, again thinking aloud, we could put the details on the left and the nav list on the right.

Yes, that may fix it. I think the main problem with the menu is that my eye focuses on it.

**Comment by DirtyF** [comment]
Aim for a [Z pattern](https://uxplanet.org/z-shaped-pattern-for-reading-web-content-ce1135f92f1c) with  showcase title > showcase detail > showcase navigation.

**Comment by budparr** [comment]
So, I'll try that and push it up for you to see.

**Comment by budparr** [comment]
Have to run to work, so could be a couple of hours.

**Comment by regisphilibert** [comment]
Jumping a bit late on the thread. 
> @kaushalmodi @regisphilibert do you see "bad images"? 

What are we looking for here?

**Comment by regisphilibert** [comment]
I might suggestion throwing more columns on larger screen for the showcase grid. 3 ?

**Comment by bep** [comment]
@regisphilibert I think the problem was that @budparr tried to build the site with, like, Hugo 0.12 (:-)) and expecting image processing etc. to work.

But you can take a look at the  showcase images down on the main page https://next--gohugoio.netlify.com/  and on https://next--gohugoio.netlify.com/showcase/ https://next--gohugoio.netlify.com/showcase/forestry/ -- and tell us if it looks OK in the quality department.

**Comment by bep** [comment]
@budparr one more related thing you can try that I think will also improve the balance. If you drop the h1-title and make the linktitle in the bio-box slightly bigger.

**Comment by regisphilibert** [comment]
Might be interesting to add a `<picture>` element in there to better manage image resource by viewport. no need to load a 910px on mobile. Super easy now that we have .Resize. 
Remember me mentioning it a discourse thread ?
I can see the images are 910px wide but do we ever serve them at this size? Max seems to be 736 ?

As for they images, they look good on my retina as well, but it's a 13inch. I can see

**Comment by bep** [comment]
@regisphilibert I asked for a binary answer ... But thanks. We will have a look at the viewport vs mobile; we may as well do this according to best practice when we're spending time on this. And we can port that knowledge to the theme site, which needs something like this badly.

**Comment by regisphilibert** [comment]
> @regisphilibert I asked for a binary answer 

Like you could ever get something like that from me 😉

**Comment by kaushalmodi** [comment]
@bep 

I definitely see an improvement in the image quality. 

In the production gohugo.io, at the moment, the images look too "pixelly". Notice the "S"s in *HEADLESS* and *BUNDLES*, "3", "5", other curvy letters in the below comparison.

As of 2018/02/06:

Production | `next` branch 
------------ | ---------------
[Hugo v0.35 news][1] | [Hugo v0.35 news][2] 
[![Banner image][3]][3] | [![Banner image][4]][4]

[1]: http://gohugo.io/news/0.35-relnotes/
[2]: https://next--gohugoio.netlify.com/news/0.35-relnotes/
[3]: http://d33wubrfki0l68.cloudfront.net/a3147069e4d24dbc6521f0fde13bcea0d2c8875d/d91b2/news/0.35-relnotes/news/0.35-relnotes/featured-hugo-35-poster_hua42b1310dd72f60a34e02851ebf2f82e_88519_480x0_resize_box.png
[4]: https://d33wubrfki0l68.cloudfront.net/31fcabf0788c0b3be6eec8e27f0c3d76f6e20ec4/5291a/news/0.35-relnotes/featured-hugo-35-poster_hua42b1310dd72f60a34e02851ebf2f82e_88519_480x0_resize_catmullrom_center.png

**Comment by bep** [comment]
@kaushalmodi the resizing is interpolation using a filter/interpolation function... In this branch I have set a bicubic filter.

```toml
[imaging]
# See https://github.com/disintegration/imaging
# CatmullRom is a sharp bicubic filter which should fit the docs site well with its many screenshots.
# Note that you can also set this per image processing.
resampleFilter = "CatmullRom"

# Defatult JPEG quality setting. Default is 75.
quality = 75

anchor = "smart"
```

But it's hard to find a good one that fits all. And it is a compromize between speed/quality. I have always been impressed by how Photoshop performs in this area. I guess Lanczos would be better for phothographic types of images ...

But now we are drifting far away from my "binary yes/no" question :-)

**Comment by budparr** [comment]
I've re-arranged the page to make the navigation work better, minimizing it generally. 

I've also made the landing page 3 across on larger screens, by which I hope people will be more inclined to click through for larger images and more detail.

I've cleaned up the template a bit. I hope this pattern is okay. I pulled the logic all into templates so that the layout is separate from the detail.

**Comment by bep** [comment]
I we pull the title into the box and make it smaller, I think we have a winner.

**Comment by budparr** [comment]
But keep the h1: Showcase up top, right? Someone made the case to me that I had no wayfinding on the page.

**Comment by budparr** [comment]
I moved the title

**Comment by bep** [comment]
I added "Section:" as a "<title>" prefix to create some _headway_ ... Now I think it looks very good. A general remark that we maybe should do with the theme (to create even more _headway_), is to mark the active menu element, so it is more visible that we're in the Showcase section etc.

**Comment by budparr** [comment]
I was just thinking the same thing about the active element. Frankly I'm surprised I didn't do that in the first place, because that's the norm.

**Comment by kaushalmodi** [comment]
This is looking great guys! The only critical comment I have is that these scrollbars don't look good here:

https://next--gohugoio.netlify.com/showcase/brightline-org/

![image](https://user-images.githubusercontent.com/3578197/35880755-c04bbc64-0b4c-11e8-988a-eeef69a92e70.png)

There appear on all showcase pages.

**Comment by budparr** [comment]
What browser is that?

**Comment by bep** [comment]
One question: Should the section be "Showcase" or "Showcases"? I started making a change, but then I thought that maybe the whole section is **a showcase** (one).

**Comment by kaushalmodi** [comment]
@budparr 

> What browser is that?

That's Firefox Quantum 58.0.1 (64-bit) on Windows 10.

**Comment by regisphilibert** [comment]
> One question: Should the section be "Showcase" or "Showcases"? I started making a change, but then I thought that maybe the whole section is a showcase (one).

I agree of showcase of websites.

**Comment by kaushalmodi** [comment]
Yes, just **Showcase**.

**Comment by bep** [comment]
@budparr I have:

* Added an `byline` param with very simple styling. If you have strong opinions about this, please change. I assume some of those I reach out to want some kind of named credit if they want to spend time on this.
* I have replaced the sites with a start of a template, see https://next--gohugoio.netlify.com/showcase/template/
* I will eventually re-introduce most of the others, but will let the people I reach out to a sense of "being first".
* I will create some copies of this so we can see how "many sites" looks like, eventually

**Comment by spf13** [comment]
@bep I think this is a great move forward. Thanks for delivering on this. I love the idea to make this more like a case study then just thumbnails where the site owners/developers are sharing their experiences. 

I have a list of companies and individuals that I think would make great additions to this. I'm happy to help here.

**Comment by bep** [comment]
@spf13 thanks. I have been in contact with a couple to start with, which has been positive, so there will be some new coming soon. I will, however, expect to publish some "screenshots with a comment" just to get the "site out there" in some of the cases.

But all in all, this is an easy sell. Hugo is great, and a little case study is a small price to pay for something great.

**Comment by bep** [comment]
@spf13 OK, if the last post did not imply this; I would really appreciate if you could reach out to the site s you know about. 

What they need to do should be described here:

http://gohugo.io/showcase/template/

**Comment by spf13** [comment]
I'm terrible at keeping up with this. I'm on my first day of vacation in
many months and I'm just now catching up. I'm happy to reach out to a few
people. I think smashingmag would be a great one to have!
