### ISSUE TITLE
Poor navigation in the responsive page for gohugo.io

### ISSUE THREAD

**Issue by ahmetb** [gohugoio/hugoDocs#334]
`gohugo.io` has really poor user experience on my iPad.

I can find no link to the documentation.

I can find no navigation (i.e. the sidebar). 

The content is only accessible via the search, therefore I can't ready the entire content by just clicking around.

Please try to use this website on an iPad.

**Comment by budparr** [comment]
Hey, @ahmetb I put in a quick fix for this and will likely be live soon. It could still use some improvement, but the mobile menu was definitely in a no-mans-land of screen-size and I fixed that. Thanks for pointing it out.

**Comment by kaushalmodi** [comment]
Actually @ahmetb might also be able to quickly test out this fix using this link: https://deploy-preview-336--gohugoio.netlify.com/documentation/
