### ISSUE TITLE
Adding a “last updated” page with the latest changes

### ISSUE THREAD

**Issue by divinerites** [gohugoio/hugoDocs#339]
This issue follows this thread : https://discourse.gohugo.io/t/adding-a-last-updated-page-with-the-latest-changes-on-doc/10412 and request from bep.

- It is difficult to know what are the latest improvements on the documentation.
- We could add a page : “latest changes” with the latest X changes on documentation.

So

- I posted on the above thread a code attempt for a shortcode
- @bep added the need for a  similar page with all TODO (via a new shortcode)
- He propose to create a new section (name?) with a simple list template?

**Comment by bep** [comment]
>@bep added the need for a similar page with all TODO (via a new shortcode)

The shortcode is already there, it just needs to be queried.

I suggest we limit this to the "last x" changes -- I can add the TODOs later. If someone could suggest a name for the section? "maintenance"?

**Comment by divinerites** [comment]
> If someone could suggest a name for the section? "maintenance"?

Well ... I'm bad @ english ...
- Updates ?
- Recent ?
- Changes ?

**Comment by bep** [comment]
My thought was to list more than one kind of pages:

* Latest updates
* Pages that needs attention (marked with TODO)
* ...

**Comment by divinerites** [comment]
It may be depends on the (so called) public for each page.
I guess *latest updates* is for anyone using Hugo, but *todo pages* more for contributors.

If I'm a random user, i like to have a *what's new* sort of page with direct access.
The *todo page* is may be more with the *contribute* section.

**Comment by divinerites** [comment]
On a side thought, it could be a plus for regular readers to also have the commit message (short) with a direct link to the commit, or to the diff.
This way it is easy to directly see the real changes on the page if you already know it/saw it.

It should stay in a discret style tho, avoiding to bloat the informations.

**Comment by bep** [comment]
>On a side thought, it could be a plus for regular readers to also have the commit message (short) with a direct link to the commit, or to the diff.

That's a good idea. But we're not creating several similar pages. This is a small project.

I suggest we call the section `spotlight`.

**Comment by divinerites** [comment]
My first attempt to collaborate on Hugo Docs, may be I have a wrong workflow (let me know).

I created a Pull request with my first attempt to the shortcode + section + page : https://github.com/gohugoio/hugoDocs/pull/344

**Comment by bep** [comment]
I have adjusted your PR a little. Note that it's not in the menu (I may add it at some point), but you can bookmark it:

https://gohugo.io/maintenance

**Comment by Jos512** [comment]
Nice work. 👍 

Could the 'last updated' table also show more entries than the last 10? Otherwise we'll have to check that page almost every day with all the new things and updates going on. 🙂

**Comment by kaushalmodi** [comment]
@Jos512 See https://github.com/gohugoio/hugoDocs/pull/352 -- [Preview][1]

[1]: https://deploy-preview-352--gohugoio.netlify.com/maintenance/
