### ISSUE TITLE
Wording about copyright on Showcase homepage

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugoDocs#343]
The current phrasing doesn't look right:

![image](https://user-images.githubusercontent.com/3578197/35994928-dd1891ca-0cdf-11e8-8d3b-f66cc6bd5793.png)

How about:

**The Showcase article authors hold the copyright to those.**

**Comment by bep** [comment]
It matches " The Hugo logos are copyright © Steve Francia 2013–201". I vote to take the road with less work.

**Comment by kaushalmodi** [comment]
It still feels incorrect.. how about:

> The Showcase articles are copyright **to** the content authors.

(just added that "to")
