### ISSUE TITLE
Showcase: DataDog

### ISSUE THREAD

**Issue by DirtyF** [gohugoio/hugoDocs#354]
https://www.datadoghq.com/  is built with Hugo as well as the documentation website ([repo](https://github.com/DataDog/documentation))

Might be a good candidate for Hugo's showcase.

/cc @l0k0ms from @DataDog

**Comment by bep** [comment]
See this template: http://gohugo.io/showcase/template/

**Comment by irabinovitch** [comment]
s/DataDog/Datadog/
