### ISSUE TITLE
Add disclaimer to third party hosting services.

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugoDocs#358]
Following the discussion at: https://github.com/gohugoio/hugoDocs/pull/356

As per @moorereason 's suggestion a disclaimer is needed on third party hosting services.

Something along the lines of: use these services at your own risk, or these hosting services are not associated or endorsed by the Hugo project etc.

I'm confident that someone more fluent with legalese than me, can write such a disclaimer and send a pull request. 

The need for this disclaimer has arisen because one of the services currently listed in the Hosting section has become very unreliable and members of the community feel that it's inappropriate to add a warning or remove that service from the Docs.

**Comment by bep** [comment]
I agree. I have added a temporarily warning for the GitLab case now.

I don't know how GitLab handled this, but I can sympathize a little about this "security shutdown". It's not easy on their end, either. But they should have sent proper warnings to users.

**Comment by onedrawingperday** [comment]
Thank you very much @bep
