### ISSUE TITLE
Update docs vs nested sections

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#36]

**Comment by rdwatters** [comment]
@bep I have a bunch of similar open issues in the concept repo. Just as an FYI, I'll go through them one by one and add this weekend and assign a few to myself.

**Comment by bep** [comment]
We should close issues in the documentation updates, and development and issue tracking should continue in the repository.

**Comment by Xeoncross** [comment]
I would love to organize my content into multiple folders and have access to each nested section + _index.md in my root index.html. The homepage would be "groups" of sections.

Is this possible? This issue is referenced in the docs but I haven't found anything about how to do this.

**Comment by bep** [comment]
@Xeoncross  please use https://discourse.gohugo.io/ for questions/troubleshooting.

**Comment by MikhailKlemin** [comment]
It is 0.31 version now... If there a chance to see a proper  documentation for nested section, not just an example... Please?  
On http://gohugo.io it is still:

```
     This section is not updated with the new nested sections support in Hugo 0.24
```

**Comment by bep** [comment]
> It is 0.31 version now... If there a chance to see a proper documentation for nested section, not just an example... Please?

We should, but someone needs to set aside time and do it. Maybe you can contribute?

**Comment by MikhailKlemin** [comment]
I would donate have there be such option...

**Comment by piebob** [comment]
i'm not sure why this was closed--the docs have not been added.

**Comment by millette** [comment]
Looks to me like the [the patch](https://github.com/gohugoio/hugoDocs/commit/149c2c1576507bdacbb7c0f78cd00214f7c44f00#diff-8e84ff230989673f3628662d1bb1531cL21) made it to the public site: https://gohugo.io/content-management/sections/

**Comment by piebob** [comment]
ah--i'm here and still see the notice:
https://gohugo.io/content-management/organization/

**Comment by millette** [comment]
Yeah, that part wasn't updated: https://github.com/gohugoio/hugoDocs/blob/master/content/content-management/organization.md

**Comment by bep** [comment]
Just did ...
