### ISSUE TITLE
Add "toggle" config language shortcode

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugoDocs#363]
It was discussed earlier this month that the docs should be able to present one code block with multiple tabs to toggle config languages (yaml, toml, json)

@bep created the [transform.Remarshal](https://github.com/gohugoio/hugo/commit/d382502d6dfa1c066545e215ba83e2e0a9d2c8d7) template function for this purpose.

**Comment by regisphilibert** [comment]
@bep, @budparr, @kaushalmodi (anyone I should have mentioned...)

I'm only thinking design as yet but, already I need some point of views...
Here are three concept for the look of this codeblock.
We will have up to four elements in there:
- filename
- 3 config lang tabs
- copy button
To make sure this doesn't break if the filename is too long we may have to use flexbox, so won't rely solely on tachyons.

![capture d ecran 2018-02-17 17 43 32](https://user-images.githubusercontent.com/1480503/36346567-34c3e7c8-140e-11e8-822f-ceb9a2e32589.png)

Above is the cleanest way but in case a longer file name it won't look good, see below:

![capture d ecran 2018-02-17 17 58 15](https://user-images.githubusercontent.com/1480503/36346569-4bdf4c04-140e-11e8-8738-7cb3ca794505.png)

So I'm thinking more something like this:
![capture d ecran 2018-02-17 17 45 56](https://user-images.githubusercontent.com/1480503/36346572-5e264e58-140e-11e8-82d0-d8a3ffd69d82.png)

Because we don't need the file extension, we can always hide its overflow.

![capture d ecran 2018-02-17 18 22 59](https://user-images.githubusercontent.com/1480503/36346612-a4f13bd0-140f-11e8-88f4-13ccc0314bc0.png)

I'm thinking number 2 but if you have a better design concept, or if you think i'm overlooking something, feel free to jump in.

**Comment by bep** [comment]
>I'm thinking number 2 

By that you mean the second screenshot? I kind of liked your third.

**Comment by regisphilibert** [comment]
> By that you mean the second screenshot? I kind of liked your third.

No I meant the same as you, I made it clearer.

**Comment by bep** [comment]
But this toggle should persist somehow. So when "I" pick

**Comment by regisphilibert** [comment]
> But this toggle should persist somehow. So when "I" pick TOML then I want it to continue TOML.

1. Something like general user preference thing? 
2. Or just for the current page, bind one toggle event to the other code blocks on the page?

The first one will be more complicated and need more ux/prog specing.

**Comment by regisphilibert** [comment]
> The first one will be more complicated and need more ux/prog specing.

Or... we just add its "first" choice to its cookies via javascript. But it means we'll need to read users cookies and toggle to its language of choice after page load. This could make some ugly flicking on big code blocks...

**Comment by bep** [comment]
>Something like general user preference thing?

It may end up as one, but at first we "somehow" store the format choice. This is side-stepping this particular discussion, and I'm sorry about that (but there is no need to do any reloads -- this format shifter will have to be client-side).

**Comment by regisphilibert** [comment]
> It may end up as one, but at first we "somehow" store the format choice.

Cookies or localStorage, I guess the later being preferred these days.

> but there is no need to do any reloads

No, but if the user goes to another page using toggle code blocks, we will have to 
1. show the code block with default language 
2. grab the cookie/localStorage key to know his lang of choice
3. update code blocks on page to show said lang.

So code blocks will toggle by themselves and it may be ugly. We could set the opacity to 0 while we fetch the info, but then every users even those without pref lang, would have to see this opacity animation on every page load.

**Comment by bep** [comment]
>So code blocks will toggle by themselves and it may be ugly.

As a "customer" I would say: Make it pretty.

**Comment by regisphilibert** [comment]
> As a "customer" I would say: Make it pretty.

Hehe. Chances are it may not be that noticeable. We'll see!

**Comment by regisphilibert** [comment]
I did not intend to render them client-side. All three tab-content will be there in the HTML. Just one visible until user click on one button at which point minimal js would toggle the displayed tab-content.

**Comment by bep** [comment]
>I did not intend to render them client-side. All three tab-content will be there in the HTML.

What do you do when the user click another format?

**Comment by regisphilibert** [comment]
Nothing more complex that that:
http://getbootstrap.com/docs/3.3/javascript/#tabs

Just some class toggling and let css do the rest.

**Comment by bep** [comment]
>Just some class toggling and let css do the rest.

There is nothing "plain CSS" about the example you link to. Adding a "if preflang == YAML" would not make it any more JSy.

**Comment by regisphilibert** [comment]
> Adding a "if preflang == YAML" would not make it any more JSy.

No it won't.

I'm not sure we are talking about the same thing. My only concern is aesthetic: having to wait for the page to load, until js can do "if preflang == YAML" and toggle the tabs from default to preflang. This may cause an ugly flash/flick when config code block takes most of the page (which happens quiet often).

But as you said I will try and make it look pretty.

**Comment by bep** [comment]
> My only concern is aesthetic: having to wait for the page to load, until js can do "if preflang == YAML" and toggle the tabs from default to preflang.

I have not way what  you are talking about here. The tab will be set client side. Super-fast. No waiting. these are computers working.

**Comment by budparr** [comment]
I like "Proposition 2" as well. I assume any given config language would only show up if it's present (just in case). There are [Flexbox](https://github.com/tachyons-css/tachyons/blob/master/src/_flexbox.css) classes in Tachyons.

**Comment by regisphilibert** [comment]
> I assume any given config language would only show up if it's present (just in case)

Editor will only include one language (of his choice) in the shortcode, and Hugo will translate it into the other 2. So technically there will always be the 3 mentioned config languages.

> There are Flexbox classes in Tachyons.

Oh thanks, did not initially find them.

**Comment by regisphilibert** [comment]
Thanks for your input. I'm just working on the styling/js right now. And this it how it looks:

https://www.dropbox.com/s/554ir0gonc11y0y/code_toggle.mov?dl=0

In the video above, we have 2 code-toggle on the page and they both answer when one is called so that user choice is reflected on every code toggle on the page.

@bep, you can see the little flashing I was talking about at the end of the video when, on page load we trigger the tab corresponding to the user's pref language stored in his localStorage.

### Question:
In the case of a code toggle, the copy button will capture the content of the active pane. Problem is, as copy is implemented, you can only use it once. 
With the new code toggle, user may want to copy twice if he mistakenly clicked copy while the active pane did not reflect his preferred language.
I looked at https://clipboardjs.com/ and could not a find a simple way to update or reset the copy mechanism.
I would need to somehow update the copy element from the tab script... if I can find how.

If any one has an idea, it would be much appreciated!

Thanks.

**Comment by bep** [comment]
@regisphilibert it looks good. I'm going to release Hugo 0.37 Friday (Go 1.10, but mostly to get the PNG  palette patch out there -- PNG the users have carefully stored as 8-bit etc. gets bigger file size when scaled down ...)

With that we could use Netlifty to iterate on this (use the `next` branch), which should make this easier to get over the finish line.

**Comment by regisphilibert** [comment]
> With that we could use Netlifty to iterate on this (use the next branch), which should make this easier to get over the finish line.

Sounds great!  I'll be out of the country from friday to tuesday night. Will get back to it then. 

Some mistakes are thrown out with the `transform.Remarshal` when pasting the whole site config yaml but it can wait for our iteration on the next branch.

**Comment by regisphilibert** [comment]
@bep I will be back on this next week. Unless told otherwise I will use the `next` branch so people can easily test it. I may need help with the "Copy" script, but we'll see. Thanks!

**Comment by regisphilibert** [comment]
A PR on Next is pending (https://github.com/gohugoio/hugoDocs/pull/420) 
When it is merged, you'll be able to see the toggle v 0.1 here: https://next--gohugoio.netlify.com/getting-started/code-toggle/
In the mean time it's here: https://deploy-preview-420--gohugoio.netlify.com/getting-started/code-toggle/

5 issues of note.

1. Expand  
	Current logic to add expand class uses element width which I believe is only catchable if said element is visible on page load. So the hidden panes are positively tested on page load and don’t get the « extend » class added to them. I will try to find something to fix it, but in the mean time if any one has a simple solution.
2. Comments (# Whatever) are not rendered by `remarshal` even in yaml and toml.
3. Adding comments containing a #   
	`# See https://github.com/gohugoio/hugoThemes#themetoml for an example` produce an error `cannot unmarshal !!str `name = ...` into map[string]interface {}`
4. Chroma is not triggered (or whatever the right verb should be). I hardcoded the `<pre><code></code></pre>` in the shortcode but we don’t have any highlight.
5. Unactive tab buttons look ugly on safari. Will fix.

**Comment by bep** [comment]
2) Comments are not supported and will probably never will.
3) We could maybe fix the error by stripping the comments "server side", but I don't see that as a blocker.

code-toggle is fine -- the limitation is outlined in its context.

I'm fine with mergin this ...?

**Comment by bep** [comment]
@regisphilibert re. comments, see https://github.com/gohugoio/hugo/issues/4520

I will try to wrap my head around a simple solution for YAML/TOML.

**Comment by regisphilibert** [comment]
> I'm fine with merging this ...?

Give me another day. I’ll remove the showcase page I created for it and check everything is up to my standard.

**Comment by regisphilibert** [comment]
> re. comments, see gohugoio/hugo#4520

Awesome, comments are often useful when adding context or explanation to a config key and because it throws an error we cannot even add them in the shortcode for later fix/implementation.

Will get back to you tomorrow.

**Comment by regisphilibert** [comment]
@bep you can merge it. (just added comments to tabs.js)
The expand system still has to be attended. I tried to grab the width of the clone of hidden code element (in codeblock.js) but it still produces 0. 
If any one has better skills at vanilla js than me, please try and look at it later on :)

Cheers

**Comment by regisphilibert** [comment]
I know this is closed, but before adding another issue I'd rather introduce my notion here:
Currently many Front Matter examples could benefit from the code-toggle, unfortunately, by using it we lose the openning ---/+++ used by yaml/toml respectively.

1. Should we care ?  I know I do, it reminds the user we're dealing with a Front Matter block. 
2. @bep do you think there is any chance the `transform.Remarshal` function could in the future preserve and convert those opening thingies to the given language ?

Thanks.
