### ISSUE TITLE
Don't use <link rel="feed">

### ISSUE THREAD

**Issue by Minoru** [gohugoio/hugoDocs#369]
Currently, templates tutorial suggest adding two `<link>` entries for the RSS feed:

https://github.com/gohugoio/hugoDocs/blob/15b5a0342c4817fb73c3d6e2c0cfb54871eae854/content/templates/rss.md#L119-L124

But `feed` isn't standardized at all: it appeared in [the earliest HTML5 draft](https://www.w3.org/TR/2008/WD-html5-20080122/#linkTypes) (in January 2008) but [two years later it was gone](https://www.w3.org/TR/2010/WD-html5-20100304/interactive-elements.html#linkTypes), and it doesn't appear neither in [the final HTML 5 spec](https://www.w3.org/TR/html50/links.html#linkTypes) nor in [its latest revision, 5.2](https://www.w3.org/TR/2017/REC-html52-20171214/links.html#allowed-keywords-and-their-meanings); not even in [the current working draft](https://www.w3.org/TR/2018/WD-html53-20180206/links.html#allowed-keywords-and-their-meanings).

Indieweb [suggests using `rel="feed"` for h-feed](https://indieweb.org/rel-feed), their own feed format, which is HTML-based and totally incompatible with RSS 2.0—thus, you can't use the same file for both. (Well, unless you serve different files depending on `Accept` header, but I don't think anyone would do that—not people who copy-paste from the tutorials, anyway.)

I'd submit a pull request to remove the offending line from the tutorial, but I'm confused by gohugoio/hugo#3442: contribution guidelines in Hugo repo say that the docs are *here*, yet somehow there's also a copy in the Hugo repo, and PRs to it are accepted without any problem. (That PR was effectively reverted by 6dbde8d731f221b027c0c60b772ba82dad759943.)

Am I missing something in HTML specs, and if not, where should I submit the PR that fixes this?

**Comment by bep** [comment]
>Am I missing something in HTML specs, and if not, where should I submit the PR that fixes this?

No, you are not. But there more than one thing to fix in the above. 

In the current Hugo, the recommended way would be this:

https://github.com/gohugoio/gohugoioTheme/blob/master/layouts/_default/baseof.html#L25

If you only want RSS, you can query the output formats.

**Comment by Minoru** [comment]
After reading [the docs on output formats](https://gohugo.io/templates/output-formats/#output-formats-for-pages) I'm still not sure if I just need to update two `<link>` lines, or config should be updated too. Since I'm not interested in installing Hugo and experimenting to find out, I'd let this issue lay; anyone willing to work on a PR is welcome to do so.

**Comment by kaushalmodi** [comment]
This has been fixed in https://github.com/gohugoio/hugoDocs/commit/20e8a21f6573085683f9494c8188a152faff4041.
