### ISSUE TITLE
showcase: https://smallmultiples.com.au

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#370]
This looks like a good candidate for the showcase:

https://smallmultiples.com.au/articles/introducing-the-new-small-multiples-website/

See this for a howto:
https://gohugo.io/showcase/template/

**Comment by comraderoyce** [comment]
@bep not responsible for the site, but I've pulled in the content and an image per the showcase template.

**Comment by bep** [comment]
@comraderoyce I might have read a little fast into this. What is your connection with Small Multiples? We need permission/OK from them to use the relevant content. I have set it to "draft" for now.
