### ISSUE TITLE
A/B test outgoing banner links

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#374]
@budparr this is somewhat motivated by my curiosity to test out the split-testing feature in Netlify (looks super-easy to use):
https://www.netlify.com/docs/split-testing/#_ga=2.27629940.973723561.1519718190-778521932.1515410698

* I have added tracking for the sponsor banner outgoing links.
* It would be cool if we could create a new branch with an alternative, maybe a visual indicator on the banner that it is clickable/a link, and see if that has any effect. 

I will set up a new branch and look into what needs to be done on the Google Analytics side, but it would be cool if you had an idea about the banner variation.

**Comment by bep** [comment]
Branch: https://github.com/gohugoio/hugoDocs/tree/split1
Preview: https://split1--gohugoio.netlify.com/

**Comment by budparr** [comment]
I'll have a look. I put in UTM tags to track links, so we should have data from day one.

**Comment by bep** [comment]
> I'll have a look. I put in UTM tags to track links, so we should have data from day one.

That does not help with outgoing links (at least it does not help me). I added support for this a week ago, but I have to adjust vs A/B.

**Comment by budparr** [comment]
I see, you switched from the default Hugo GA tags. That works, though the lo-fi way should still get you data, but trackoutboundlinks is better. At any rate, I'll see if I can work up something by this evening.

**Comment by budparr** [comment]
I put something rough up, which I think is good enough for testing. https://elegant-rosalind-36c73d.netlify.com/ 

With the A/B would I do the PR against the master branch?

**Comment by bep** [comment]
We do the "B version" in https://github.com/gohugoio/hugoDocs/tree/split1 -- then we can compare it with the master version.

**Comment by bep** [comment]
OK, I have figured out how to set up dimensions/segments in GA for this and has split the traffic 50/50 between master and split1. Let us see what that gets us.

**Comment by bep** [comment]
The test has been running for about a week now. I have now stopped it.

* The A/B feature of Netlify works great, so great it is easy to forget it's on...
* The two banners in this case performs almost exactly the same
* So we keep the prettiest (the one in master)
