### ISSUE TITLE
Can't re-login to the Hugo Forum using GitHub credentials

### ISSUE THREAD

**Issue by vassudanagunta** [gohugoio/hugoDocs#386]
Not sure where to report this since I'm in a Catch-22 for reporting this on the [Hugo Forum](discourse.gohugo.io). I signed up for the forum in September using my GitHub credentials and have since tried and given up logging back in many times because I'm always presented with a username/password prompt. 

The [CommonMark forum](https://talk.commonmark.org) also uses Discourse and the login button there has a button for logging in with GitHub.

**Comment by bep** [comment]
Just tested it by logging out, then in again. I got the option to use either Google or GitHub.. GitHub worked fine.

**Comment by kaushalmodi** [comment]
> GitHub worked fine.

Same here.

**Comment by vassudanagunta** [comment]
Ok, i figured it out. I had to disable [uBlock Origin](https://github.com/gorhill/uBlock/) for the gohugo.io domain. As long as the Hugo team isn't working for the NSA, I'm good. Sorry for the false alarm.
