### ISSUE TITLE
Have the TOC in sidebar show all headings up to h4 (or may be h3?), right now they show only h2

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugoDocs#394]
I have often come across Hugo documentation sections where I need to do `Ctrl + U` and view the source to figure out a heading's anchor.

A very recent example: https://gohugo.io/content-management/cross-references/#manually-specifying-anchors.

It looks like this: 

![image](https://user-images.githubusercontent.com/3578197/37116608-c9c63cb0-221c-11e8-9781-5002739f571f.png)

I would have liked to have the anchor link show up next to it, like this:

![image](https://user-images.githubusercontent.com/3578197/37116638-e4c2fcce-221c-11e8-9664-66bb271465e7.png)

But looks like the anchor link addition (and also the showing up of the headings on the content in the right sidebar) happen only till h2 level headings.

The "Manually Specifying Anchors" sub-section is under "Hugo Heading Anchors", and it would be useful to have that sub-section show up in the content sidebar too.. but it is not:

![image](https://user-images.githubusercontent.com/3578197/37116692-0953a4a8-221d-11e8-8af6-3859ada9f8de.png)

---

**Can the level depth for (1) appending of that anchor link, and (2) inclusion in the sidebar content, be increase to h4 from h2?**

**Comment by kaushalmodi** [comment]
I see that a CSS hack is used to hide levels deeper than h2 in the TOC as we cannot control the number of levels in `.TableOfContents`.

Then, how about using something like: https://github.com/tscanlin/tocbot ([Demo][1])? [Looks like][2] we can easily configure how many heading levels to include in the TOC.

[1]: https://tscanlin.github.io/tocbot/
[2]: https://tscanlin.github.io/tocbot/#usage

**Comment by bep** [comment]
What is this issue about? It looks like two different thing, which is hard to track in one issue.

**Comment by kaushalmodi** [comment]
The issue is that it's not easy to get links to h3 and lower level headings (useful when pasting in discourse forum). The "chain icon" does not appear for h3 and lower headings, and the TOC also does not show h3 and lower headings. So the only resort is to do Ctrl + U and copy the sub-heading `id`.

Agreed, that different pieces of CSS govern the chain icon on the right of sub headings and the hiding of headings in the TOC sidebar..

**Comment by budparr** [comment]
The way Hugo's TOC work we would have a very long list of TOC for each post. To increase readability, I made it only show higher levels. They're automatically generated, so the headings themselves could be more thoughtful or useful.

On the chain links, I'd have to look. I don't recall. 

I was thinking of redoing the single-pages anyway, now that they've been in the wild for a while (I think I need to wait until @bep finishes with some A/B testing), but I'd be happy to address this when I do.

**Comment by bep** [comment]
>I think I need to wait until @bep finishes with some A/B testing

I will let that live for 2 more days.

**Comment by budparr** [comment]
Okay. I'll create an issue with my intentions here soon.

**Comment by kaushalmodi** [comment]
Part of this issue is a duplicate of https://github.com/gohugoio/hugoDocs/issues/286.

**Comment by kaushalmodi** [comment]
- [x] Anchorify headings up to h4 level - Done in https://github.com/gohugoio/hugoDocs/commit/7ae9cf2ccb3eecc1ff50f686925249d01cf37c6c
- [ ] Show levels up to h4 in TOC
