### ISSUE TITLE
.Site.RegularPages vs .Data.Pages

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugoDocs#398]
I find these 2 confusing.. looks like .Site.RegularPages is almost always the right thing to use..

Then, when should .Data.Pages be used?

**Comment by kaushalmodi** [comment]
Document the nuances in usage between the two.

**Comment by bep** [comment]
>Then, when should .Data.Pages be used?

They are never the same. 

If you use `.Pages` it may be easier to understand (`.Data.Pages` is kept for historical reasons) -- it is the page's pages. `$myTaxonomy.Pages` is a subset of .Site.RegularPages and .Site.Pages.

**Comment by budparr** [comment]
I've been using `.Data.Pages` up until now. Good to know, because without it the entire thing makes more at-a-glance sense .Pages -> .Site.Pages.

**Comment by budparr** [comment]
Looks like we should change all of these, right? https://github.com/gohugoio/hugoDocs/search?l=Markdown&q=.Data.Pages&type=&utf8=%E2%9C%93

**Comment by bep** [comment]
Yes. I think I held off on the documentation with this until the `.Pages` was a well established "alias", but that is ... years ago.

**Comment by kaushalmodi** [comment]
OK, is this a good, and correct summary:

| Variable              | Current context | Pages included                                                                                                                                       |
|-----------------------|-----------------|------------------------------------------------------------------------------------------------------------------------------------------------------|
| `$.Site.Pages`        | **any**         | **All** pages: content, sections, taxonomies, etc. -- Superset of everything!                                                                        |
| `$.Site.RegularPages` | **any**         | Only _regular_ pages.. content pages -- Subset of `$.Site.Pages`                                                                                     |
| `.Pages`              | _List_ page     | Pages under that section, taxonomy term (`tags`), taxonomy (`/tags/foo`) -- Subset of `$.Site.Pages` or `$.Site.RegularPages`, depending on context. |
| `.Pages`              | _Single_ page   | _none_                                                                                                                                               |

**Comment by bep** [comment]
>: Do NOT use .Data.Pages anywhere .. deprecated.

That is a little harsh. There are some other stuff in `Data` as well, so it makes kind of sense to say that `Data` is a data container for the page ... It will never be removed.

And the single page has an _empty_ `.Pages`, which may or not be the same as `none`-- but it is not nil. 

But I'm not sure putting that table in the documentation will make it much clearer.

**Comment by kaushalmodi** [comment]
> There are some other stuff in Data as well

Correct. I meant to imply "deprecated" only to `.Data.Pages`, not the whole of `.Data`. But I get your point. But in non-harsh terms, you don't ever see the point of using `.Data.Pages`.. right?

> And the single page has an empty .Pages, which may or may not be the same as none-- but it has a value.

Agreed, will change that.

> But I'm not sure putting that table in the documentation will make it much clearer.

But this needs to be documented in *some* fashion.

**Comment by kaushalmodi** [comment]
@budparr 

> Looks like we should change all of these, right? https://github.com/gohugoio/hugoDocs/search?l=Markdown&q=.Data.Pages&type=&utf8=%E2%9C%93

See https://github.com/gohugoio/hugoDocs/pull/526.
