### ISSUE TITLE
Update about/features

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugoDocs#405]
https://gohugo.io/about/features/

I ended up cursorily grepping/reviewing the places where Pygments was specified and Chroma wasn't mentioned at all, and saw the the features listed are very old and doesn't mention new features (not new any more :)) like Chroma, output formats, image processing, etc.

**Comment by budparr** [comment]
Do we even need that page? The home page reflects features (now out of date with some of the bundles/resources features) and, I think the fewer pages to maintain the better.

**Comment by kaushalmodi** [comment]
That's even better :)

**Comment by dryscord** [comment]
HUGO changes a lot that that page is indeed outdated.

**Comment by flexxgaad** [comment]
It seems the page is now updated.

**Comment by jmooring** [comment]
@flexxgaad I guess it was updated at some point, but it needs some love. I'm planning to use [this](https://github.com/gohugoio/hugo?tab=readme-ov-file#readme) as a model.
