### ISSUE TITLE
Document the definition of a 'section'

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugoDocs#409]
The collective meaning of a 'section' is understood from the whole documentation, but a definitive text explaining that is missing in https://gohugo.io/content-management/sections/.

**Comment by bep** [comment]
Maybe we need a glossary.

**Comment by kaushalmodi** [comment]
> Maybe we need a glossary.

Serious or joking? :) In any case, I now have a PR at least for the *section* definition.

**Comment by kaushalmodi** [comment]
This should suffice confusion like this: https://discourse.gohugo.io/t/how-do-i-get-the-nested-section-that-a-page-is-in/10993/6?u=kaushalmodi
