### ISSUE TITLE
Document NextInSection, PrevInSection (and possibly also Next, Prev)

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugoDocs#413]
Couldn't find `NextInSection` and `PrevInSection` documented anywhere.. especially the fact that they go in the opposite order compared to `Next` and `Prev` (See https://github.com/gohugoio/hugo/issues/1061#issuecomment-372390847).

---

Searching for **Next** does not return any thing useful:

![image](https://user-images.githubusercontent.com/3578197/37308415-5e6007a2-2614-11e8-898f-fb68969e76fe.png)

It's only reference, I believe, is in: http://gohugo.io/templates/pagination/

.. and the same for `Prev`.

---

Also not sure that @bep refers to as "undocumented feature" [here][1]. I followed the later comment:

> The last one I believe is undocumented, but if you read Go code, see this commit: https://github.com/gohugoio/hugo/commit/b719ba7e2bd612e85e539b17569ed15066ebcc07

.. but that commit only has `Next` and `Prev` definitions.. *What am I missing?*

[1]: https://discourse.gohugo.io/t/question-regarding-next-prev-navigation/1055/2?u=kaushalmodi

**Comment by bep** [comment]
>.. but that commit only has Next and Prev definitions.. What am I missing?

... The point? :-)

**Comment by kaushalmodi** [comment]
Sorry, I don't get it. Understood that Next, Prev, NextInSection, PrevInSection need to be well documented. But what is the fifth thing you refer to in that comment, that's neither documented in that comment nor, from what I understand, in that referenced commit.

**Comment by bep** [comment]
Those methods are not documented. 

Also see https://github.com/gohugoio/hugo/issues/4500

Take any questions on that issue.

**Comment by rdwatters** [comment]
@kaushalmodi I should note that I (likely incorrectly) put these in the "Page Variables" page under the "Variables" section if you're looking for them within the docs:

http://gohugo.io/variables/page/

**Comment by kaushalmodi** [comment]
@rdwatters Thanks. The "unable to find the documentation" was due to older Algolia settings which got fixed later (related discussion: https://github.com/gohugoio/gohugoioTheme/issues/63#issuecomment-373811385).

I then though of leaving this open.. as it's not documented that *Next* and *NextInSection* work in opposite directorions (and the same with *Prev* and *PrevInSection*).. see https://github.com/gohugoio/hugo/issues/1061#issuecomment-372390847.
