### ISSUE TITLE
How to merge gohugoioTheme worktree into this repo? #dev

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugoDocs#418]
Hello @bep,

I have used git extensively, but never used git worktrees.. Looks like you have added the gohugoioTheme repo to this one as a worktree/subtree? As I do not see it as a git submodule..

Can you document the steps somewhere on how to do that merge?

Or is converting gohugoioTheme to a submodule an option?

Thanks.

**Comment by bep** [comment]
>Or is converting gohugoioTheme to a submodule an option?

The choice of making it a sub-tree was deliberate. It is a little painful, but the benefits are bigger.

To sync the theme back to `hugoDocs` use the `pull-theme.sh` script.

To go the other way is a little harder (and takes time):

1. Set up  theme-local as a "local remote" on your `hugoDocs` repo (mine looks like this: `theme-local	/Users/bep/go/src/github.com/gohugoio/gohugoioTheme`)
1. git subtree push --prefix=themes/gohugoioTheme/ theme-local `some-temp-branch`
2. Go to your theme-local master: git merge `some-temp-branch`

The benefits are obvious if you look at the main `hugo` repo where we distribute the docs as part of the source distro (with theme and all). We could not do that with submodules. 

And it also allows @budparr  and others to create complete PRs with changes in the theme etc. with a Netlify preview in this repo.

**Comment by kaushalmodi** [comment]
Is `subtree` a git alias of yours?

I get:

> git: 'subtree' is not a git command. See 'git --help'.

**Comment by bep** [comment]
>Is subtree a git alias of yours?

No.

```bash
▶ git version
git version 2.14.1
```
I did some digging into this some time ago, and `subtree` is part of the Git distro. I doubt they removed it in 2.15...?

**Comment by kaushalmodi** [comment]
@bep Thanks for the script.. looks like it worked fine :).. at least the commit message doesn't have any surprises... https://github.com/gohugoio/hugoDocs/commit/489ec5ea03799fa092d891838c1655e60b34f337.
