### ISSUE TITLE
time format documentation

### ISSUE THREAD

**Issue by client9** [gohugoio/hugoDocs#419]
Hello,

I wrote up something hugo, golang and time formats.

https://www.client9.com/convert-strftime-time-format-to-hugo/

I'm happy to donate / repurpose it to hugoDocs. I read the contribution guide, but might need some pointers where should this go into the docs structure, and general style.

And to know me, is to copy-edit me.

Feedback and comments welcome,

regards,

n

**Comment by kaushalmodi** [comment]
Hello,

That's a good article.

We have this in documentation: https://gohugo.io/functions/format

What improvements do you suggest in that? You can provide a PR to https://github.com/gohugoio/hugoDocs/blob/master/content/functions/format.md.

**Comment by client9** [comment]
Hi @kaushalmodi   [embarrassed]  I wrote this like a year+ ago, and at the time I don't think  https://gohugo.io/functions/format existed.  I should have relooked. 

Let me re-read and see what I'd add.   Mostly rewoking "converting from strftime formats" and the table in separate section.     Will send a PR.

thanks,

n
