### ISSUE TITLE
Discussion about subtree vs submodule

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugoDocs#421]
@bep, \cc @budparr:

I read your comment at https://github.com/gohugoio/hugoDocs/pull/420#issuecomment-373871060:

> That is a pragmatical approach and the benefit of the subtree approach. 

and also from https://github.com/gohugoio/hugoDocs/issues/418#issuecomment-373744953:

>  if you look at the main hugo repo where we distribute the docs as part of the source distro (with theme and all). We could not do that with submodules.

> And it also allows @budparr and others to create complete PRs with changes in the theme etc. with a Netlify preview in this repo.

I still don't completely 'get' the benefit of subtrees.. it just seems more work, but not benefits.

### Distributing hugoDocs + theme with hugo core repo

You can still do that with git submodules.. You create a submodule for hugoDocs inside hugo core (just as you have that as a subtree right now).

You then just do `git clone --recurse-submodules` instead of plain `git clone`, that's it.. and the end user won't know if the hugoDocs subdir is a submodule or a subtree.. and I believe maintaining subtrees would be much easier.

### Multi-user contribution

- Anyone wanting to contribute would not be able to do so without committing in the actual repos. Right now, those commits can go in the subtrees or actual repos, and it could result in merge-mess at the time of releases.
- If hugoDocs repo were added as a submodule, it would have 2 active branches: master (stable) and devel. **The devel branch will always be a superset of master.** So all unreleased feature docs would go on devel, but typo fixes, released feature docs, etc would go on master first, and then merged into devel. Then at the time of release, you just need to merge devel in master.

### Netlify previews

You can still do that.

- Let's say you want to try a new feature X that requires some change in the hugoDocs.
  - Create a branch Y in hugoDocs.
  - Create a branch X in hugo, and then update the hugoDocs submodule reference to point to the hugoDocs-branch-Y-hash.
  - Commit. That's it.. Netlify will build the preview using hugo branch X + hugoDocs branch Y.

### Cleanliness

As submodule pointers are just hashes, at the time of release, you'll just have an innocuous commit for doc update on the hugo master branch.. and update of submodule reference for hugoDocs tagged vN-1 to the reference tagged vN.

Example: See [this commit][1] where I update the submodule reference for my theme for my hugo site.

![image](https://user-images.githubusercontent.com/3578197/37549868-1419b46e-295b-11e8-9294-4484b8e2266c.png)

The commits for hugoDocs update on hugo master branch would look just like that.. just a submodule reference update, much cleaner.

---

*And the same for submodule releationship between hugoDocs and gohugoioTheme.*

[1]: https://gitlab.com/kaushalmodi/kaushalmodi.gitlab.io/commit/a981f16c02aca6dbf4b07755f755bf7f9665603c

**Comment by bep** [comment]
___

Let's say you want to try a new feature X that requires some change in the hugoDocs.
Create a branch Y in hugoDocs.
Create a branch X in hugo, and then update the hugoDocs submodule reference to point to the hugoDocs-branch-Y-hash.
___

How is the above simpler than "make the code and docs change in 1 repo"?

The core problem that needs to be solved in all of this before we even _start to discuss it_ is the complete and versioned source distribution. I understand the `git clone --recurse-submodules` -- but you have to take this with GitHub and not me.
