### ISSUE TITLE
Document setting of params, etc from themes

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugoDocs#427]
https://github.com/gohugoio/hugo/commit/e9c7b6205f94a7edac0e0df2cd18d1456cb26a06

**Comment by kaushalmodi** [comment]
Example `themes/foo/config.toml`: https://github.com/gohugoio/hugo/commit/e9c7b6205f94a7edac0e0df2cd18d1456cb26a06#diff-2fb049fba21e581a781999e58ba6bdbfR122

**Comment by kaushalmodi** [comment]
@bep I am starting to add a rough outline of what you can and cannot do in the theme's config.toml. Please add/correct as needed.

## Can Do

1. Define new  `mediaTypes."foo/bar"` media types
2. Define new `outputFormats.zoo` custom Output formats

Example:

```
# Atom feed
# https://gist.github.com/lpar/7ded35d8f52fef7490a5be92e6cd6937
[mediaTypes."application/atom"]
  suffix = "xml"
[outputFormats.Atom]
  # https://validator.w3.org/feed/docs/atom.html#whatIsAtom
  mediaType = "application/atom"
  baseName = "atom" # generated file = <baseName>.<mediaType."application/atom".suffix> = atom.xml
  isPlainText = false
```

3. Define new custom Params. Below will be accessible as `.Site.Params.THEME.p1` or `.Site.Params.p1` assuming that a param with the same name is **not** defined in the site config.

```
[params]
p1 = "p1 theme"
```

## Cannot Do in `themes/foo/config.toml`

1. Cannot have `[mediaTypes]` or `[outputFormats]` in either the site's config.toml or theme's config.toml. Both places can only do `[mediaTypes."foo/bar"]` or `[outputFormats.zoo]`.
2. Cannot set `frontmatter` as that would be partially defining it.

```
[frontmatter]
expiryDate = ["date"]
```

**Comment by bep** [comment]
> Define new custom Params. Below will be accessible as .Site.Params.THEME.p1 or .Site.Params.p1 assuming that a param with the same name is not defined in the site config.


Yes, that is correct. I had, however, a thought the other day that I have not followed up on. Not sure what it was, but it was related to the upcoming "theme merge" feature.

So, the motivation for the "theme params namespace" is to give the theme a place where he/she knows the theme settings will be.

But what is really the theme name? Today it is really the folder below /themes, which the theme author does not control ... Hmm...

**Comment by kaushalmodi** [comment]
> But what is really the theme name? 

Should be defined in theme's config.toml? And throw an error if that is not defined?

**Comment by kaushalmodi** [comment]
Also, should it be made a convention to **not** have users use `[mediaTypes]` in their site configs? Because otherwise, the theme won't be able to set `[mediaTypes."foo/bar"]`.

**Comment by bep** [comment]
>Surprisingly, I was unable to set the whole Taxonomies map in the theme's config.toml. I

Why is that a surprise? My commit message is pretty clear on what is there.

**Comment by kaushalmodi** [comment]
Well, surprise not in that sense.. but in the manner that it makes more sense for a theme to be able to set those.. a theme could have custom layouts for series, etc. So it better to set the `series` taxonomy in the theme by default. But anyways, not a big deal.. I was just documenting the "can do" and "cannot do" for my sake as I was porting stuff from my site's config to [that][1] in my theme.

Now there's enough raw material here to start documenting this.

[1]: https://gitlab.com/kaushalmodi/hugo-theme-refined/blob/master/config.toml

**Comment by bep** [comment]
Yea, I had to stop somewhere. I have been bitten before because I have rushed into things like these. Taxonomy is not obviously a theme concern.

**Comment by jmooring** [comment]
This will be addressed with https://github.com/gohugoio/hugoDocs/issues/1888
