### ISSUE TITLE
Document that both true/false blocks of cond get evaluated unconditionally

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugoDocs#442]
See https://discourse.gohugo.io/t/difference-between-if-and-cond/11455/2?u=kaushalmodi

/cc @paulcmal Would you like to submit a PR with example?

**Comment by paulcmal** [comment]
I would love that. However, I'm a bit busy writing [content plugins](https://framagit.org/csa-ivry/vaydom/tree/master/bin) at the moment, so it may be a few days before I actually submit the PR.

Don't hesitate to bump the topic to let me think of it :)

**Comment by moorereason** [comment]
`cond` is meant to mimic a ternary operator, similar to `?:` in C-like languages.

**Comment by lucperkins** [comment]
@kaushalmodi @paulcmal I'm going to submit a docs PR today.

**Comment by kaushalmodi** [comment]
This was fixed in https://github.com/gohugoio/hugoDocs/commit/e8fbc163e8630a0c24c1821e4aef9bdd13cce5f8.
