### ISSUE TITLE
Clarify some stuff in branch bundles

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugoDocs#446]
Ref: https://github.com/gohugoio/hugo/issues/4594#issuecomment-379562221

Need to yet understand what exactly needs to be clarified.

/cc @bademux

**Comment by onedrawingperday** [comment]
I’ve ran into this myself.

Directories below the content root are treated as Sections.

So if a user creates an _index.md directly under /content/ there is access to .Resources that are right next to said _index.md

Also if a user creates an index.md directly under /content/ again folders are treated as Sections and not as part of the Leaf Bundle.
