### ISSUE TITLE
Document the .Sub, .After and other calculation functions that can be used for time

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugoDocs#447]
- https://godoc.org/time#Time
- https://discourse.gohugo.io/t/convert-a-string-to-a-time-datetime/11515/3
- https://discourse.gohugo.io/t/parsing-dates-in-templates/603/15
- https://gohugohq.com/howto/compare-date-strings-in-hugo/#calculations

**Comment by moorereason** [comment]
Agreed.  These are not really functions.  They are methods on `time.Time` objects.  Consider the fact that we need to document the type not individual functions.

**Comment by kaushalmodi** [comment]
> These are not really functions.

TIL that Go distinguishes methods from functions.. I googled a bit, but I still couldn't quite grasp the difference.. the resources I referred went into other Go lang lingo like "receivers" and stuff. If you don't mind explaining, what would be a 1-2 liner difference between a method and function?

From what I see.. the `time.Time` *methods* ship with the Go lang itself? whereas the *functions* are part of, and specific to Hugo?

>  Consider the fact that we need to document the type not individual functions.

I didn't quite understand that. Do you mean that we just list all the methods available for variables of type `time.Time`, and then link to the godoc.org documentation?

**Comment by moorereason** [comment]
> what would be a 1-2 liner difference between a method and function?

Methods are tied to a specific **type** (or an instance of an object in OOP).  Functions are stand-alone.

For an example function, look at [`time.Parse()`](https://golang.org/pkg/time/#Parse).  `Parse` stands alone and simply operates on the parameters you pass it.  It, in turn, gives you a Time object back.

By contrast, that Time type has many methods hanging off of it, such as `Time.Day()`.  You don't pass it parameters like you did to `Parse`--the Time type has everything it needs already and just returns the integer for the day defined within it.

> From what I see.. the time.Time methods ship with the Go lang itself? whereas the functions are part of, and specific to Hugo?

Yes.  We use the Go `time.Time` type, so its properties and methods are exposed to the user in the templates.  Hugo has its own types as well, such as [Pages](https://godoc.org/github.com/gohugoio/hugo/hugolib#Page), [Images](https://godoc.org/github.com/gohugoio/hugo/hugolib#Image), etc.

Almost all of the functions in Hugo templates are functions we created.

> Do you mean that we just list all the methods available for variables of type time.Time, and then link to the godoc.org documentation?

Not exactly.  I prefer to have our docs be self-contained, so I'd rather not link to the godocs.  They're meant for a different audience, anyway.

I envisioned a Time page similar to our [Git Variables page](https://gohugo.io/variables/git/).  We would move Time methods (like [.Format](https://gohugo.io/functions/format/), [.AddDate](https://gohugo.io/functions/adddate/), and [.Unix](https://gohugo.io/functions/unix/)) to that page where they belong, and add anything else from the `time.Time` type that seems relevant.  Then from functions such as [`time`](https://gohugo.io/functions/time/), [`now`](https://gohugo.io/functions/now/), and [`dateFormat`](https://gohugo.io/functions/dateformat/), we link to the Time Variables page for additional info.

**Comment by moorereason** [comment]
Related to #105.

**Comment by bep** [comment]
We have an outstanding issue getting a good separation between methods and funcs in the docs. We have used the ".Something" to indicate a method. The main point being that the functions are "standalone" and the methods do not make sense without the receiver.

**Comment by moorereason** [comment]
@bep,
My argument is that we document the main types (with their properties & methods) separate from the functions.  As you say, tie the methods to their receiver.  We already do that for some types, but not all.

Are you and I agreeing here?  If not, where do we differ?

**Comment by bep** [comment]
>Are you and I agreeing here? If not, where do we differ?

We agree.
