### ISSUE TITLE
Document new features in v0.39

### ISSUE THREAD

**Issue by moorereason** [gohugoio/hugoDocs#452]
* [x] `anchorize` https://github.com/gohugoio/hugo/commit/4dba6ce15ae9b5208b1e2d68c96d7b1dce0a07ab
* [ ] `path.Join` https://github.com/gohugoio/hugo/commit/880ca19f209e68e6a8daa6686b361515ecacc91e
* [ ] `path.Split` https://github.com/gohugoio/hugo/commit/01b72eb592d0e0aefc5f7ae42f9f6ff112883bb6
* [x] `Resource.Content` https://github.com/gohugoio/hugo/issues/4622

**Comment by jrisch** [comment]
I would really like to use the new Resource.Content feature, but I cannot get it to work. I've use readFile like this before:

`{{- $file := .Params.codefile -}}
{{ readFile $file }}
`

And I would like to replace it with that. I've tried:

`{{- $file := .Resources.Match "code.txt" }}
{{ .Resource.Content $file }}`

and

`{{ ( .Resources.Match "code.txt" ).Content }}`

and a couple of other things I can't remember now. But none of it works... :-/

**Comment by rdwatters** [comment]
@jrisch That might be better for the forums. This is just an issue for documenting these new features. https://discourse.gohugo.io
