### ISSUE TITLE
Use imperative mood in titles

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#46]
This is a matter of taste, but to me, this looks heavy:

```bash
Taxonomy List Templates
Taxonomy Terms Template
WeightedPages
Ordering Taxonomies
Ordering Content within Taxonomies
Displaying a Single Piece of Content’s Taxonomies
Listing Content with the Same Taxonomy Term
Listing All content in a Given taxonomy
Rendering a Site’s Taxonomies
.Site.GetPage for Taxonomies
 ```

Compare that to the lighter:

```bash
Taxonomy List Templates
Taxonomy Terms Template
WeightedPages
Order Taxonomies
Order Content within Taxonomies
Display a Single Piece of Content’s Taxonomies
List Content with the Same Taxonomy Term
List All content in a Given taxonomy
Render a Site’s Taxonomies
.Site.GetPage for Taxonomies
 ```

**Comment by rdwatters** [comment]
1. This is a good idea.
2. At the risk of sounding like a pedant, I believe this is the simple infinitive mood and not the imperative mood; i.e., we aren't telling/exhorting/entreating users what to do.  
3. I'm happy to take on making this consistent once we decide on preferred style.

**Comment by moorereason** [comment]
You're probably right on the pedantic "mood" correction.  We started using the "imperative" term in our contributing guide based upon [a blog article](https://chris.beams.io/posts/git-commit/).  Feel free to correct the contributing guides.

**Comment by bep** [comment]
I'm from Norway.

This sounds like the work for a regexp replacement. We have plenty of tasks that need manual labour.
