### ISSUE TITLE
Move content from Hugo 0.32 HOWTO to correct sections in documentation

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugoDocs#460]
https://gohugo.io/about/new-in-032/

https://discourse.gohugo.io/t/a-page-in-site-sections/11690/9?u=kaushalmodi

Also update the examples with current version of Hugo (example: GetByPrefix is deprecated).

**Comment by regisphilibert** [comment]
Do we still need this blog post though? 
It has been the first inspiration for documenting Page Resources, but I thought everything mentioned in there had already been ported to the relevant pages of the doc, split between [Page Bundle](https://gohugo.io/content-management/page-bundles/), [Image Processing](https://gohugo.io/content-management/image-processing/), [Page Resources](https://gohugo.io/content-management/page-resources/)... 

Am I missing something?

**Comment by bep** [comment]
No, delete it.
