### ISSUE TITLE
github_repo not set in config

### ISSUE THREAD

**Issue by jorinvo** [gohugoio/hugoDocs#47]
The "File an issue" link in the footer currently doesn't work:
https://github.com/gohugoio/gohugoioTheme/blob/master/layouts/partials/site-footer.html#L22

Congrats for the new design, I like it a lot 🎉

**Comment by rdwatters** [comment]
@budparr Looks like this could be fixed in one or two places. You currently have `github_repo`, but perhaps we can use `ghissue` as a param in the [site config](https://github.com/gohugoio/hugoDocs/blob/master/config.toml) instead and set it to the new issue url (i.e., `https://github.com/gohugoio/hugo/issues/new`)?

**Comment by budparr** [comment]
We have in the config now:
```
  ## Gh repo for site footer (include trailing slash)
  ghrepo = "https://github.com/gohugoio/hugoDocs/"

  ### Edit content repo (set to automatically enter "edit" mode; this is good for "improve this page" links)
  ghdocsrepo = "https://github.com/gohugoio/hugoDocs/tree/master/docs"
```
A quick search seems to indicate they have uses in shortcodes, or something, but the "ghrepo" is not what it describes. I think we need some more descriptive param names, and I think we put the repo only in the param and fill out the rest of the link where appropriate. I don't think "gh" does anything for us either.

so, perhaps

`documentation_repo`
`hugo_repo`

so the footer link would be:

`{{ .Site.Params.hugo_repo }}/issues/new`


Thoughts?

**Comment by rdwatters** [comment]
Works for me. It's also better than my suggestion of a link specifically for new issues, which is way too granular.

**Comment by kaushalmodi** [comment]
@budparr That looks great.

**Comment by kenmorse** [comment]
@budparr Is this still an issue? It looks like both `github_repo` and `ghdocsrepo` are now set in params.toml and the both the _File an Issue_ and _IMPROVE THIS PAGE_ links behave appropriately.
