### ISSUE TITLE
Restore the "Hugo Open on Save" animated GIF in 0.25 release notes

### ISSUE THREAD

**Issue by anthonyfok** [gohugoio/hugoDocs#473]
* https://gohugo.io/news/0.25-relnotes/
* https://github.com/gohugoio/hugo/releases/tag/v0.25

The links to the GIFs seem to have expired.

Fortunately, the "animated GIF" can still be seen here:

* https://twitter.com/GoHugoIO/status/879065641315119104

though it is actually an MPEG-4 video (Twitter converts animated GIFs into videos for better compression):

* https://video.twimg.com/tweet_video/DDMRQwKXcAEZaS2.mp4

Short of converting that MPEG-4 video back to GIF, does anyone still has a copy of the original animated GIF somewhere?  :-)

**Comment by kaushalmodi** [comment]
Might be worth using just that mp4 for now?
