### ISSUE TITLE
countrunes and countwords are set as aliases of each other

### ISSUE THREAD

**Issue by maiki** [gohugoio/hugoDocs#48]
Both function pages have an alias line:

```
aliases: [/functions/countrunes/,/functions/countwords/]
```

I would have removed them, but maybe that is part of a plan? The current site is redirecting `countwords` to `countrunes`.

**Comment by kaushalmodi** [comment]
@bep 

That alias is [still there][1], and oddly https://gohugo.io/functions/countwords/ is **not** redirecting to https://gohugo.io/functions/countrunes/. Why doesn't that alias work?

Also, should that alias be fixed as @maiki suggested?

[1]: https://github.com/gohugoio/hugoDocs/blame/3bc56e9ecc2d5585761a6d25e2133d02f1ad1034/content/functions/countwords.md#L18

**Comment by bep** [comment]
>Also, should that alias be fixed as @maiki suggested?

Yes.
