### ISSUE TITLE
News pages need better titles

### ISSUE THREAD

**Issue by moorereason** [gohugoio/hugoDocs#49]
URL: https://gohugo.io/news/

Many of the articles have the same title, such as "June Release."  We should change these to "Hugo 0.24.1 Release" or something.

**Comment by rdwatters** [comment]
Agreed. Adding similar conversation but just for reference: https://github.com/rdwatters/hugo-docs-concept/pull/161#issue-241836566

**Comment by bep** [comment]
Do it simple: Use the `.Title`. Problem solved.

**Comment by bep** [comment]
Fixed
