### ISSUE TITLE
Add snap install for Ubuntu

### ISSUE THREAD

**Issue by anthonydillon** [gohugoio/hugoDocs#50]
The current documentation says to install hugo via apt. The version installed by apt is very old and does not work with the default theme. 

https://gohugo.io/getting-started/installing/#i-class-icon-linux-i-linux

The snap version is up to date and works out of the box. So please update the documentation to install via the snap:
``` bash
sudo snap install hugo
```

**Comment by anthonyfok** [comment]
> The current documentation says to install hugo via apt. The version installed by apt is very old and does not work with the default theme.

The version installed by apt can be very old or very new depending on the distribution that the end user is using, e.g. Ubuntu 16.04 LTS (Hugo 0.16) vs. Ubuntu 18.04 LTS (Hugo 0.40.1) vs Ubuntu 18.10 (Hugo 0.47.2).  I think that is something that needs to be addressed in the docs too.  (Note to self: Doc reorganization needed, see https://discourse.gohugo.io/t/quick-start-doesnt-work-on-ubuntu/14686)
