### ISSUE TITLE
Install theme documentation discrepancy

### ISSUE THREAD

**Issue by vkatsikaros** [gohugoio/hugoDocs#503]
The documentation suggests 2 ways of installing a theme:

1) [Quick Start](https://gohugo.io/getting-started/quick-start/#step-3-add-a-theme) `git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke`

2) [Install and Use Themes](https://gohugo.io/themes/installing-and-using-themes/#install-a-single-theme) `git clone URL_TO_THEME`

I understand the implications of git submodules VS cloning the repo but:

a) An inexperienced git user could be confused by the discrepancy.

b) As an experienced git user I am wondering what is the suggested approach in using themes, ideally  depending on the level that the theme customization.

I would expect to see a "single theme" to be installed in the same way in both documentation pages. Alternatively I would expect some comments on suggested approach on theme customization/maintenance. 

Note: moved here from [hugo issue 4844](https://github.com/gohugoio/hugo/issues/4844)

**Comment by havelund** [comment]
Documentation for static website generators generally is not great. I would recommend someone to observe a newbie read the documentation for Hugo and try to e.g. create something as simple as a menu.
