### ISSUE TITLE
Git Version on “hosting-on-github”

### ISSUE THREAD

**Issue by khalid-hussain** [gohugoio/hugoDocs#506]
![image](https://user-images.githubusercontent.com/3102714/41746821-53961f36-75de-11e8-91b4-fc1996fcf58c.png)

Link: https://gohugo.io/hosting-and-deployment/hosting-on-github/

The latest version on [Git-SCM](https://git-scm.com/downloads) seems to be 2.18, although I can only download the 2.17.1 for Windows.

Is this a mistake?

**Comment by bep** [comment]
>Is this a mistake?

Yes.

**Comment by Hanzei** [comment]
Why is this a mistake. Git 2.8 is a valid version (see https://github.com/git/git/blob/master/Documentation/RelNotes/2.8.0.txt)

**Comment by bep** [comment]
>Why is this a mistake. 

OK, it was a mistake of me to say it was a mistake. Of course, 2.8 is valid.

**Comment by khalid-hussain** [comment]
I'm not sure about 2.8.

The [Git releases](https://github.com/git/git/releases) page shows 2.18 as the latest version.

![image](https://user-images.githubusercontent.com/3102714/41929263-155764ee-79aa-11e8-8b1d-661e4d3e0597.png)

**Comment by kaushalmodi** [comment]
@khalid-hussain 8 < 18 => 2.8 < 2.18.
