### ISSUE TITLE
Clarify the singular/plural type requirement

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugoDocs#521]
If I have `content/posts/foo.md`, setting its layout in `layouts/posts/single.html` works. In the example in https://gohugo.io/content-management/types/#custom-content-type-template-lookup-order, it has (emphasis mine):

> The lookup order for the content/events/my-first-event.md templates would be as follows:
>    - layouts/event/birthday.html
>    - layouts/event/single.html
>    - layouts/**events**/single.html
>    - layouts/_default/single.html

But https://gohugo.io/content-management/types/#create-a-type-layout-directory quotes:

> Create a directory with the name of the type in /layouts. For creating these custom layouts, **type is always singular**; e.g., `events` => `event` and `posts` => `post`.

This contradicts the above lookup order example.. should that **type is always singular** statement be removed? Did that apply some time in the past but not anymore?

@bep?

---

Ref: https://github.com/gohugoio/hugoDocs/pull/520#issuecomment-404303851

/cc @pgilad

**Comment by jmooring** [comment]
This was resolved with https://github.com/gohugoio/hugoDocs/commit/a9d0e7c6812b490b3ce2a7e8125b399a453e6311
