### ISSUE TITLE
Functions should live in namespaces (sub-sections)

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#53]

**Comment by rdwatters** [comment]
While I'm at it, what are you thinking for methods v functions? Should `methods` be its own namespace?

**Comment by bep** [comment]
>Should methods be its own namespace?

I have not thought this entirely, but the thing is, **methods have a natural namespace in its receiver** (i.e. `Page`, ´Shortcode` etc.) so they should somehow live there. 

So there is:

```bash
Site
   GetPage
Shortcode
  Get
Math
   Add
```

Eetc.

**Comment by bep** [comment]
The above will also clean up some of the confusion in the `variables` sections, which is also a messy mix of fields and methods.

**Comment by rdwatters** [comment]
I'll likely add a front matter field as well, since this could be seen as metadata, which makes more sense to have travel with the content itself. I'll defer to you on what your thoughts are for the list page (i.e. quick reference). 

Any place other than [here](https://github.com/gohugoio/hugo/blob/master/docs/data/docs.json#L286) I should be looking? 

> variables sections, which is also a messy mix of fields and methods.

If you can help me identify which ones need to be moved, I'll do my best to make the "mess" even smaller...

**Comment by bep** [comment]
No, it does not belong in front matter field. It should be a section and the section should have a title.

**Comment by rdwatters** [comment]
I was planning on doing both since I find more structured content usually means more flexibility. That said, is my link above the best place for me to find these values? https://github.com/gohugoio/hugo/blob/master/docs/data/docs.json#L286

A preemptive "thank you" for your input.

**Comment by digitalcraftsman** [comment]
We should also work on the following:

- [ ] create aliases for the urls so old links get redirected
- [ ] let file names correspond to the function name while staying consistent re. capitalization, usage of hyphens etc.
- [ ] the same applies for tthe page titles of the documented functions

**Comment by bep** [comment]
@digitalcraftsman I suggest that, instead of creating lots of single issues, that someone **just fixes this issue.**  The issue factory going on is just creating a false sense of progress, and is filling up my notification box. 

And by fixing this issue he/she should also integrate the JSON that exists with a complete list of templatef funcs -- and then do a check that every func has a content file.

**Comment by digitalcraftsman** [comment]
I'm currently working on the a reorganization of the function section in the docs. Mainly I want to organize functions based on their namespace.

I can understand that the issues create noise in your inbox. On the other hand they act as reminder (for me). Do you have suggestions / alternatives?

**Comment by rdwatters** [comment]
> And by fixing this issue he/she should also integrate the JSON that exists with a complete list of templatef funcs

Are you talking about just a manual check or by "integrate" do you mean using the auto-generated json file as part of the template for a single function page?

**Comment by bep** [comment]
I mean 

1) Move the current markdown files down to namespaces.
2) Match all the current against the JSON file and make sure the name and namespace matches
3) Create MD files for the remaining.

And by doing the above, you lay the ground work (namspace + name used in matching) can be used for creating a shortcode that uses the example etc. But that is outside the scope of this issue.

**Comment by digitalcraftsman** [comment]
What Bjørn Erik describes is what I planned.

**Comment by davidsneighbour** [comment]
What's the status of this ticket? Isn't the following part what is needed?

https://github.com/gohugoio/hugo/blob/master/docs/data/docs.json#L2662

**Comment by Wuzzy2** [comment]
I have written a nicely-formatted list of suggested categorization here:

#1550
