### ISSUE TITLE
Add `.Site.Home` to Site Variables list

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugoDocs#539]
`.Site.Home` is used in several examples throughout the doc but not listed in the [Site Variable List](https://gohugo.io/variables/site/#site-variables-list)

I understand it is a very handy alternative to `.GetPage` to use the Homepage object in the templates.

Anybody knows what it returns if no homepage's md is found? @kaushalmodi @bep? Seems like a page object with empty values (except for kind), am I right is there something I need to know?

**Comment by bep** [comment]
I will always return the home page.
