### ISSUE TITLE
Document FirstSection

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugoDocs#542]
- https://github.com/gohugoio/hugo/commit/c790029e1dbb0b66af18d05764bd6045deb2e180
- https://discourse.gohugo.io/t/panic-error-with-getpage-in-hugo-0-45/13116/4?u=kaushalmodi

**Comment by kaushalmodi** [comment]
Nevermind, this was reverted in https://github.com/gohugoio/hugo/commit/179de5f5bc0336c9c279e851ea13202b7ffe572e#diff-6b8113e8ab9139239550a6f7fb81c3f4.

/cc @onedrawingperday

**Comment by kaushalmodi** [comment]
.. and it's back :D https://github.com/gohugoio/hugo/commit/016dd4a69a765061bb3da8490d3cac6ec47a91eb

**Comment by jmooring** [comment]
This was resolved on May 3, 2019 with https://github.com/gohugoio/hugoDocs/commit/e08be4d81efd30542172ce0548f7b2139f7c23d9.
