### ISSUE TITLE
Document templates.Exists (Hugo 0.46)

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#552]
https://github.com/gohugoio/hugo/commit/0ba19c57f180c33b41c64335ea1d1c89335d34c0

**Comment by regisphilibert** [comment]
Can you confirm the parameter is the filepath relative to the `layouts/` directory like the examples below:

```
{{ if templates.Exists "partials/post/banner.html" }}
{{ if templates.Exists "shortcodes/notice.html" }}
{{ if templates.Exists "post/single.amp.html" }}
```

**Comment by bep** [comment]
Yes.

**Comment by bep** [comment]
>Can you confirm the parameter is the filepath

To be precise, it is the Unix path. I.e. Windows slashes will not work.
