### ISSUE TITLE
Unreachable pages (too many redirects)

### ISSUE THREAD

**Issue by luistar** [gohugoio/hugoDocs#555]
Some pages in the docs ([content-management/multilingual](https://gohugo.io/content-management/multilingual/), [content-management/toc](https://gohugo.io/content-management/toc/), [variables/page](https://gohugo.io/variables/page/) and maybe others) are currently stuck in a `301` redirect loop.

Sorry if this doesn't belong here, I didn't know where else to report it.

**Comment by brentybh** [comment]
and also [templates/introduction](https://gohugo.io/templates/introduction/)
