### ISSUE TITLE
Add default Related Content configuration

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugoDocs#567]
Following [this thread](https://discourse.gohugo.io/t/getting-started-with-related-content/13610/2)

As per the doc:

> Hugo provides a sensible default configuration of Related Content, but you can fine-tune this in your configuration, on the global or language level if needed.

I'm wondering what the default related configuration is and propose adding to the doc so users can determine if their project needs its own or not.

**Comment by peterkappus** [comment]
Thanks both, I've submitted a draft PR with a couple of new sentences to, hopefully, cover this: https://github.com/gohugoio/hugoDocs/pull/572 Feedback and enhancements welcome.

**Comment by regisphilibert** [comment]
I think following https://github.com/gohugoio/hugoDocs/commit/19e900a17e75cc6c8202d22dafeb4257ee9d6303 this issue is covered.

**Comment by peterkappus** [comment]
Yep, your re-work looks terrific, @regisphilibert. I noticed one small tweak (I think`name: weight` should be `name: date`) but otherwise perfect. Thanks for doing this!

**Comment by peterkappus** [comment]
@regisphilibert, I've just gone ahead and opened PR #582 for this tiny tweak. Hope it's useful.

**Comment by regisphilibert** [comment]
Just merged it! Thanks for catching this!

**Comment by peterkappus** [comment]
Anytime! Thanks for doing the hard stuff 😄

**Comment by regisphilibert** [comment]
https://github.com/gohugoio/hugoDocs/commit/19e900a17e75cc6c8202d22dafeb4257ee9d6303
