### ISSUE TITLE
ToC doc page should mention h6 bug

### ISSUE THREAD

**Issue by Isigiel** [gohugoio/hugoDocs#576]
On https://gohugo.io/content-management/toc/
The note right at the start should be extended by the info, that a h6 t the start of an article will result in a breakdown of the ToC functionality.
Since this is a known but not very well documented issue.

**Comment by kaushalmodi** [comment]
Ref: https://github.com/gohugoio/hugo/issues/5104

**Comment by kaushalmodi** [comment]
@Isigiel Can you provide a little Markdown example that I can use to reproduce this issue?
