### ISSUE TITLE
Do we need highlight.js for HugoDocs?

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugoDocs#577]
While fixing https://github.com/gohugoio/hugo/issues/5108, I read that:

> The Hugo docs use a version of [highlight.js](https://highlightjs.org/) with a specific set of languages.

Among the listed languages for hljs, I see langs like toml, yaml, etc. which Chroma supports pretty well.

Aren't we at a stage where we can reply completely on Chroma?

**Comment by bep** [comment]
>Aren't we at a stage where we can reply completely on Chroma?

Yes.
