### ISSUE TITLE
QuickStart Guide - Step 8. Customize robust theme - "url(...)" not evaluating

### ISSUE THREAD

**Issue by kebno** [gohugoio/hugoDocs#58]
I am following the docs current as of today (18 July 2017).

When the quickstart instructs to create `layouts/_default/li.html` and paste in code, the rendered result does not have a proper URL for the image. 

I have an image in `static/images/default.jpg` as well as one in  `themes/hugo_theme_robust/static/images/`. 

---

```
<article class="li">
  <a href="{{ .Permalink }}" class="clearfix">
    <div class="image" style="background-image: url({{ $.Site.BaseURL }}images/{{ with .Params.image }}{{ . }}{{ else }}default.jpg{{ end }});"></div>
  </a>
</article>
```

<img width="881" alt="screen shot 2017-07-18 at 3 39 21 pm" src="https://user-images.githubusercontent.com/1569364/28342888-62209d20-6bcf-11e7-82e7-34c73395a0a0.png">

**Comment by bep** [comment]
This quick start has now been rewritten.
