### ISSUE TITLE
Installation instructions for OpenBSD inaccurate, package does not exist.

### ISSUE THREAD

**Issue by Seep1959** [gohugoio/hugoDocs#580]
https://gohugo.io/getting-started/installing/
> OpenBSD provides a package for Hugo via pkg_add:
> `doas pkg_add hugo`

The package does not exist in OpenBSD 6.1, 6.2, or 6.3 repos.

**Comment by wondratsch** [comment]
It is in OpenBSD -current. Please wait for OBSD 6.4.

**Comment by wondratsch** [comment]
OBSD 6.4 has arrived. This Issue should be closed.
