### ISSUE TITLE
Update installing docs to follow the instructions from README.md

### ISSUE THREAD

**Issue by biancarosa** [gohugoio/hugoDocs#591]
The installing docs doesn't seem to be updated. [This issue](https://github.com/gohugoio/hugo/issues/5151) also explains the problem. 

The file located at `docs/content/en/getting-started/installing.md` should be updated to follow the `Fetch from GitHub` instructions exactly like [this README](https://github.com/gohugoio/hugo/blob/master/README.md).

**Comment by felicianotech** [comment]
This issue has been resolved in: https://github.com/gohugoio/hugoDocs/pull/611
