### ISSUE TITLE
site-hierarchy.svg: taxonomy branch shows wrong values

### ISSUE THREAD

**Issue by 251** [gohugoio/hugoDocs#60]
In taxonomy tree on the right side the node on the left branch states `Term 1; Lists 1,3,4,5` but has leaves 1, 3, 5, 6.

**Comment by rdwatters** [comment]
Ha. Nice catch. Thanks @251 I'll fix this :smile:

**Comment by jmooring** [comment]
This was fixed with https://github.com/gohugoio/hugoDocs/pull/1149.
