### ISSUE TITLE
Hugo gopher overlapping hugo install instructions

### ISSUE THREAD

**Issue by zwbetz-gh** [gohugoio/hugoDocs#604]
On the homepage of https://gohugo.io/ under the "Install in seconds, build in milliseconds." section, the hugo gopher is overlapping with the section about installing hugo on different platforms.  See this screenshot. 

![2018-09-14_12-16-33](https://user-images.githubusercontent.com/37317628/45565190-7a934d80-b818-11e8-9990-31a60e62b904.png)

**Comment by zwbetz-gh** [comment]
This is only happening for me in Chrome 69.0.3497.92, Firefox 61.0.1, and Safari 11.1. It looks fine in IE 11 funny enough.

**Comment by zwbetz-gh** [comment]
@bep That fixed it for now

**Comment by bep** [comment]
OK, I will add the "--minify" flag to the Hugo server in a few days, so it's easier to check this locally.
