### ISSUE TITLE
How to get a value from a map?or how to know a key in a map list?

### ISSUE THREAD

**Issue by mycad** [gohugoio/hugoDocs#606]
my data fold has a file named future.yml, the content as bellow:
- 39-6534: 39-0000
- 39-5136: 39-0001
- 39-5174: 39-0002
- 39-4682: 39-0003

How could I get 39-0000 by 39-6534? or let me know the yml has 39-6534?

**Comment by kaushalmodi** [comment]
This discussion belong in https://discourse.gohugo.io/. Please start a new thread for this question there.
