### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by alexivkin** [gohugoio/hugoDocs#609]
The latest change in shortcodes/code broke the build: 
hugo Static Site Generator v0.48-DEV-1977B18
Go 1.11

hugo serve:
Failed to add template "shortcodes/code.html" in path "shortcodes/code.html": template: shortcodes/code.html:9: unexpected "=" in operand
ERROR 2018/09/18 23:18:56 shortcodes/code.html : template: shortcodes/code.html:9: unexpected "=" in operand

changing = to := fixes the issue

**Comment by bep** [comment]
You need to build with Go 1.11, or use Hugo 0.48 release binary.

**Comment by alexivkin** [comment]
That's exactly what I am using - and I wrote as much in the text of the issue above
What are you using to build it?

**Comment by kaushalmodi** [comment]
@alexivkin I cannot reproduce your error. Please continue the debug discussion on Hugo Discourse.

I get:

```

                   | EN  | ZH
+------------------+-----+-----+
  Pages            | 534 |  23
  Paginator pages  |   1 |   0
  Non-page files   |  40 |   0
  Static files     | 167 | 167
  Processed images |  88 |   0
  Aliases          |  15 |   4
  Sitemaps         |   2 |   1
  Cleaned          |   0 |   0

Total in 2814 ms
```

**Comment by bep** [comment]
@kaushalmodi the Hugo version isn't very important here -- the main problem is the GO VERSION. But let's continue this ... somewhere else.

**Comment by kaushalmodi** [comment]
> the main problem is the GO VERSION

Yes, I guess is that he build 0.48-DEV using Go 1.10 and *then* update Go.. just theory. The reason I asked him to use the 0.48 release is that it will circumvent that user error.

**Comment by alexivkin** [comment]
You are right, 0.48-Dev was compiled with 1.10.3. It came from a snap and that's the latest they have in the snaps.
