### ISSUE TITLE
Add *some* highlighting

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#61]
OK, so we now have some syntax highlighting that looks consistent -- but there are some longish template examples that would benefit with some syntax colours.

I suggest we

1) Remove the language tag on all examples (search replace)
2) Enable `Pygments`
3) Add `html` on the _selected few_ examples.

Pygments does a fairly good job with Go template code:

http://bepsays.com/2017/07/19/highlight-test/

There are probably also some other styles that will do even better. 

/cc @budparr @moorereason @rdwatters

**Comment by rdwatters** [comment]
Cool by me as long as it still works on the code shortcodes I built and doesn't kill build times, but I trust your expertise in these matters @bep. I know very little about pygments. 

If the idea is to remove the code shortcodes altogether&mdash;and I'm not sure if this is what you're suggesting or not&mdash;it's a common design pattern in documentation, and I like the added convenience.

Nevertheless, if there are changes that might affect future authors, I'll make the updates to the contribution page of the docs: http://gohugo.io/contribute/documentation/#add-code-blocks

**Comment by bep** [comment]
We'll handle the code shortcode fine, and it will not kill build time.  Browsing through the doc there isn't too many places that really need highlighting.
