### ISSUE TITLE
"Code Toggle" entry missing from left hand menu

### ISSUE THREAD

**Issue by rootkea** [gohugoio/hugoDocs#612]
On expanding "Getting Started" one doesn't see "Code Toggle" entry in the left hand menu but "[Getting Started Overview](https://gohugo.io/getting-started)" shows "Code Toggle" page snippet.

Please see the attached screenshot.
![hugo](https://user-images.githubusercontent.com/2694559/45815229-8a52dc00-bcc7-11e8-87b7-b18b25c2cce5.png)

**Comment by bep** [comment]
Thanks, but that is "by design". The Code Toggle page was added as a playground to test out the Code Toggle shortcode. That shortcode is part of the Hugo site -- and is not a Hugo internal shortcode. But that shortcode's source is in the docs repo, if you want to look.

**Comment by bep** [comment]
Also see https://github.com/gohugoio/hugoDocs/commit/e5e98b950ca631c3135ac2f4446c79d71d2196be

**Comment by cdyson37** [comment]
The right (">") arrow on the right hand side of the [Directory Structure](https://gohugo.io/getting-started/directory-structure/) page links to "Code Toggle", which is confusing when it's not in the contents on the left hand side.
