### ISSUE TITLE
error calling len: len of type hugolib.PageGroup

### ISSUE THREAD

**Issue by mycad** [gohugoio/hugoDocs#613]
my code is:
```
{{ range $index, $pagesByYear:=.Site.RegularPages.GroupByDate "2006" }}
                        {{len $pagesByYear}}
 {{ end }}
```

**Comment by onedrawingperday** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/). GitHub issues are used only for bugs and enhancements. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
