### ISSUE TITLE
Remove/update dead link

### ISSUE THREAD

**Issue by rootkea** [gohugoio/hugoDocs#626]
https://gohugo.io/content-management/cross-references has text "More information about document unique identifiers and headings can be found [below](https://gohugo.io/content-management/cross-references#hugo-heading-anchors)."

The link with text "below" is not valid.

**Comment by kaushalmodi** [comment]
See https://github.com/gohugoio/hugoDocs/pull/629#issuecomment-429405225.

The link is dead because it's pointing to a section that seems to be removed by mistake. 

Instead of removing that link, the section needs to be restored.

**Comment by jacebenson** [comment]
I added the section back in a PR.  We'll see if it's merged.

**Comment by jacebenson** [comment]
Can this be closed?

**Comment by davidsneighbour** [comment]
Can be closed because right now it works in a logical sense on that page in question and I am allergic to old issues.
