### ISSUE TITLE
Example missing/incomplete

### ISSUE THREAD

**Issue by rootkea** [gohugoio/hugoDocs#627]
https://gohugo.io/content-management/menus/#nesting says "In this example, the top level of the menu is defined in your [site `config` file](https://gohugo.io/getting-started/configuration/). All content entries are attached to one of these entries via the `.Parent` field."  

But there is no example following the quote.  

Even if we assume the example `config` specified in just previous topic "Add Non-content Entries to a Menu" is the one being  referred here in "Nesting", the said file lacks the `.Parent` field.

**Comment by abdelmomen19852** [comment]
`.Parent` field
