### ISSUE TITLE
Link RSS feeds

### ISSUE THREAD

**Issue by digitalcraftsman** [gohugoio/hugoDocs#64]
Currently, a lot of users will not note the presence of an RSS feed for certain sections in the docs. The news section is likely the most interesting one for users due to the release notes etc.

The RSS feed could be linked in the top right corner next to the Twitter icon or maybe somewhere in the footer.

Discussed in https://discourse.gohugo.io/t/rss-for-official-hugo-blog/7502/

**Comment by thewebmastercom** [comment]
It is also worth adding the rel alternate link in the header so feed readers can pick up the RSS feed when the main url is used.
