### ISSUE TITLE
Complete examples for hugo-pipes, bundling etc

### ISSUE THREAD

**Issue by cottrell** [gohugoio/hugoDocs#640]
I do not see any complete examples of this stuff. Will update the docs if there is some. Cloning the docs and grepping for resources.Get shows only the docs verbatim text. And it is not in the theme.

**Comment by kaushalmodi** [comment]
What kind of examples are you looking for? We have:

- https://gohugo.io/hugo-pipes/
- https://gohugo.io/content-management/page-bundles/

Please add specifics on what's not clear from the existing docs.

**Comment by cottrell** [comment]
Regis Philibert pointed me to an example which basically answered my question: 

https://github.com/regisphilibert/rp_hugo_theme/blob/b5755a167fa4137e5359f90ff85b36b826b5c5d8/layouts/partials/assets/scratch.html

The filename and path are effectively removed from the docs. It is probably obvious where to put this for some folks but not everyone, especially if you have jumped straight from basic-usage to that spot like me :)

**Comment by kaushalmodi** [comment]
Copying @regisphilibert as he would better know the context of how the docs can be improved for this particular case.

**Comment by cottrell** [comment]
I can jam something in if you want, but sometimes having a random person edit the docs isn't great. 

To be super specific, the only thing missing to that section of the docs was exactly where (what files/location) you put the template lines like:

    {{ $style := resources.Get "sass/main.scss" }}

For example, I think $style needs to be defined wherever you use this.

**Comment by regisphilibert** [comment]
Not sure about this. 

The doc provides one simple HTML example in the Pipes' [introduction](https://gohugo.io/hugo-pipes/introduction/#go-pipes) and I thought this was plenty. I may have been wrong.

> To be super specific, the only thing missing to that section of the docs was exactly where (what files/location) you put the template lines like:
`{{ $style := resources.Get "sass/main.scss" }}`
For example, I think $style needs to be defined wherever you use this.

Variables being limited to one template file is really basic Go Template. Specifying this in the Hugo Pipes' doc would make it sound like this is Pipes' specific. It is not. 
This would also imply that every article of the doc using variables in its code blocks should remind user they cannot use them across multiple template files.

I think the Hugo documentation, as well as any doc, should approach the theory, give some basic keys to the users for them to start with and let other medias take care of detailing more complex use cases and implementations. As a result Hugo docs often mention tier writings when it complements one of its features. This could be the path to take here.

**Comment by bep** [comment]
I agree with @regisphilibert on this.

**Comment by cottrell** [comment]
One thing I have been noticing with the docs, is that it is not easy to tell when an example is actually 100% complete and when it is merely a sketch. Basically Hugo is super easy and fast to use and iterate one *when you start with an example that you have working*. The downside of that is, as a doc reader/learner, I kind of come with the expectation of being able to copy/paste most examples and iterate on that. It is not always immediately clear what the copy/paste/iterate step is from the docs. Likely having a full file path on top of the example code snippets might go a long way for new people reading it?

Hopefully this is not coming across as critical of the docs or tool, I'm kind of buying in to Hugo and hoping the feedback on the docs is useful one way or another and leads to more usage and more buy in!
