### ISSUE TITLE
Remove unused files below /static

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#65]
There seem to be some unusded CSS etc. Probably due to a imperfect merge.

**Comment by rdwatters** [comment]
This seems like a reasonable place to ask the question of where to keep additional design assets; e.g.; my affinity designer files when I recreated the Hugo theme, or any other additional Illustrator, etc files used. Do you have a preference @bep?

**Comment by bep** [comment]
I have in my own personal projects put those below /work -- which sounds reasonable.

**Comment by anthonyfok** [comment]
There were some files that I decided not to remove in PR #456, especially the various "Made with Hugo" or "Powered by Hugo" logos:

* static/share/powered-by-hugo.png
* static/share/made-with-hugo-long-dark.png
* static/share/powered-by-hugo-long.png
* static/share/made-with-hugo-long.png
* static/share/made-with-hugo-dark.png
* static/share/powered-by-hugo-dark.png
* static/share/powered-by-hugo-long-dark.png
* static/share/made-with-hugo.png
* static/share/hugo-tall.png

though these are not exposed by the current new Hugo website design yet.  Not sure what to do with them yet, hehe.
