### ISSUE TITLE
Example: Get unique tags/categories

### ISSUE THREAD

**Issue by akshaybabloo** [gohugoio/hugoDocs#650]
Add an example to get unique tags/categories of a page.

See https://discourse.gohugo.io/t/get-all-unique-taxonomies-of-a-page/14431 for more information.

**Comment by akshaybabloo** [comment]
Any update on this?

**Comment by jmooring** [comment]
The related forum discussion is _not_ about displaying a specific taxonomy's terms used on a page. That's trivial with the `.GetTerms` method on `.Page`, and is already documented [here](https://gohugo.io/templates/taxonomy-templates/#example-list-tags-in-a-single-page-template).

Instead, the forum discussion is about displaying a specific taxonomy's terms used in a section. This is an uncommon request, so I see no need to include an example in the documentation.

I think that's better suited to a tips and tricks forum topic:
<https://discourse.gohugo.io/t/displaying-terms-from-a-specific-taxonomy-used-in-a-sections-pages/41490>
