### ISSUE TITLE
Document collections.Complement (Hugo 0.51)

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#658]
Note that I'm happy to do it myself, but I need to come up with a good usage example.

**Comment by kaushalmodi** [comment]
One example: For a page with series taxonomy, show Related posts such that they do not have the same series taxonomy value. 

E.g. If I am on a post of series "Making Foo", don't include other "Making Foo" posts in Related (because I have a separate "same series" post navigator).
