### ISSUE TITLE
yaml/toml/json toggle for front matter page not working

### ISSUE THREAD

**Issue by zwbetz-gh** [gohugoio/hugoDocs#668]
Doc page: https://gohugo.io/content-management/front-matter/

See below screenshots:

![2018-11-19_22-12-16](https://user-images.githubusercontent.com/37317628/48751190-a41d8a80-ec48-11e8-9571-aece4fdff0b5.png)

![2018-11-19_22-12-43](https://user-images.githubusercontent.com/37317628/48751195-a7b11180-ec48-11e8-8236-a0ba47cdbb59.png)

![2018-11-19_22-12-46](https://user-images.githubusercontent.com/37317628/48751201-aaac0200-ec48-11e8-80ac-7b3bfb671318.png)

**Comment by peaceiris** [comment]
I got the same symptom.

**Comment by peaceiris** [comment]
@zwbetz-gh It was merged, please close this.
