### ISSUE TITLE
Duplicate shortcodes in hugoDocs vs theme

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#67]
https://github.com/gohugoio/hugoDocs/tree/master/layouts/shortcodes being one recent example.

* It is kind of clumsy to have to edit to repos to make simple changes (makes PRs hard to do)
* But we can not maintain two versions of the same shortcode

When removing one of them, please make sure you keep the most recent.

**Comment by rdwatters** [comment]
D'oh. Didn't realize we let duplicates slip in. I want to say @budparr and I chatted about this when he released the first version of the theme to the team. We decided they should live only in the project and not in the theme...if my memory serves? Mind confirming, Bud?

**Comment by budparr** [comment]
While I'd generally say keep them in the theme, it seems like it'd would be more convenient for contributors to have them in the content repo, and not in the theme, being that they're tightly linked to content.

**Comment by bep** [comment]
This relates to https://github.com/gohugoio/hugoDocs/issues/69

Right now it is near impossible in a simple way create a PR that contains changes in both docs site and theme. We need to fix that.

**Comment by kaushalmodi** [comment]
So this issue got solved when gohugoioTheme started being added as a subtree to both doc and theme sites..
