### ISSUE TITLE
"Hugo sites" vs theme

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#69]
Right now we have two web sites sharing a theme as a submodule.

Which isn't too grand if you want to create a fix/feature/PR that has changes in both.

3 options, none perfect:

1) Hugo website mono repo

```
/hugoSites
   /hugoDocs
   /hugoThemesSite
   /gohugoioTheme
```

2)  Make gohugoioTheme into a Git subtree and do two-way merges

3) Keep it as is.

**Comment by kaushalmodi** [comment]
So this issue got solved when gohugoioTheme started being added as a subtree to both doc and theme sites..
