### ISSUE TITLE
Fix the go get install instructions

### ISSUE THREAD

**Issue by digitalcraftsman** [gohugoio/hugoDocs#7]
Explaing the usage of govendor to vendor dependencies.

**Comment by galopin** [comment]
It's probably time to include the updated § Vendored Dependencies section in [`CONTRIBUTING.md`](https://github.com/gohugoio/hugo/blob/master/CONTRIBUTING.md#vendored-dependencies) document as `govendor` was just dropped in favor of [Go Dep](https://github.com/golang/dep).

**Comment by kaushalmodi** [comment]
Looks like this is fixed now :)

https://gohugo.io/getting-started/installing#source
