### ISSUE TITLE
Document author and copyright configuration settings

### ISSUE THREAD

**Issue by zombiezen** [gohugoio/hugoDocs#704]
The [All Configuration Settings](https://gohugo.io/getting-started/configuration/#all-configuration-settings) section does not mention the `copyright` setting or the `[author]` section that is used for [RSS configuration](https://gohugo.io/templates/rss/#configure-rss).

I'm happy to send a PR for this, but I'm unclear if these settings are only used for RSS or whether they impact other aspects of site generation.

**Comment by zombiezen** [comment]
This is still important to document for the reasons above.

**Comment by invzhi** [comment]
I also noticed. It seems that no one wants to fix it.

**Comment by zombiezen** [comment]
Still relevant.

**Comment by zombiezen** [comment]
Still relevant.

**Comment by davidsneighbour** [comment]
What exactly keeps you from sending a pull request?

**Comment by zombiezen** [comment]
I don't know what else in the Hugo codebase reads from the copyright or author settings, if anything. It appears to be just the RSS bit, but I don't know for sure, and I don't want to write documentation that contains omissions.

**Comment by sasvdw** [comment]
I've somehow stumbled on a [this discussion](https://discourse.gohugo.io/t/how-to-configure-and-use-site-author/3682/10) that mentions how to provide per-author configuration files. Sadly this isn't documented anywhere so any documentation would be better than nothing @zombiezen . I'm sure if you put together a PR and submit it the maintainers will provide you with feedback even if you might not have the full context of how everything relates to the rest of the codebase.

**Comment by zombiezen** [comment]
Still relevant AFAIK, but I don't have the time to do the research for this.
