### ISSUE TITLE
Improve theme website landing page to give more room to theme components

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugoDocs#710]
Couldn't find a way to add an issue (other than theme submision) to the theme repo so I cautiously drop tihs one here.

The theme website was built to promote theme components which gives a distinctive "look" to your Hugo project, the only component there was at the time only refered to as "theme".
As a result its landing page is a grid of themes, presenting a screenshot, which is the most effective way to present those kind of components.
But another form of component, introduced this year, which has very limited impact on your project's style or skin (shortcode bundle, service component, seo component etc...) cannot be presented with a screenshot without getting lost in the grid.

To improve this we could:
1. limit the landing page's themes to a curated list of components and allow visitors to browse the others using filters including an **all** button
2. Split the landing page into two part. First one listing images of full fledge themes, second one below, listing, in a different way, more textual maybe,  components which do not really fall into the "theme" category.

**Comment by bep** [comment]
I have on my "todo list" (that gets longer by the day) to improve on the "dependency management" for themes/components ... That said, we can and should do this before then.

I kind of like the idea that everyone can showcase their theme on this site. With the number of new themes coming in, we may possibly have to add some "quality threshold" eventually.

But it makes it hard to find a good theme. There are probably around 20-30 themes that we could pull out and mark as "curated" and list on the front page.

**Comment by bep** [comment]
We could probably do 1) first (as that should be more obvious)
