### ISSUE TITLE
CSV file can’t be reached

### ISSUE THREAD

**Issue by peaceiris** [gohugoio/hugoDocs#717]
At [/content/en/templates/data-templates.md](https://github.com/gohugoio/hugoDocs/blob/master/content/en/templates/data-templates.md)

http://a-big-corp.com/finance/employee-salaries.csv can't be reached.

**Comment by kaushalmodi** [comment]
> can't be reached.

That's because that's just an example, not a real URL.

**Comment by peaceiris** [comment]
@kaushalmodi Thanks.
