### ISSUE TITLE
Shorten "Found no layout file" warning

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugoDocs#721]
Following https://discourse.gohugo.io/t/error-warning-for-missing-template-that-does-exist/15287

I personally tend to think this warning is a bit verbose, so verbose that I suspect most people miss its meaning despite its helpfulness and don't address it.

I suggest it is reduced to simply mention the output format and page kind concerned:

```
WARN 2018/11/13 18:54:15 Found no layout file for output format "JSON" on "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
```

**Comment by kaushalmodi** [comment]
Why not just close the issue? :)

**Comment by regisphilibert** [comment]
Of course 🤦‍♂️ ! Thanks @kaushalmodi
