### ISSUE TITLE
Missing page in docs

### ISSUE THREAD

**Issue by cfq20** [gohugoio/hugoDocs#734]
The [CLI](https://gohugo.io/commands/) menu item in the [Documentation](https://gohugo.io/documentation/) takes you to a missing page when clicked.

![cli](https://user-images.githubusercontent.com/11352192/52045222-570d3d00-2544-11e9-941f-3dd6ddd78001.png)
.

**Comment by bep** [comment]
Hmm ... So, I re-generated the CLI docs yesterday, and the `date` was then reset to `2019-01-30`; which I assume, because of the time zone difference, Netlify had not reached yet ... It is fixed now, thanks for the heads up.
