### ISSUE TITLE
"This recording has been archived" messages in quick start page

### ISSUE THREAD

**Issue by bboreham** [gohugoio/hugoDocs#735]
When I visit https://gohugo.io/getting-started/quick-start/ I see multiple instances of this message:

> This recording has been archived
> All unclaimed recordings (the ones not linked to any user account) are automatically archived 7 days after upload.

**Comment by peaceiris** [comment]
This is an error of https://github.com/gohugoio/hugoDocs/blob/master/layouts/shortcodes/asciicast.html

**Comment by moorereason** [comment]
Should we self-host?  https://github.com/asciinema/asciinema-player/releases

**Comment by kaushalmodi** [comment]
Why not just record the SVGs and host them? https://github.com/nbedos/termtosvg is an awesome tool.

**Comment by peaceiris** [comment]
How about [svg-term-cli](https://github.com/marionebl/svg-term-cli)?

**Comment by bep** [comment]
The reason is simple: I did the recordings without registering. Then they changed their archival policy. I (or someone else) need to re-do the videos, which would be a good exercise since that would indicate that the instructions still work ...
