### ISSUE TITLE
On Mobile in "Use Site Configuration Parameter" section, the tabs come over the navbar

### ISSUE THREAD

**Issue by ankitskvmdam** [gohugoio/hugoDocs#738]
On Mobile in "Use Site Configuration Parameter" section, link: "https://gohugo.io/templates/introduction/", tabs come over the navbar.
I have also attached the screenshot for reference.

![hugo](https://user-images.githubusercontent.com/22586210/52270560-5c64f000-2967-11e9-9df5-9d20073b7e9f.jpg)

**Comment by peaceiris** [comment]
I got the same problem. (iPhone 8, Safari)

This issue should be reported on [gohugoio/gohugoioTheme](https://github.com/gohugoio/gohugoioTheme)

![img_0909](https://user-images.githubusercontent.com/30958501/52271948-7e229f00-2988-11e9-9fb0-ab874bdb2b3c.jpg)

**Comment by ankitskvmdam** [comment]
Ok
