### ISSUE TITLE
Document strings.Contains and other missing strings methods

### ISSUE THREAD

**Issue by XhmikosR** [gohugoio/hugoDocs#739]

**Comment by jmooring** [comment]
Missing from documentation as of September 7, 2020:

- `strings.Contains`
- `strings.ContainsAny`
- `strings.FirstUpper`

**Comment by jmooring** [comment]
When comparing `strings` methods that have been implemented to the current documentation, it may _appear_ as if many are not documented. For example, `strings.Chomp` is not documented, but its mapped alias `chomp` _is_ documented. We're a bit inconsistent about how we documents these methods. I would prefer to document `strings.Method` on a `strings.Method` page, and then reference the alias. But that ship has already sailed...

**Comment by moorereason** [comment]
@jmooring, I had an [ambitious PR](https://github.com/gohugoio/hugoDocs/pull/707) a while back to resolve #53, but I didn't have time (or help from others) to finish it.  I'm open to taking another stab at it if you want to help.

**Comment by bep** [comment]
>  But that ship has already sailed...

Never say never. The problem is, we introduced namespaces a little late in the game ...

And I have silently ignored all of this waiting for some time to implement "pages from data".
