### ISSUE TITLE
Use the range else syntax in examples

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#748]
This is little bit a note to myself, as I did not know the `range` keyword had an `else`:

```
{{range .Pages }}{{ .Title }}{{else}}No pages for you!{{end}}
```

/cc @regisphilibert

**Comment by regisphilibert** [comment]
Saw that on the go template doc a while ago but somehow concluded it dit not work in Hugo for some forgotten reason.

I will try it again.
