### ISSUE TITLE
Fix broken "quick start"

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#75]
See https://discourse.gohugo.io/t/newbie-is-having-major-grief-with-quick-start/7552/2

**Comment by bep** [comment]
I will create a suggested quick start.

**Comment by anthonyfok** [comment]
> I will create a suggested quick start.

This is awesome!  I especially love your use of asciinema and the choice of ananke theme, and the concise and easy-to-understand instructions.  Thank you!

**Comment by bep** [comment]
Thanks. The old one made some sense as an article, but not as a quick start. I guess we will get complaints on this one, too, from Windows users, but having it this short makes it possible to handle.
