### ISSUE TITLE
"HUGO" logo on themes.gohugo.io does not link to gohugo.io

### ISSUE THREAD

**Issue by dittaeva** [gohugoio/hugoDocs#758]
While the HUGO logo in the top left corner in the top menu on all other internal pages on gohugo.io (showcase, documentation, news) link to gohugo.io (the main page), this is not the case on the themes page (themes.gohugo.io) where it links to itself.

Linking to the main page is consistent and useful, but I am not familiar enough with hugo yet to suggest where this should be fixed.

**Comment by darshanbaral** [comment]
Linking https://github.com/gohugoio/hugoThemesSite/issues/60.

Maybe hardcode `https://gohugo.io/` instead of `{{ .Site.BaseURL }}` [here](https://github.com/gohugoio/gohugoioTheme/blob/819d069c2dbef2dbcd847f523e8a0c93cbd2ccda/layouts/partials/site-nav.html#L7)?

**Comment by dittaeva** [comment]
Seems to me this is still an issue that should be fixed. A solution has been proposed by @darshanbaral and the way I understand @digitalcraftsman in [issue #60 on hugoThemesSite](https://github.com/gohugoio/hugoThemesSite/issues/60) changing the URL is desirable. This is perhaps not the correct repository though?

**Comment by darshanbaral** [comment]
Looks like it's addressed now.

**Comment by bep** [comment]
Yea, now the theme is a Hugo Module and included as such in both sites, so should be easier to keep in synch.
