### ISSUE TITLE
Differentiate between Go Template built-in functions and additional Hugo functions

### ISSUE THREAD

**Issue by catanman** [gohugoio/hugoDocs#759]
At the top of the functions doc page (https://gohugo.io/functions/) it says:

> Go templates are lightweight but extensible. Go itself supplies built-in functions, including comparison operators and other basic tools. These are listed in the [Go template documentation](https://golang.org/pkg/text/template/#hdr-Functions). Hugo has added additional functions to the basic template logic.

It sounds like what should follow are the additional Hugo functions but instead there's mix of some built-in Go template functions (but not all of them) and Hugo specific function. 

For example: 

- https://gohugo.io/functions/base64/ is a Hugo function
- https://gohugo.io/functions/le/ is a Go Template built-in with a Hugo doc page
- _len_ is a Go built-in but doesn't have a Hugo doc page

I was thinking it would be helpful to differentiate between the Hugo specific functions and the Go template built-in functions or perhaps only document Hugo specific functions? 

Also I noticed that some functions that appear on the sidebar are missing from the Functions Quick Reference. For example:

https://gohugo.io/functions/shuffle/ appears in the sidebar but not on the quick reference page (https://gohugo.io/functions/).

**Comment by bep** [comment]
Thanks for the input. There are 2 items (at least) to consider thinking about this:

1. We have plans to use the function template namespace with its JSON docs to be the foundation of the template funcs docs tree. @moorereason has done some preliminary work in this department, but suspect that waiting for "pages from data" would make this simpler.
2. From Hugo 0.55 there will be very few Go template funcs that isn't on some level overloaded in Hugo, so I think we can safely document them all similary.

**Comment by moorereason** [comment]
@catanman, I've not updated my PR (#707) since January, but you can take a look at [the Netlify preview](https://deploy-preview-707--gohugoio.netlify.com/functions/) to see if we're heading toward a fix for your concern.
