### ISSUE TITLE
IsSection missing from docs?

### ISSUE THREAD

**Issue by catanman** [gohugoio/hugoDocs#760]
In one of the themes I'm using the _partial/menu.html_ template contains `{{ if .IsSection }}`. I couldn't find _IsSection_ defined anywhere in the docs (admittedly it's pretty obvious).

**Comment by bep** [comment]
The docs for this and others will be clearer when we get Hugo 0.55 (not long!) -- as all page etc. attributes will be defined in interfaces (with method docs).

**Comment by jmooring** [comment]
.IsSection is not present in the documentation.
