### ISSUE TITLE
Document "return" in partial

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugoDocs#794]
We can now return any type from a partial and the world should know (really life changing)

I'll play around with it some more and add a section [here](https://gohugo.io/templates/partials/#readout)

Questions:

Any preference on how to "call" this feature/concept. 
Returning partials vs Outputing partials?

**Comment by bep** [comment]
>Returning partials vs Outputing partials?

How about "partials that return a value".

**Comment by regisphilibert** [comment]
Awesome, I'm playing around with it in order to better understand the limitations if any.

It appears you cannot have the `keyword` twice à la:
```
{{ if eq . 3 }}
  {{ return true }}
{{ else }}
  {{ return false }}
{{ end }}
```
The above will break if the condition fails: `executing "partials/func/return.html" at <return>: wrong number of args for return: want 0 got 1`

My conclusion is that only one `return` statement is allowed for each partial and we should encourage manipulating a variable which is eventually returned:

```
{{ if eq . 3 }}
  {{ $return = true }}
{{ else }}
  {{ $return = false }}
{{ end }}
{{ return $return }}
```

**Comment by regisphilibert** [comment]
I'm wondering if we should not advise against using an output format extension such as `html` or `json` when creating a returning partial and probably use a random one like `.return` or `.data` or whatever.

I think people will want to minimize the argument length by omitting extensions especially as they won't make much sense for returning partials like:
`{{ $featured := partial "GetFeatured" 5 }}` vs `{{ $featured := partial "GetFeatured.html" 5 }}`

What is the behaviour if I have a `partials/GetFeatured.html` and a `partials/GetFeatured.json` in this case ? Do Hugo uses the current output format to resolve the extension?

**Comment by regisphilibert** [comment]
I answered my own question and will add a notice to warn users intending not mention extension.

**Comment by bep** [comment]
>?Do Hugo uses the current output format to resolve the extension?

No. But you kind of want to have an extension to be able to map it to some syntax highlighter support in your editor.

And, only 1 `return` keyword per partial.

**Comment by regisphilibert** [comment]
To the risk of derailing the discussion:
> Do Hugo uses the current output format to resolve the extension?
> No

Then how does it resolve it if not by the current output format, current template extension?
It appears so as from a `.html` template file, Hugo will load `partials/whatever.html` when calling `partial "whatever"`

**Comment by bep** [comment]
for

```bash
{{ partial "foo.bar" }}
```

We first try "foo.bar" then "foo.bar.html" (this is old code that precedes any output format logic).

**Comment by regisphilibert** [comment]
So using `partial "something"` is really limited to partials with the `.html` extension. Good to know thanks!

**Comment by bep** [comment]
>So using partial "something" is really limited to partials with the .html extension

No.

It will first try "something" (without extension).

**Comment by regisphilibert** [comment]
Extensionless partial files... Interesting. I'll leave this aside for now.

**Comment by regisphilibert** [comment]
https://gohugo.io/templates/partials/#returning-a-value

**Comment by bep** [comment]
I think it would also help if you added that you can also use `partialCached`, which I think would make sense in your "get featured" example. Also "$return" makes for a bad variable name.

**Comment by regisphilibert** [comment]
> I think it would also help if you added that you can also use partialCached

Mmm, my view was that people had no reason to assume they could not use `partialCached` with those.

> Also "$return" makes for a bad variable name.
I use `$output` for whatever I'm about to _output_. `$returns` therefor made sense to me.

But I'm curious what you would use to store the value you intend to return or rather what would make a good "example" for the users.

**Comment by bep** [comment]
>But I'm curious what you would use to store the value you intend to return or rather what would make a good "example" for the users.

I like to stick to the rule of having the variable name telling me what it contains. `$name`, `$page` etc.

**Comment by bep** [comment]
>Mmm, my view was that people had no reason to assume they could not use partialCached with those.

Sure, but the example would, in my head, be considered ... sub-optimal without the caching.

**Comment by bep** [comment]
But it doesn't matter, we can improve this later.

**Comment by regisphilibert** [comment]
> Sure, but the example would, in my head, be considered ... sub-optimal without the caching. 

I did not want to confuse first time readers with mentioning a feature (partialCached) which they are unaware of, as this is the last section (and rightly so).

We can take some more time to include this information somehow.
