### ISSUE TITLE
Feature Request: Missing dark theme

### ISSUE THREAD

**Issue by shiftgeist** [gohugoio/hugoDocs#805]
I find it very irritating that https://gohugo.io/documentation/ has no dark theme.
Would love to see it beeing consent/implemented.

**Comment by peaceiris** [comment]
I recommend you to use tools like this:

- [Stylus - Chrome web store](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne)

**Comment by shiftgeist** [comment]
I understand your concern, but this is not what I had in mind. I was thinking more of a color changer. Adding a plugin to the browser is not satisfying.

**Comment by peaceiris** [comment]
"Color changer" is not a top priority and this proposal will be rejected because we have a lot of other problems to solve. Unfortunately, no one has time to implement it.

**Comment by peaceiris** [comment]
"Color changer" is a low-priority feature and this proposal will be rejected because we have a lot of other problems to solve. Unfortunately, no one has the time to implement the changer.

**Comment by shiftgeist** [comment]
I like to help implement this feature. But first we have to agree on a concept.

**Comment by digitalcraftsman** [comment]
Hello @shiftgeist and @peaceiris,

this discussion might be better suited for https://github.com/gohugoio/gohugoioTheme/issues. The hugoDocs repo contains only the content of the Hugo documentation whereas the development of the website theme happens in the gohugoioTheme repo.
