### ISSUE TITLE
Page does not exist / 404 Link: functions/haschildren/

### ISSUE THREAD

**Issue by shiftgeist** [gohugoio/hugoDocs#814]
On https://gohugo.io/variables/menus/ the link ".HasChildren" looks like

```
<a href="/functions/haschildren/">.HasChildren</a>
```

![image](https://user-images.githubusercontent.com/30648730/57183667-88cdd100-6eb0-11e9-8d82-0be1a89f88b7.png)

## https://gohugo.io/functions/haschildren/ ->

![image](https://user-images.githubusercontent.com/30648730/57183672-a7cc6300-6eb0-11e9-90cb-b0d31b768ea7.png)

**Comment by bgguna** [comment]
I can pick up this issue and create a PR. This is going to be my first PR to this community so if anything is incorrect, please shout out.
