### ISSUE TITLE
Function overview is missing a pager

### ISSUE THREAD

**Issue by davidsneighbour** [gohugoio/hugoDocs#838]
1. I go to https://gohugo.io/functions/
2. I scroll down
3. The list of available function (seemingly ordered ASC on title) end at `sha`

I would expect a pager or ALL functions on one page. There is probably a limit of 100 somewhere in the templates/range for this page?

Quick test: `substr` is available in the navigation left, but missing in the page itself.

**Comment by bep** [comment]
I think I vaguely remember a where filter in there somewhere, but you are right, we should fix this
