### ISSUE TITLE
Use a centralized translation system for the documentation

### ISSUE THREAD

**Issue by davidsneighbour** [gohugoio/hugoDocs#858]
I propose using a centralized system to translate the Hugo documentation. 

https://gitlocalize.com/

This system works with markdown files. It needs some configuration but in the end, it would be possible to lead "amateurs" to a website where they can translate parts of the documentation in their own language. 

The system can be configured to commit to branches/pull requests and someone with rights to merge could apply the patches. It should be possible to have an index of how much (%) is translated and translations that are 100% done could be added and shown on the documentation website. If for instance a language is only subpar done it could be added as an alternative to the English "main version". 

As far as I understand the gitlocalize system it will be able to show changed main language parts collects languages as they are done by the users and so on.

And it's free.

**Comment by bep** [comment]
>And it's free.

Nothing is really free. I have spent hundreds of hours setting up Hugo build/test etc. on "free services".

But some times it's worth it.

One quick question: Do they preserve authorship in the commits that ends up on GitHub?

**Comment by davidsneighbour** [comment]
Yes. You log in with your GitHub account and changes done by you appear as your own pull request in the repository.

https://docs.gitlocalize.com/how_to_contribute.html

**Comment by bep** [comment]
OK, but re. what I wrote about this on the Dicsussion forum: We're (or at least I'm not) not ready to handle translation PRs on a very fine grained level into this one repo. Even merging PRs in languages I do understand takes time. Then consider if the same type of PRs flooded in for Chinese, ....

With the next Hugo we can relatively easy partition it into several repos each wit its own trusted editor.

**Comment by davidsneighbour** [comment]
Sounds perfect. I didn't think about modules this way (yet). That's the proper way.

**Comment by bep** [comment]
Yea, making modules work for content had me walking some extra miles to get it right, but it opens up some interesting use cases (at least for ... enterprise use).
