### ISSUE TITLE
no function pages for getJSON/getCSV

### ISSUE THREAD

**Issue by jgreely** [gohugoio/hugoDocs#86]
The getJSON and getCSV functions should be documented in the Functions section, not just on the Data Templates page.

**Comment by rdwatters** [comment]
Yes, they most certainly should. Thanks for the (as always) keen eye, @jgreely :smile:

**Comment by bep** [comment]
But lets fix #53 first.

**Comment by genetikdisoda** [comment]
Does `.GetRemote` deprecate these methods?

**Comment by jmooring** [comment]
@genetikdisoda Please use the forum (https://discourse.gohugo.io/) for questions.

**Comment by genetikdisoda** [comment]
I hate discourse, I am ouuta here either way.

**Comment by bep** [comment]
I'm closing this. We now have a `resources.Get`/  `resources.GetRemote` that replaces these.
