### ISSUE TITLE
quickstart guide: final step doesn't produce static files for post, because post is still draft

### ISSUE THREAD

**Issue by liasomething** [gohugoio/hugoDocs#862]
As per title: the quick start guide https://gohugo.io/getting-started/quick-start/ generates static html with no posts, which is not useful for users.

To fix: either 

1. in Step 7, hugo needs to be invoked as `hugo --buildDrafts`, or
2. in Step 4, the user should be told to set `draft` to `false`

**Comment by clemens-tolboom** [comment]
That will not help as the suggested theme *Anaka* uses **/post/**. See https://github.com/budparr/gohugo-theme-ananke/tree/master/exampleSite/content

The **asciicast** is blocking me to create a PR.

**Comment by rdela** [comment]
Hi Clemens, thanks for commenting, but I think that is a different issue than the one LIA opened this issue about, that drafts did not get built in the old version of the quick start.

**Comment by clemens-tolboom** [comment]
I did the Quickstart again today and did not get any content with `hugo --buildDrafts` until I changed the directory name from `posts` into `post` (which anaka theme uses) so even your ref to #883 was not enough.
