### ISSUE TITLE
Document map/slice methods' current limitations

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugoDocs#863]
After reading @bep  comment in https://github.com/gohugoio/hugo/issues/6105#issuecomment-513575911 I realize we should document those limitations. But first I'd rather we have our facts and our wording straights.

So I'm here asking 3 "top-of-your-head" questions before I get into some testing when time allows:

For me, `uniq` and `intersect` are currently limited to 
- slice of strings
- collection of pages

Is that right? 
Is it the correct wording? 
Is there any other "map/slice" methods subject to such limitations, among `symdiff`, `complement`, `group` (and others?).

I know for a fact that `append` is not affected.

**Comment by bep** [comment]
These functions accept slices that contain comparable types:

https://golang.org/ref/spec#Comparison_operators

So:

* Not a slice of slices
* Not a slice of maps

That could be implemented, of course, but you would then have to compare each element in the slice/map with ...
