### ISSUE TITLE
Clarify deployment authentication

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#878]
![image](https://user-images.githubusercontent.com/394382/62068470-5bd25580-b236-11e9-8f6e-653c0b0a00f7.png)

@vangent re the section above:

Do I have to have the `aws` client installed to deploy locally to deploy to my S3 bucket? The same question applies to others. I understand that these clients can help with the creation of authentication tokens or whatever, but I have always assumed that the Hugo binary should be sufficient. This is esp. important when running in a CI.

**Comment by vangent** [comment]
No, it's not required that you've installed those binaries.

* For GCS, we use default credentials, which include `gcloud auth login` but also a bunch of other alternatives: https://cloud.google.com/docs/authentication/production.

* For AWS, we similarly use default credentials, which include `aws configure` but also a bunch of other alternatives: https://docs.aws.amazon.com/sdk-for-go/api/aws/session/.

* For Azure, we use `AZURE_STORAGE_ACCOUNT` plus `AZURE_STORAGE_KEY` or `AZURE_STORAGE_SAS_TOKEN`, which are (kind of) documented here: https://docs.microsoft.com/en-us/azure/storage/common/storage-azure-cli#azure-cli-sample-script.

I'll improve https://gocloud.dev/howto/blob to be more consistent about linking to those resources.

WDYT about adding a 4th bullet in the list with something like:

* NOTE: Each service supports alternatives for authentication, including using environment variables. See [here][https://gocloud.dev/howto/blob/#services] for more details.

**Comment by bep** [comment]
>WDYT about adding a 4th bullet in the list with something like:

I think that would be great!
