### ISSUE TITLE
Help wanted/needed: Update docs to 0.57

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#888]
Ref. https://github.com/gohugoio/hugo/releases/tag/v0.57.0

Also, see the notes section. There are some significant updates that need docs updates. I would appreciate if someone could lend a hand to get the docs up to date.

**Comment by talktopri** [comment]
@bep Hi! I'm new to Hugo, and I'd love to help with documentation. Any tips on how I can get started and help get this issue fixed?

**Comment by talktopri** [comment]
cc @moorereason too, as I see you were participating here.

**Comment by moorereason** [comment]
Thanks for wanting to help.  I'd go read the release notes linked above and make sure all the new features or significant changes are documented.
