### ISSUE TITLE
Clarify Page Collections

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugoDocs#890]
Since Hugo v.0.57.0 on the homepage `.Pages` now include section lists.

However after auditing the Hugo Themes demos in https://github.com/gohugoio/hugoThemes/issues/682 I am seeing the following:

`.Paginator.Pages` continues to render `.Site.RegularPages` on the homepage as seen [here](https://themes.gohugo.io/polymer/) (relevant template [here](https://github.com/pdevty/polymer/blob/master/layouts/partials/content.html#L4))

~~`.Site.Pages` is the same as `.Site.RegularPages` on the homepage as shown [here](https://themes.gohugo.io/shiori/) (relevant template [here](https://github.com/chibicode/hugo-theme-shiori/blob/master/layouts/index.html#L4))~~ edit: I missed the link to the `posts` section of this theme.

**Comment by bep** [comment]
>.Site.Pages is the same as .Site.RegularPages on the homepage as shown here (relevant template here)

The above isn't correct. `.Site.Pages` returns all page kinds.

**Comment by onedrawingperday** [comment]
>The above isn't correct. `.Site.Pages` returns all page kinds.

Right. Thanks I missed that one.

**Comment by kaushalmodi** [comment]
So the `.Pages` row needs to be renamed to `.RegularPages` and a new row with the new `.Pages` behavior needs to be added: https://gohugo.io/variables/site/#site-pages

*Note to self*

**Comment by bep** [comment]
To recap:

* `.Pages` returns both regular pages and sections, but only the children (one level, even for the home page)
* `.RegularPages` is a new `Page` method that complements what we had on `Site` -- this can be used if you don't love the change introduced above.

`.Site.RegularPages` and `.Site.Pages` behaves as before.

For the paginator, also see https://github.com/gohugoio/hugo/issues/6231
