### ISSUE TITLE
Directory structure for config.toml

### ISSUE THREAD

**Issue by tdelmas** [gohugoio/hugoDocs#893]
On https://github.com/gohugoio/hugoDocs/blob/master/content/en/getting-started/configuration.md it displays correctly:

![image](https://user-images.githubusercontent.com/1955774/63194478-697a3e80-c070-11e9-99ce-0b403ff3e560.png)

But on https://gohugo.io/getting-started/configuration/#configuration-directory the last (production) part is wrong:

![image](https://user-images.githubusercontent.com/1955774/63194502-7f87ff00-c070-11e9-953a-4f2254d8fe8c.png)

**Comment by davidsneighbour** [comment]
The markup in the .md file is correct and the preview on Github looks alright. I think you have discovered an issue with Blackfriday parsing of this markup.

**Comment by bep** [comment]
Fixed by 88fce61784e5cb82860f8b5ee20959e5db0dfe3f
