### ISSUE TITLE
Verify or clarify `.kind` for `taxonomy` vs `taxonomyTerm

### ISSUE THREAD

**Issue by bmackinney** [gohugoio/hugoDocs#902]
https://gohugo.io/templates/section-templates/#page-kinds

taxonomy | A page listing regular pages from a given taxonomy term | page for the term awesome from tags taxonomy (/tags/awesome/index.html)
-- | -- | --
taxonomyTerm | A page listing terms from a given taxonomy | page for the tags taxonomy (/tags/index.html)

Should the table actually say this?

taxonomyTerm | A page listing regular pages from a given taxonomy term | page for the term awesome from tags taxonomy (/tags/awesome/index.html)
-- | -- | --
taxonomy | A page listing terms from a given taxonomy | page for the tags taxonomy (/tags/index.html)

**Comment by kaushalmodi** [comment]
No, what's written is carefully documented and correct.

**Comment by kaushalmodi** [comment]
It was documented especially to clarify what was implemented (I know that it is counterintuitive).
