### ISSUE TITLE
.Site.Files doesn't exist

### ISSUE THREAD

**Issue by yktoo** [gohugoio/hugoDocs#922]
`.Site.Files` referenced [here](https://gohugo.io/variables/site/) does not exist:

> can't evaluate field Files in type page.Site

**Comment by bep** [comment]
https://github.com/gohugoio/hugoDocs/commit/b0db64a032f019027defaf4f6233b5dd9a3759b8

**Comment by yktoo** [comment]
I was actually hoping for an alternative :) Is there any?

**Comment by bep** [comment]
```
{{ $files := slice }}
{{ range .Site.Pages }}
{{ with .File }}
{{ $files = append $files . }}
{{ end }}
{{ end }}
