### ISSUE TITLE
Delete stale branches

### ISSUE THREAD

**Issue by davidsneighbour** [gohugoio/hugoDocs#940]
See title ;) delete them or make them useful. right now we have three "sub"-branches with one commit ahead each. All with at least 100 commits behind, the oldest with 6066 commits behind...

Clean up, people ;) Sorry for being the pusher on this :P

**Comment by bep** [comment]
And why is this a problem?

**Comment by davidsneighbour** [comment]
It's just an OCD thing ;) What are these branches for? Let's solve them.

**Comment by bep** [comment]
* `next` is for "bigger work tasks" that for some reason cannot go live 
* `dev` is probably not needed, but it doesn't hurt anyone.
* And then we have a branch for A/B testing.

These are set up with URLs on Netlify, and even if they're not used on a daily basis, it's convenient to just have them there when you need them.
