### ISSUE TITLE
Restructure "modules" for the gohugo.io sites

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#941]
I'm putting this issue randomly here. I've been postponing this for too long now and we're a little out of sync on several things.

Short story:

Old structure:

* hugoDocs - the theme as a git subtree
* hugo/docs - hugoDocs as a git subtree
* hugoThemeSite - the theme as a git submodule

The big motivation with the above was to get complete and versioned docs in the source archives created by GitHub releases (they do not follow submodules).

When we released Hugo Modules, I updated this repo (hugoDocs) to use the theme as a module, but left the rest as is.

What I suggest we do is:

* hugoDocs - theme as a Hugo module, vendored (`hugo mod vendor`)
* hugo/docs - hugoDocs as a git subtree (unchanged)
* hugoThemeSite - the theme as a Hugo Module (no need to vendor)

Any protests? @onedrawingperday @davidsneighbour @digitalcraftsman @budparr and gang

**Comment by davidsneighbour** [comment]
I don't understand modules yet good enough to have a useful opinion here. My thought was that subtrees or submodules could be replaced by modules from now on. To me, from an educational point, it looks good though if we use various different ways. Could be used later on for documentation in sense of "look at how the theme site is set up to learn more".

**Comment by bep** [comment]
> My thought was that subtrees or submodules could be replaced by modules from now on. 

The above statement is true. And we could use that to load the theme in `hugo/docs` -- but it's kind of nice to have the "full site source" included in the source archive -- esp. if you consider people looking at this 100 years from now when the GitHub tags may be long gone ...

**Comment by bep** [comment]
Note to self:

Theme site + docs site now uses the theme as a module; I will wait with the vendoring until a release.

**Comment by onedrawingperday** [comment]
I just tested a theme submission locally and there is a slight delay while the Build Script is generating the Themes Site:

```
go: finding github.com/gohugoio/gohugoioTheme v0.0.0-20191014144142-1f3a01deed7b
```

I suppose that we will have to learn to live with the new delay, but I just thought that you may want to know about it.

**Comment by bep** [comment]
>I suppose that we will have to learn to live with the new delay,

Not every time. There is a cache in play, so on average, this should be as fast as having it as a Git submodule.

**Comment by bep** [comment]
This is now done.
