### ISSUE TITLE
config.toml:1:1": unmarshal failed: Near line 0 (last key parsed ''): bare keys cannot contain '<'

### ISSUE THREAD

**Issue by dmolpa** [gohugoio/hugoDocs#945]
Hello.

1. Cloned.
2. Installed Go.
3. Pulled a Theme.
4. Started hugo server and got:
Error: "D:\path_to_a_folder\config.toml:1:1": unmarshal failed: Near line 0 (last key parsed ''): bare keys cannot contain '<'

Windows 10 Home.
I am trying to fix a blog after the theme I used broke (hugo-natrium-theme). So I'm looking for anything that would help to figure out how Hugo works. No luck yet.

Thx.

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by alasijia2468** [comment]
把冒号或者尖括号去掉就好了，我的已经好了
