### ISSUE TITLE
Broken External URLs

### ISSUE THREAD

**Issue by coliff** [gohugoio/hugoDocs#953]
I used checkbot.io to scan for broken URLs

URL | Broken links
-- | --
https://gohugo.io/ | https://twitter.com/carriecoxwell/status/948402470144872448
https://gohugo.io/commands/hugo_gen_chromastyles/ | https://help.farbox.com/pygments.html
https://gohugo.io/content-management/syntax-highlighting/ | https://help.farbox.com/pygments.html
https://gohugo.io/getting-started/configuration/ | https://help.farbox.com/pygments.html
https://gohugo.io/hosting-and-deployment/deployment-with-wercker/ | http://devcenter.wercker.com/docs/deploy/s3.html
https://gohugo.io/news/0.10-relnotes/ | http://hugo.spf13.com/extras/highlighting,http://hugo.spf13.com/content/ordering,http://hugo.spf13.com/extras/toc,http://hugo.spf13.com/extras/permalinks,http://hugo.spf13.com/extras/shortcodes,http://hugo.spf13.com/extras/urls,http://hugo.spf13.com/layouts/templatefunctions,http://hugo.spf13.com/layout/rss,http://hugo.spf13.com/content/front-matter,http://hugo.spf13.com/showcase
https://gohugo.io/news/0.13-relnotes/ | http://ace.yoss.si/
https://gohugo.io/news/0.21-relnotes/ | https://github.com/rickyhan
https://gohugo.io/news/0.22-relnotes/ | http://hugotest.bep.is/
https://gohugo.io/news/0.32-relnotes/ | https://github.com/carlchengli
https://gohugo.io/news/0.33-relnotes/ | http://hugotest.bep.is/resourcemeta/
https://gohugo.io/news/0.36-relnotes/ | http://hugotest.bep.is/resourcemeta/smartcrop/
https://gohugo.io/news/0.37-relnotes/ | https://github.com/curttimson
https://gohugo.io/news/0.38-relnotes/ | http://hugotest.bep.is/
https://gohugo.io/news/0.55.0-relnotes/ | https://github.com/larson004
https://gohugo.io/news/0.7-relnotes/ | http://hugo.spf13.com/
https://gohugo.io/news/http2-server-push-in-hugo/ | https://www.netlify.com/blog/2017/07/18/http/2-server-push-on-netlify/

**Comment by bep** [comment]
We're not changing the release notes. I assume that most of the above examples are sites that have existed at some point, but are now removed --so there is nothing to fix (and we're not removing them).

**Comment by coliff** [comment]
I can understand why you wouldn't want to go back and edit old release notes, but for the ones in the current docs then any users clicking on a link which is broken is going to cause frustration - I don't know why you wouldn't want to get them fixed or links removed.
