### ISSUE TITLE
Quick start docs: produces empty page in the browser

### ISSUE THREAD

**Issue by novosibiryak** [gohugoio/hugoDocs#955]
Server reports "found no layout file for html for home" after going through all steps as written.
Tested on Windows 10.

**Comment by clemens-tolboom** [comment]
You probably did not do step 3 completely.

- https://gohugo.io/getting-started/quick-start/#step-3-add-a-theme

**Comment by novosibiryak** [comment]
Figured that out. I was launching the server from the folder that is different from the site home folder
