### ISSUE TITLE
Where do I edit my site after following GitHub hosting?

### ISSUE THREAD

**Issue by richjsouth** [gohugoio/hugoDocs#961]
I followed you instructions on setting up and then deploying to github (my personal one rather than project) but what is the workflow now?  Where do I edit and update my site?  Which of the steps from (https://gohugo.io/hosting-and-deployment/hosting-on-github/) do I need to follow now? A follow-on would be useful as I'm not too familiar with GitHub (I've usted Bitbucket but only for simple source-code storage).

**Comment by peaceiris** [comment]
Now, it is easy to use the GitHub Actions for deploying to the GitHub Pages.

Please refer to my post: [Deploy Hugo project to GitHub Pages with GitHub Actions - tips & tricks - Hugo](https://discourse.gohugo.io/t/deploy-hugo-project-to-github-pages-with-github-actions/20725)

In addition, this repository is not suitable for questions. Please use the above forum.

**Comment by richjsouth** [comment]
Thank you very much. I'll check it out. And sorry for posting in the wrong
place.
