### ISSUE TITLE
Remove footnoteReturnLinkContents from list of global params

### ISSUE THREAD

**Issue by Brixy** [gohugoio/hugoDocs#971]
Hi!

`footnoteReturnLinkContents` (and probably some other params) do not work as [global params](https://gohugo.io/getting-started/configuration/) with Goldmark. It probably should be removed from this docs page. 

It is correctly listed as a [blackfriday config param](https://gohugo.io/getting-started/configuration-markup).

**Comment by bep** [comment]
Yes, it should.
