### ISSUE TITLE
Document lang.Translate template function

### ISSUE THREAD

**Issue by digitalcraftsman** [gohugoio/hugoDocs#98]
Currently, it's not documented on it's own.

/cc @bep - are `i18n` and `T` just aliases for `lang.Translate`?

**Comment by moorereason** [comment]
@digitalcraftsman,
Yes, they are aliases.  All aliases are defined within the `init.go` file of each namespace package.  In this instance, they are here:

https://github.com/gohugoio/hugo/blob/d8717cd4c74e80ea8e20adead9321412a2d76022/tpl/lang/init.go#L33.

**Comment by digitalcraftsman** [comment]
`i18n` is the most common usage in templates I guess. Let's document this as default name and mention the others as aliases.

**Comment by moorereason** [comment]
I'm not sure how you're planning to move to namespaces in the docs structure, but keep in mind that we will likely try to generate the functions md files from `docs.json` as some point (which bep generates from godoc comments and the info in the package's `init.go`).  If you let the Go packages lead the way, `lang.Translate` will be the canonical function name and `i18n` will be an alias.

**Comment by digitalcraftsman** [comment]
I already saw this in the Gitter channel. Thanks for the reminder.

**Comment by deining** [comment]
`lang.Translate` function is already documented [here](https://gohugo.io/functions/lang/#langtranslate).
With #1914 merged the function will appear as an alias in the signature of the `i18n` function.
Therefore I think this ticket can be closed.
