### ISSUE TITLE
Update hugoDocs with files modified by hugo pull #6640

### ISSUE THREAD

**Issue by zaitseff** [gohugoio/hugoDocs#983]
I note that my hugo pull #6640 <https://github.com/gohugoio/hugo/pull/6640> was recently applied to the hugo repository.  However, documentation files in that pull have not yet been migrated to the hugoDocs repository.  This issue is to remind the maintainers of the need to do so.  Thanks!

**Comment by bep** [comment]
It will happen automatically as part of the release (Monday).
