### ISSUE TITLE
Document math.Log template func

### ISSUE THREAD

**Issue by digitalcraftsman** [gohugoio/hugoDocs#99]
The documentation might accidentely got lost during the merge of the old and new docs.

Here are the original ones: https://github.com/gohugoio/hugo/commit/34c566773a1364077e1397daece85b22948dc721#diff-b0459ca979b7cda94af36279c6f4c38fR436

**Comment by rdwatters** [comment]
> The documentation might accidentely got lost during

Definitely did. Sorry I missed this one.
